### ISSUE TITLE
Cheats are not hooked to the Mednafen PSX core

### ISSUE THREAD

**Issue by Warriors-Blade** [libretro/beetle-psx-libretro#10]
Seems this has not been addressed yet, can we have this fixed soon if possible?

**Comment by christopher-s** [comment]
Despite the cheat options being available in the "Quick Menu", I don't believe cheats are working yet.

Is this on anybody's radar for implementation? Would be great to get cheat support.

**Comment by adespoton** [comment]
In the meantime, using a GameShark 5 image works.

**Comment by Arviel** [comment]
I would love to have cheat support. It is the only thing that makes me go back to EPSXE.

**Comment by micochops** [comment]
Hello!

Says in this [post](https://www.patreon.com/posts/other-core-8583207):
* Improved/**_added cheat support_** for PicoDrive, Genesis Plus GX, **_Beetle PSX_**, and others!

Can anyone confirm if cheats are now working?

Thanks!

**Comment by willismonroe** [comment]
Any confirmation whether these work?
