### ISSUE TITLE
Left analog not reaching max value while tilting straight up in 'Ape Escape'

### ISSUE THREAD

**Issue by prataczak** [libretro/beetle-psx-libretro#106]
I'm using a PS3 controller with an 8bitdo retro receiver hooked up to my PC, I can confirm the analog functions normally in other emulators like Mupen that require it.

Basically, when you tilt straight up, he walks at a moderate pace instead of running at full speed. Tilting even slightly left or right will make him run. Every other direction reaches max value fine.

Kind of strange actually, because I noticed the Android version of pcsx2 rearmed retroarch core did the exact same thing.

**Comment by simias** [comment]
Could be related to #40 although you seem to be describing the opposite problem (your controller seems to have a bigger radius than the native one).

I'm going to try to implement the calibration process I had in mind, we'll see if it fixes your problem as well.

**Comment by prataczak** [comment]
The thing is, it doesn't even seem like the character is accelerating when traveling through the 'up' plane.

Every other direction is fine, but if you press straight up, there's no acceleration.

Can someone else confirm that this is a problem?

**Comment by simias** [comment]
Can you use a program to read the raw values returned by the joystick? I think windows has a calibration program like that built in but I'm not certain.

**Comment by saftle** [comment]
@prataczak most likely you have Digital to Analog enabled while Dual Shock being enabled at the same time. See this issue: https://github.com/libretro/beetle-psx-libretro/issues/78. Sadly when you have both enabled, the Digital to Analog takes precedence over Dual Shock. This is the same issue that the person in the aforementioned issue had.

**Comment by Awakened0** [comment]
> A more elegant solution would be amazing.

I use overrides for games that support analog containing these settings:

> input_libretro_device_p1 = "517"
input_player1_analog_dpad_mode = "0"

There are few enough PSX games that properly support analog (some like Chrono Cross just map digital movement to the analog) that it wasn't that big a deal to make them.

**Comment by prataczak** [comment]
Saftle, I don't have Analog to Digital enabled neither in the main input settings  for player 1 (2nd setting from the top in RetroArch, right?), nor the "Quick Menu" settings.

Simias, again, other emus work fine. In Mupen64, Mario slightly walks when barely pressing up, and he sprints when tilting all the way.

Guys I appreciate your input but what I'd really like is for you to take 60 seconds and confirm one way or the other "Yes" this core has issues with "Ape Escape" while tilting straight up (has to be *straight* up - even slightly to the left or right is fine!), or no, everything is fine on my end.

Speculation isn't as useful as empirical evidence, you know?

**Comment by prataczak** [comment]
![2016-10-07 1](https://cloud.githubusercontent.com/assets/12243933/19207577/140b5344-8cc0-11e6-8599-bc36c3033c1b.png)
![2016-10-07 2](https://cloud.githubusercontent.com/assets/12243933/19207579/140d6b66-8cc0-11e6-976e-ee50a12eb5fe.png)
![2016-10-07 3](https://cloud.githubusercontent.com/assets/12243933/19207576/140b6424-8cc0-11e6-9ade-80949a3623d8.png)
![2016-10-07 0](https://cloud.githubusercontent.com/assets/12243933/19207578/140ba876-8cc0-11e6-8f49-8c0ee2da46c3.png)
 Pics of me using that windows calibration tool you spoke of.

**Comment by prataczak** [comment]
![2016-10-07 5](https://cloud.githubusercontent.com/assets/12243933/19207638/972313c0-8cc0-11e6-99b4-2908deb50433.png)
![2016-10-07 6](https://cloud.githubusercontent.com/assets/12243933/19207639/97299e3e-8cc0-11e6-9362-a207a564451d.png)

Proof that my settings aren't to blame.

**Comment by prataczak** [comment]
Also to clarify, previously I stated that it seemed like there was no acceleration while pressing straight up.

That's not completely true. The character does seem to go from a *very slow* walk to a moderate paced walk. He just doesn't move any faster than that when pressed all the way up.

**Comment by prataczak** [comment]
![2016-10-07 8](https://cloud.githubusercontent.com/assets/12243933/19208132/8b5feee2-8cc4-11e6-9610-a33f09bf4cf3.png)
![2016-10-07 9](https://cloud.githubusercontent.com/assets/12243933/19208128/8b5e0bcc-8cc4-11e6-92b3-2cc136fd5885.png)
![2016-10-07 10](https://cloud.githubusercontent.com/assets/12243933/19208131/8b6006e8-8cc4-11e6-9e18-4d6ffb8030d0.png)
![2016-10-07 11](https://cloud.githubusercontent.com/assets/12243933/19208129/8b5ebf54-8cc4-11e6-879b-8bb2059fd59b.png)
![2016-10-07 12](https://cloud.githubusercontent.com/assets/12243933/19208130/8b5ec468-8cc4-11e6-8a41-a21db3800da0.png)
![2016-10-07 7](https://cloud.githubusercontent.com/assets/12243933/19208133/8b610912-8cc4-11e6-9c2f-b4b762796e53.png)
Pics of the actual raw data values in the calibration tool.

**Comment by fr500** [comment]
> 

    A more elegant solution would be amazing.

I use overrides for games that support analog containing these settings:

    input_libretro_device_p1 = "517"
    input_player1_analog_dpad_mode = "0"

There are few enough PSX games that properly support analog (some like Chrono Cross just map digital movement to the analog) that it wasn't that big a deal to make them.

Also remaps save these values too, so you don't even need overrides.

**Comment by Awakened0** [comment]
> Guys I appreciate your input but what I'd really like is for you to take 60 seconds and confirm one way or the other "Yes" this core has issues with "Ape Escape" while tilting straight up (has to be straight up - even slightly to the left or right is fine!), or no, everything is fine on my end.

I played all the way through the game with my Xbox Elite controller last year and had no problem getting a full speed run when pushing the stick straight forward. I just tested the latest nightly and without doing any of the new calibration stuff, I can still run fine in any direction.

IIRC, my Wii U Pro controller with a Mayflash adapter in xinput mode had an issue where it'd flip between fast walk and run on the forward diagonals. Straight forward was fine. But that pad also had that issue with Bayo 2 on the actual Wii U, so that seemed like a hardware problem.

**Comment by fr500** [comment]
I just tried with a DS3 with SCP toolkit and I can walk/run without problems in dualshock mode

**Comment by prataczak** [comment]
> IIRC, my Wii U Pro controller with a Mayflash adapter in xinput mode had an issue where it'd flip between fast walk and run on the forward diagonals. Straight forward was fine. But that pad also had that issue with Bayo 2 on the actual Wii U, so that seemed like a hardware problem.

> 


I just plugged in my Micro$uck 360 wired controller and it worked perfectly. Weird.

Yeah this 8bitdo adapter uses X-Input. Seems like there's something wrong with the core though, since other cores have no issue.

**Comment by Awakened0** [comment]
I think Ape Escape might just be one of those games that doesn't give you much leeway because of the run state radius size. Like, it really wants the stick up against the plastic or very close to it.

**Comment by prataczak** [comment]
But maybe it's the way the the core handles X-Input also, because I just tried my 8bitdo NES30Pro, and it also worked flawlessly, and you mentioned you had issues when you were using X-Input.

**Comment by Awakened0** [comment]
The Elite controller is X-input too...

**Comment by fr500** [comment]
The core doesn't change with xinput or dinput or any driver for the matter. RetroArch reads the values and normalizes them to -32768....32678 and passes the values to the core.

**Comment by prataczak** [comment]
I tried the direct input driver, and the up/down was inverted, but everything worked, so I was hopeful.

I went into the controls and switched them, and the same problem came back.

**Comment by prataczak** [comment]
Well, I borrowed a friend's bluetooth dongle, and starting using the 'better ds3' tool, and now everything's working fine for me. Maybe there's an issue with my 8bitdo 'retro receiver' that doesn't play well with that particular core, who knows?

Still baffled that it seems to work fine with all the other cores though.

**Comment by simias** [comment]
@prataczak I'm not sure it's related after all but I've added a self-calibration option to beetle yesterday, maybe it could help if your issue is deadzone-related.

**Comment by JacksonBailey** [comment]
I get this issue on PSX 1.13 with an XBox 360 controller too. I don't know how relevant this is but I found this issue through Google.

**Comment by OptimalJew** [comment]
Noticed this immediately upon starting a Parasite Eve playthrough, where you couldn't reach 'run' speed with diagonal movement. Enabled Analog self-calibration, and never had a problem through the rest of the game. I also played through the entirety of Ape Escape with it enabled, and it worked great there as well.

**Comment by rz5** [comment]
@prataczak - I'll close this issue for now. Hopefully you'll see this ping and report back whether or not simias's self-calibration feature fixes your problem or not. I'm closing this for now
