### ISSUE TITLE
Black Screen in Aladdin in Nasira's Revenge.

### ISSUE THREAD

**Issue by lasers** [libretro/beetle-psx-libretro#109]
According to Wikipedia, there are minigames at the end of each level: pie throwing, surfing, skate-boarding, and cloud jumping.

When I enter the door to complete the level, I get a black screen instead of completed level statistics and mini games. 

![How it should looks like](https://cloud.githubusercontent.com/assets/852504/19232736/06010602-8ea7-11e6-82ed-8c4191b3ae3e.gif)

**Comment by saftle** [comment]
Please verify this against Mednafen standalone. If it is a standalone issue, then it would first need to be fixed on Mednafen's end and reported in their forums.

**Comment by lasers** [comment]
Verified right now. Mednafen standalone got this game far than beetle-psx-libretro.
![out2](https://cloud.githubusercontent.com/assets/852504/19237412/5dced1aa-8ec2-11e6-9551-1ea9483336ca.png)

**Comment by OptimalJew** [comment]
Appears to be working in the latest version.

Stat Screen
![disney s aladdin in nasira s revenge usa -171008-104619](https://user-images.githubusercontent.com/31424143/31317953-fdc81400-ac17-11e7-92bf-e946feaee886.png)
Slot Machine
![disney s aladdin in nasira s revenge usa -171008-104642](https://user-images.githubusercontent.com/31424143/31317954-01f2460e-ac18-11e7-86b9-079373c4750d.png)
Cloud Jumping
![disney s aladdin in nasira s revenge usa -171008-104655](https://user-images.githubusercontent.com/31424143/31317955-0458d9d0-ac18-11e7-916b-a7ca4ef80688.png)

**Comment by rz5** [comment]
Thanks for reporting it @OptimalJew, one less issue to track. @lasers, try it on your side too. I'll close this for now.
