### ISSUE TITLE
dualshock analog axis scale option?

### ISSUE THREAD

**Issue by Yoten** [libretro/beetle-psx-libretro#11]
Hello,

The original Mednafen had options to adjust the axis scale on dualshock and dualanalog controllers to deal with logical range issues that would cause movement problems in some games. An example is given here:

http://mednafen.fobby.net/documentation/psx.html#psx.input.port1.dualshock.axis_scale

Is there any chance that these options could be added into this core so that it could be utilized by various front-ends like retroarch?

Thanks!

**Comment by saftle** [comment]
@Yoten Please take a look at the solution here: https://github.com/libretro/beetle-psx-libretro/issues/78. Maybe it is a similar issue.

**Comment by rz5** [comment]
simias added the 'Analog self-calibration' core option which should help with this problem. Exposing 'psx.input.port1.dualshock.axis_scale' as an additional core option could also be done too but for now I'm closing this issue.
