### ISSUE TITLE
Cropping for NTSC games with black bars

### ISSUE THREAD

**Issue by needo2** [libretro/beetle-psx-libretro#120]
is_pal games getting their black bars cropped but there are some NTSC games with black bars too.
Ones I know of are the Spyro series

**Comment by shinra358** [comment]
if you don't want to wait, you can save a pergame shader setting with the image-adjustment shader.

**Comment by hizzlekizzle** [comment]
I would assume this is a "won't fix" anyway, as those black bars are actually in the game. Between image-adjustment and first/last scanline core options, you should be able to eliminate/hide them on a game-by-game basis, it just won't be automatic.

**Comment by lones710** [comment]
Another nice option is to use a custom viewport for removing black bars, like in crash bandicoot 1-3

**Comment by needo2** [comment]
Okay, I was going to say "Yeah this is not optimal" but I tried the same rom (Spyro the Dragon [NTSC]) with no$psx* and it doesn't have the letterbox effect

*I was looking for a debugger so maybe I could write a cheat to remove the letterbox and implement widescreen

**Comment by lones710** [comment]
honestly, the letterboxes ARE THERE on a real ps. so why should we patch it away, doesn't make sense! For Crash 1 to Crash 3, use these options to remove the letterbox bars( so to say "zoom" on the picture) (options for 1920x1080 resolution):

custom_viewport_width = "1600"
custom_viewport_height = "1200"
custom_viewport_x = "160"
custom_viewport_y = "-60"
aspect_ratio_index = "22"

**Comment by needo2** [comment]
I've been using that config overload for Spyro 2 for a while.

I also asked RetroArch for a "Zoom" multiplier option which adapts to varied resolutions and you'll only need to configure one option instead of 5

As for why to patch letterbox, these games are intended for 10/7 so 1920x1080 monitor should play them ~1542x1080 but they play on 1440x1008 in a small box inside the screen

Another thing is Symphony of the Night is letterbox in game but not on main menu. Which is why I went to search for a patch in the first place.

**Comment by hizzlekizzle** [comment]
What's the 10/7 thing based on?

PS1s can output a variety of resolutions and it can switch among them many times in a single game. Most have 240 vertical lines of resolution with 224 active lines, but this doubles in interlaced modes, which were commonly used in menus but also for some in-game stuff, like Tekken 3. Horizontal resolution bounced around 256, 320, 512, 640...

If you're using the full 240-scanline frame, that's a 4.5x scale on 1080p. 224*4.5=1008 and 320*4.5=1440. So, mystery solved there. The rest of the black borders are there in-game and always have been, and they wax and wane at various points in the game. You're never going to get rid of all of them.

**Comment by ggdrt** [comment]
Closing this issue since the `Crop Horizontal Overscan` and `Initial/Last Scanline` core options should be sufficient for cropping in-game borders.
