### ISSUE TITLE
Widescreen option broken in Vulkan renderer

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#124]
When using the vulkan renderer, the widescreen option does not work. It appears to attempt to work, but only adjusts the image within the same 4:3 resolution bounds.

This was confirmed by other users in IRC and Discord.

The resolution is set to "Core Provided".

**Comment by simias** [comment]
The vulkan code probably doesn't adjust the `aspect_ratio` when calling `RETRO_ENVIRONMENT_SET_GEOMETRY` in widescreen mode.

The vulkan code doesn't seem to call this environment at all which surprises me.

**Comment by simias** [comment]
The relevant code in the GL path is here by the way: https://github.com/libretro/beetle-psx-libretro/blob/master/rustation-libretro/src/renderer/GlRenderer.cpp#L387-L410

**Comment by rz5** [comment]
Should be fixed in the latest commit.

**Comment by saftle** [comment]
Thanks! The commit worked perfectly.
