### ISSUE TITLE
Vulkan Renderer: Garbled Graphics before/after FMV

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#126]
On most games that play FMVs: Wipeout, Chrono Cross, etc; garbled graphics are shown before and after the FMV has been played. This is always reproducable and appears to not be option dependent.

Here is a screenshot showcasing the error in Breath of Fire III as an example (right after the Capcom FMV): 
![breath of fire iii-161204-010622](https://cloud.githubusercontent.com/assets/852777/20863724/ee6ebc42-b9d4-11e6-97df-56d797b34b2c.png)

**Comment by rz5** [comment]
@saftle: That screenshot is not related to garbage happening between FMVs, that was @fr500 getting bugs from an old Nvidia driver.

I made a PR trying to fix this. Not getting said garbage in Wipeout 3 anymore with the patch.

**Comment by saftle** [comment]
Thanks for the reminder. Just replaced it with a more relevant one.

**Comment by saftle** [comment]
The fix worked perfectly. Thanks @rz5 !
