### ISSUE TITLE
Add support for mouse and lightguns

### ISSUE THREAD

**Issue by OmegaXII** [libretro/beetle-psx-libretro#13]
Currently, you cannot use the PSX mouse or either of the lightgun input methods in the libretro port.

**Comment by Rukumouru** [comment]
This is my most wanted feature as well. AFAIK there's no way to get this working through libretro right now.

**Comment by twinaphex** [comment]
It's not a libretro API implementation, just unimplemented in the core.

**Comment by Phiben** [comment]
Is there any hope for this to happen in the near future? I really don´t want to use epsxe anymore!

**Comment by hiddenasbestos** [comment]
I added mouse support with pull request #261.

**Comment by hiddenasbestos** [comment]
Guncon support added with pull request #263.

**Comment by hiddenasbestos** [comment]
Aaaand.... Konami Justifier is now supported with pull request #264.

**Comment by saftle** [comment]
@hiddenasbestos awesome work!
