### ISSUE TITLE
Game Crash Problem (Vulkan)

### ISSUE THREAD

**Issue by FiLeonard** [libretro/beetle-psx-libretro#132]
Tony Hawk's Pro Skater 2 crashes immediatly when used with the attached memcard. (Vulcan)  It has been created with pcsx-rearmed. ePSXe loads it as well.  Using this memcard with other games in Beetle PSX, it boots normally. (Tried with Driver.)
I tried other memcards created by pcsx-rearmed and they work as expected in Beetle PSX. (e.g. MGS) Of course, method is libretro.

Just tried to boot it in the non-HW core of mednafen and there it boots.

In mednafen HW it gives me an access violation in nvoglv64.dll Maybe a problem with the nvidia drivers. But what has this to do with the memcard?
 
[Tony Hawk's Pro Skater 2 (Europe).zip](https://github.com/libretro/beetle-psx-libretro/files/631210/Tony.Hawk.s.Pro.Skater.2.Europe.zip)

**Comment by FiLeonard** [comment]
Just tried to boot it in thee non-HW version and there it boots.

**Comment by FiLeonard** [comment]
OK dont know what is going. After renaming it into the .mcr scheme, and using mednafen save method ist crashed again. after renaming it back to .srm and and switching back to libretro method it booted. Although it alway crashed before. I dont know.

**Comment by simias** [comment]
I can't find anything obviously wrong with the memory card format. Only one file in one block, no broken sector, nothing seems incoherent:

```
File #1:
  File name: BESLES-02908CLHAG01
  Title: ＴＨＰＳ２　ＣＡＲＥＥＲー　ＣＡＲＥＥＲ　Ａ
  File size (reported): 8192B (1 blocks)
  Blocks: 1 (1 total)

Block 1: used (First)
  File name: BESLES-02908CLHAG01
  File size: 8192B (1 block)
  Metadata checksum: 0x21 (OK)
```

**Comment by FiLeonard** [comment]
Well, I dont actually know what is going on. Played around a bit again. I think THPS 2 just crashes sometimes with the vulkan renderer. it crashes even without with or without memcard. The memcard issue probably was a distraction. Really weird. 
I'm using win10, 64bit. Geforce 750m gt with driver 376.09. Sorry everything is just weird. Aller other games i tried work and don't crash. Maybe someone has the game and is able to confirm a problem.

**Comment by FiLeonard** [comment]
Ok now i am able to reproduce the problem. Starting retroarch and immediatly booting THPS2 results in a crash with beetle psx. Starting another game first with beetle PSX, then closing it, THEN starting THPS2, it boots.

**Comment by simias** [comment]
Just to clarify: this is not related to the memory card image at all anymore, right?

**Comment by FiLeonard** [comment]
Right. I'm sorry for that. i mistook the memcard for producing the error, but probably i reproduced the aforementioned behavior while testing the memcards.

**Comment by FiLeonard** [comment]
Okay these titles seems to have this problem:
Tekken 3: SCES 01237
THPS 2:  SLES-02908.
gex: enter the gecko SLUS-00598
Street Fighter Alpha 3

What works as expected:
Driver
FF7
FF8
FF9
Chrono Cross
GT2
G-Police
MGS
NFS - Porsche
NFS3
Parasite Eve 2
Ridge Racer 4
THPS 4
Twisted Metal 2
Vigilante 8

**Comment by FiLeonard** [comment]
Problem vanished
