### ISSUE TITLE
[Vulkan backend] Internal resolution setting is ignored.

### ISSUE THREAD

**Issue by mac1202** [libretro/beetle-psx-libretro#133]
Hi with the latest git version using the Vulkan backend When you launch a game the internal resolution is set to 1X whenever the setting you set in config. Changing the setting once the game is started properly change the resolution.
I also have another question is this normal that the vulkan backend has the same performance as software backend. I can't go higher than 4X internal resolution without making the game terribly slow. When used the opengl backend I could go to 8X and game was running smooth.
And another thing using slang shader I got a black screen, I have to use cg shader to make it work. Vulkan based core wasnt supposed to only work with slang shader ?

**Comment by fr500** [comment]
There is no way for cg to work on vulkan so it means it's probably falling back to GL
Do you have RetroArch set to vulkan?

**Comment by mac1202** [comment]
Hi your right stupid forget to set vulkan in video driver setting.
Now slang shader work. But the problem with internal resolution not properly set at retroarch start is still there and is the same thing with the shader it isnt applied at start I have to hit apply shader change once in game for the shader to be applied.

**Comment by fr500** [comment]
I'll check it when I get home, I re-factored core options yesterday.

**Comment by mac1202** [comment]
Yeah should be something wrong with the core option, I have deleted all beetle_psx line from my retroarch-core-options.cfg, reload retroarch, reconfigure core option and quit. Reopen retroarch-core-options.cfg and no beetle_psx line inside.

**Comment by fr500** [comment]
That sounds more like something wrong in your setup

**Comment by mac1202** [comment]
Just tried the same thing beetle saturn core to check and core option are properly rewritten in retroarch-core-options.cfg file. Will try to compile an older version of beetle-psx to be sure.

**Comment by fr500** [comment]
Writing doesn't depend on the core though....
Writing is done by the frontend. 

Maybe it's crashing on exit or something?
Or maybe you accidentaly touched "Create game options file"? and now it's saving in mednafen psx hw/gamename.opt

**Comment by mac1202** [comment]
Yeah it probably crash when I try previously. Because I just try again and it write the core option inside the file. Here is the setting : 
```
beetle_psx_renderer = "vulkan"
beetle_psx_renderer_software_fb = "enabled"
beetle_psx_adaptive_smoothing = "enabled"
beetle_psx_internal_resolution = "4x"
beetle_psx_pgxp_mode = "memory + CPU"
beetle_psx_pgxp_caching = "enabled"
beetle_psx_pgxp_texture = "enabled"
beetle_psx_initial_scanline = "0"
beetle_psx_last_scanline = "239"
beetle_psx_initial_scanline_pal = "0"
beetle_psx_last_scanline_pal = "287"
beetle_psx_frame_duping_enable = "disabled"
beetle_psx_widescreen_hack = "disabled"
beetle_psx_crop_overscan = "enabled"
beetle_psx_image_crop = "disabled"
beetle_psx_image_offset = "disabled"
beetle_psx_display_internal_framerate = "disabled"
beetle_psx_analog_calibration = "disabled"
beetle_psx_analog_toggle = "disabled"
beetle_psx_enable_multitap_port1 = "disabled"
beetle_psx_enable_multitap_port2 = "disabled"
beetle_psx_cpu_overclock = "enabled"
beetle_psx_cdimagecache = "disabled"
beetle_psx_skipbios = "disabled"
beetle_psx_use_mednafen_memcard0_method = "libretro"
beetle_psx_enable_memcard1 = "enabled"
beetle_psx_shared_memory_cards = "disabled"
```
Now there is just the problem with internal resolution not properly applied at start.

**Comment by fr500** [comment]
Are you sure you're in master?
works fine for me
also the hw core coptions are beetle_psx_hw now

**Comment by mac1202** [comment]
I use this pkgbuild to build the lib https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libretro-mednafen-psx-git and use the mednafen_psx_hw_libretro.so.
And here the output of the terminal when I launch it http://pastebin.com/ZiHsFuak

**Comment by mac1202** [comment]
Something is probably wrong with my setup because 
```
ldd /usr/lib/libretro/mednafen_psx_hw_libretro.so
linux-vdso.so.1 (0x00007ffc32fa1000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fac65137000)
libGL.so.1 => /usr/lib/libGL.so.1 (0x00007fac64ebf000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fac64b37000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007fac64833000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fac6461c000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007fac6427e000)
/usr/lib64/ld-linux-x86-64.so.2 (0x0000560f82875000)
libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007fac6404b000)
libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fac63d0c000)
libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fac63afa000)
libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007fac63824000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fac63620000)   
libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fac633f7000)
libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fac631f1000)
libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fac62feb000)
```
Should probably return something about vulkan if everything was right.

**Comment by mac1202** [comment]
Seems like I have figured out how to fix it.
instead of setting HAVE_VULKAN = 1 in makefile I have add a line HAVE_HW = 1
And my main retroarch config was set to video driver gl and I had an overwrite file for mednafen with video driver vulkan. But with this setup it doesnt work I have to set video driver to vulkan in my main retroarch config file. Now it seems to work. Thanks a lot for your time.
