### ISSUE TITLE
dualshock digital mode not working properly with old games

### ISSUE THREAD

**Issue by bigboo3000** [libretro/beetle-psx-libretro#134]
Set the controller to dualshock (or dualanalog)
Set "DualShock Analog button toggle"  to "**disabled**"
Launch an old game (like castlevania) > controls doesn't works

A real ps1 with a dualshock connected is the same as this configuration (analog disabled by default) and controls are working.

So I think this option "DualShock Analog button toggle" is not working well as this option set to disabled should be transparent to old games.

**Comment by saftle** [comment]
The toggle option doesn't toggle whether DS is enabled, it toggles whether the toggle itself is enabled. Let me explain. 

Basically, if you have the input set as DS and have the toggle off, it will act as if DS is always on (making most games unplayable). However, with the toggle on, you can hold L1, L2, R1, R2, Start, and Select for a few seconds to turn DS on/off making all games playable. 

I hope this makes more sense.

**Comment by saftle** [comment]
This issue can be closed as well. It was a user support issue in this case.
