### ISSUE TITLE
[OpenGL] Internal resolution - partial screen

### ISSUE THREAD

**Issue by alondero** [libretro/beetle-psx-libretro#136]
When changing the internal resolution settings in the most recent build the portion of the screen that doesn't fall into the bottom left most (assuming) 320x240 is cropped away. This is happening on the <s>Vulkan</s> and OpenGL backends.
![colin mcrae rally 2 0 usa -161211-111017](https://cloud.githubusercontent.com/assets/1269060/21079725/c1bc7dba-bf92-11e6-931d-a706d01722af.png)
My core settings are:
`beetle_psx_hw_renderer = "opengl"
beetle_psx_hw_renderer_software_fb = "enabled"
beetle_psx_hw_adaptive_smoothing = "enabled"
beetle_psx_hw_internal_resolution = "8x"
beetle_psx_hw_filter = "bilinear"
beetle_psx_hw_internal_color_depth = "32bpp"
beetle_psx_hw_scale_dither = "enabled"
beetle_psx_hw_wireframe = "disabled"
beetle_psx_hw_display_vram = "disabled"
beetle_psx_hw_pgxp_mode = "memory + CPU"
beetle_psx_hw_pgxp_caching = "enabled"
beetle_psx_hw_pgxp_texture = "enabled"
beetle_psx_hw_initial_scanline = "0"
beetle_psx_hw_last_scanline = "239"
beetle_psx_hw_initial_scanline_pal = "0"
beetle_psx_hw_last_scanline_pal = "287"
beetle_psx_hw_frame_duping_enable = "enabled"
beetle_psx_hw_widescreen_hack = "enabled"
beetle_psx_hw_crop_overscan = "enabled"
beetle_psx_hw_image_crop = "disabled"
beetle_psx_hw_image_offset = "disabled"
beetle_psx_hw_display_internal_framerate = "disabled"
beetle_psx_hw_analog_calibration = "disabled"
beetle_psx_hw_analog_toggle = "disabled"
beetle_psx_hw_enable_multitap_port1 = "disabled"
beetle_psx_hw_enable_multitap_port2 = "disabled"
beetle_psx_hw_cpu_overclock = "enabled"
beetle_psx_hw_cdimagecache = "enabled"
beetle_psx_hw_skipbios = "enabled"
beetle_psx_hw_use_mednafen_memcard0_method = "libretro"
beetle_psx_hw_enable_memcard1 = "enabled"
beetle_psx_hw_shared_memory_cards = "disabled"
beetle_psx_hw_dither_mode = "internal resolution"`

**Comment by rz5** [comment]
@alondero: I can confirm this bug for the GL renderer. But the vulkan renderer does not have this bug on my end.

If you wanted to try the vk renderer, you most likely forgot to set your video driver to 'vulkan'.

**Comment by alondero** [comment]
You're right! Looks like I was facing the issue described here https://github.com/libretro/RetroArch/issues/3297, where the config override for video_driver wasn't being honoured. I'll change the title of this ticket.

**Comment by simias** [comment]
That's odd. I can't reproduce that on my end.

I've pushed a few modifications to the GL renderer since you've opened this bug, can you confirm if it's still happening with the new version?

**Comment by saftle** [comment]
@simias the new commits haven't landed on the windows buildbot build yet. I'm guessing it's failing to compile since the 6th.

**Comment by rz5** [comment]
I can confirm that this is still happening on Windows 10 + Nvidia + MSYS2

https://cloud.githubusercontent.com/assets/8117159/21120240/436de390-c0be-11e6-9676-c835a23e7600.png

**Comment by simias** [comment]
@saftle Uh, any idea why it's failing? Does the buildbot log that somewhere?

@rz5 Looks like this odd bug @twinaphex had and I can't reproduce. Does it happen with every game?

**Comment by saftle** [comment]
I asked in IRC. I was told the buildbot has been down the last few days. Not sure why exactly.

**Comment by rz5** [comment]
@simias I'm only testing with Mega Man X4 at the moment and the results are this:
1x IR - No problem
2x - No problem
4x - About a third of the screen is black
8x - Less than the 4th quadrant is drawn

I just built what's in the repo with HAVE_HW=1 DEBUG=1, if I try to change IR, I get a failed assertion:

buffer.h, Line 195
m != NULL

**Comment by tuluse** [comment]
Just updated the core, and I'm having this problem as well.

This is 2x, I have a Radeon R9 285.

![retroarch-1213-204107](https://cloud.githubusercontent.com/assets/10588046/21167820/c58a4970-c174-11e6-85c6-1f52f01d4b9e.png)

Also note the Sony Computer Entertainment text is not visible. It quickly blinks visible for a moment and goes away.

**Comment by JacobAL** [comment]
Just updated my core. I'd prefer to use OGL because vulkan doesn't allow me to unthrottle speed while vsync is on. 
[http://i.imgur.com/Wp9aaeM.png](url)

**Comment by simias** [comment]
I'm going to try to reproduce this again I guess. Just to be clear: is this issue game specific or does it happen all the time when you increase the internal res?

**Comment by JacobAL** [comment]
Here's all the games where it's happening for me. 4x res for all of them, all NTSC-U:
Alundra - http://i.imgur.com/iiXTe8u.png
Chrono trigger - http://i.imgur.com/4GrJrGU.png cutscene problems but the game seems normal
Crash Bandicoot - http://i.imgur.com/e0mN5YO.png
Crash 2 - http://i.imgur.com/e0mN5YO.png
Crash 3 - http://i.imgur.com/0dHfO9d.png
Crash Bash - http://i.imgur.com/aKeL9ZK.png Seems to have other issues going on as well, vectors appear to be going crazy
Crash Team Racing - http://i.imgur.com/nxZxzag.png
Croc - http://i.imgur.com/cIJ1KeX.jpg 
Digimon World - http://i.imgur.com/cHH7p8r.png
King's Field - http://i.imgur.com/bl8WXg1.png vectors going crazy here too
Medievil - http://i.imgur.com/udCWDTP.png
Medievil 2 - http://i.imgur.com/pxAvzGi.png
Ogre Battle - http://i.imgur.com/OOsypKb.png
Parappa - http://i.imgur.com/EtbZUEJ.png
Rayman - http://i.imgur.com/DFlWhDX.png
SaGa - http://i.imgur.com/MGu5lI3.png
Silent Bomber - http://i.imgur.com/JaP73ch.png
Silent Hill - http://i.imgur.com/wV4DDUq.png http://i.imgur.com/PeujqNF.png
Soul Blade - http://i.imgur.com/0J5yWJU.png vector issues here again, also it isn't picking up inputs which is odd
Spyro the Dragon - http://i.imgur.com/WFB7Zrs.png
Spyro 2 - http://i.imgur.com/wkRYUsf.png
Spyro 3 - http://i.imgur.com/K31cTKF.png
Strider 2 - http://i.imgur.com/hGSLPip.png
Suikoden - http://i.imgur.com/Qz2WURw.png
Suikoden 2 - http://i.imgur.com/D8yP2Dw.png
Tenchu - http://i.imgur.com/vkLz9Hs.png
Tenchu 2 - http://i.imgur.com/76Kb5Sm.png
Twisted metal - http://i.imgur.com/FSdSGy6.png
Vagrant Story - http://i.imgur.com/zYt2Vby.png
Valkyrie Profile - http://i.imgur.com/anXyDe1.png http://i.imgur.com/gF5EKGU.png

Every game I have seems to have problems. Chrono trigger seemed the best as it only had problems in cutscenes.

Also, I appear to be getting a lot of slowdown where there didn't used to be any whatsoever. Normally I'd be able to go at at least double speed, which was helpful for loading screens. Now I can't increase speed at all and at 1x speed I'm getting sub 60fps in most places.

Specs: http://i.imgur.com/jsYgbbS.png

**Comment by JacobAL** [comment]
Going back to a slightly older version, I notice that I still can't increase speed with OGL. Weird, definitely used to be possible in older builds. Maybe something to do with vsync. THat's not really an issue for this thread though.

**Comment by saftle** [comment]
The newest buildbot build for windows x64 has been built, and can confirm the issue still exists. I tested Brave Fencer Musashi with 8x.

**Comment by lones710** [comment]
The bug still isnt fixed, Running win10 + amd r9 280x! When will there be a fix?

**Comment by fr500** [comment]
when it's ready

**Comment by HellishINC** [comment]
This is still an issue for me. Using Arch 4.9.7 + mesa-git. GCN1.0 (280x) does not have Vulkan support at this point in time, so that's not an option.

**Comment by Tenolius** [comment]
I am having issues with both **Vulkan** and **GL** ( I am corrrectly setting both the driver and render to match each one.) The issue only occurs when setting the **internal resolution** to either **x4** or **x8.**

When setting to x4
**GL**
![crash bandicoot 2 - cortex strikes back usa -170221-001815](https://cloud.githubusercontent.com/assets/12527930/23156373/7d018122-f7cb-11e6-85b2-c7bbffa8cd8c.png)
**Vulkan**
![crash bandicoot 2 - cortex strikes back usa -170221-001756](https://cloud.githubusercontent.com/assets/12527930/23156375/8110ffc2-f7cb-11e6-812e-d2a8ff84c039.png)

When setting to x8
**GL**
![crash bandicoot 2 - cortex strikes back usa -170221-001901](https://cloud.githubusercontent.com/assets/12527930/23156376/83da8606-f7cb-11e6-9a64-b9e27f64b888.png)
**Vulkan**
![crash bandicoot 2 - cortex strikes back usa -170221-001911](https://cloud.githubusercontent.com/assets/12527930/23156379/875034c0-f7cb-11e6-8c24-d9f5d3bfd145.png)

**Comment by saftle** [comment]
@Tenolius Be sure that your driver is set to Vulkan as well (a retroarch restart is required), when testing Vulkan, since the GL renderer always defaults to your driver version, regardless of what you have set there. It looks like you just switched the GL Renderer from GL to Vulkan, but were still on GL the entire time.

**Comment by HellishINC** [comment]
Just an update, still an issue with Arch 4.9.11 + mesa 17 stable on FOSS driver.

**Comment by lones710** [comment]
this issue still persists in the newest build

**Comment by razorache** [comment]
Same here. The right 25% of the screen is all black when 2x resolution is enabled with both Vulkan and GL

**Comment by twinaphex** [comment]
Yes, I've pointed this out many times. Nothing has been done. Absolutely nothing.

Guess I should just take the plunge and start reverting the commit that led to this.

**Comment by lones710** [comment]
That would be so awesome. It is such a shame that this bug exists, as the vulkan renderer is not a real alternative yet because it has so many graphical bugs. The opengl renderer is the definitive hw renderer for now. I wish I would have enough programming skills to help fix.

**Comment by twinaphex** [comment]
Hopefully these issues should be gone now as of this commit -

https://github.com/libretro/beetle-psx-libretro/commit/38215d46630d82d354d5ce72e2163b82a206a275

I simply reverted @simias' last few commits and that seems to also fix the interlacing issues that happened in Dead or Alive.

Sorry that I left this issue stagnant for months, I was meaning to leave it to simias so as to not step on any toes but since nothing ever happened, I guess there is no harm done in taking the lead on this project to begin with.

**Comment by razorache** [comment]
@twinaphex Quick question, Will this fix be available in the updater version of RA or do I have to manually download this one? Sorry, new to this.

**Comment by rkapl** [comment]
That did not unfortunately help me. Even with 38215d4 i still see the left half of the screen only, sometimes only quarter (in BIOS etc).

I've tried git bisect and came to commit 2b2070b8 (option rework), which curiously should not have anything to do with the issue. Before this commit the 4x scaling with opengl works (the textures are filtered, so it seems it indeed is using the gl renderer).

**Comment by twinaphex** [comment]
Hmm @fr500, that seems to be your commit. Can you try guessing what the problem might be?

**Comment by twinaphex** [comment]
@razorache Weird, it works fine for me here.

**Comment by razorache** [comment]
@twinaphex I will try updating my drivers. Do you want my specs?

**Comment by razorache** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19499190/24334445/6583c7f8-1238-11e7-8cd2-0f22ea44bb1e.png)

Ok, this is about to get weird. When my gui and driver are set to a different renderers I get different results.

Gui: Vulkan + Core: Vulkan = Works fine
Gui: GL + Core: GL= Half black screen
Gui: Vulkan + Core: GL  =Half black screen
Gui: GL + Core: GL = All black screen

**Comment by tuluse** [comment]
I've updated to the latest nightly and I just get a black screen with opengl now. Vulkan and software work fine.

**Comment by fr500** [comment]
Load a GLSL shader before in any other core.

**Comment by tuluse** [comment]
I tried loading fxaa.glsl in PPSSPP and then starting a game in PSX, still get black screen

**Comment by rz5** [comment]
@alondero - this bug shouldn't be happening anymore, could you try it again and close the issue if it's fixed?

**Comment by axfelix** [comment]
I can no longer duplicate!

**Comment by alondero** [comment]
@rz5 Yes looks like this is fixed now 👍 Closing.
