### ISSUE TITLE
Cant load any m3u list in the PSX HW Core

### ISSUE THREAD

**Issue by DukeJP** [libretro/beetle-psx-libretro#142]
In the old software psx core my m3u files works ok. But the recent PSX HW core just crash to desktop with the message 
Microsoft Visual C++ Runtime Library
Runtime error!
Program:................/retroarch.exe
The application has requested the Runtime to terminate it in an unusual way.
Please contact.... bla bla bla...

I checked my m3u files and worked in the old core. Some games, like Metal Gear Solid and Chrono Cross are unplayable without this swaping option.
The Cue, and iso games works ok.

**Comment by saftle** [comment]
I'm able to run m3u files without problems with the HW vulkan and GL cores. Anyone else having this issue?

**Comment by DukeJP** [comment]
This morning i tried several options. A clean installation of retroarch, re-download the core. Its a m3u problem, when i load Metal Gear Solid Disc 1, works ok. Please, can upload the exact core you are using?

**Comment by saftle** [comment]
I'm using a regular nightly build core for win x64 via the buildbot, so need to upload in this case. Could you attach your m3u file and attch a screenshot showing the directory in which your bin/cue files reside?

**Comment by DukeJP** [comment]
http://imgur.com/xAQiloU

This m3u works ok with the software core.
[Final Fantasy IX.txt](https://github.com/libretro/beetle-psx-libretro/files/667514/Final.Fantasy.IX.txt)
(change the extension file from txt to m3u. I cant upload m3u here)

**Comment by DukeJP** [comment]
I think i find my error, or difference between cores. My actual m3u says:
H:\Playstation\Metal Gear Solid\Disc 1.cue
H:\Playstation\Metal Gear Solid\disc2.cue

If i modified to
Disc 1.cue
Disc 2.cue

Works ok!  I elimined the route and works!
