### ISSUE TITLE
Pepsi-Man No Music Even when Loading Cue sheet

### ISSUE THREAD

**Issue by shinra358** [libretro/beetle-psx-libretro#144]
Pepsi-Man, dumped as iso/cue (not bin/cue) because of a region  setting, doesn't play in-game music even when loaded from the cue sheet. Works fine in epsxe. Pepsi-Man is a japan region game.

**Comment by DukeJP** [comment]
Why not use a bin/cue instead? Works ok with libretro.

**Comment by DukeJP** [comment]
well, dump it to bin/cue instead. Works ok in libretro.

**Comment by shinra358** [comment]
ok, redump worked.
