### ISSUE TITLE
Various options removed from the standard PSX Mednafen core

### ISSUE THREAD

**Issue by Warriors-Blade** [libretro/beetle-psx-libretro#150]
Various options such as dithering removal are now absent in the recent builds of the core, can these please be added back in as the HW core is quite buggy and most such as myself tend to avoid it.

**Comment by hizzlekizzle** [comment]
I believe you can still use the hardware core and just set it to use the software renderer instead of opengl. They all use the same codebase, after all.

**Comment by Warriors-Blade** [comment]
Yes its in HW but its now missing from the standard core when its a function that works in the standard software core.

**Comment by Awakened0** [comment]
I think all the features that were removed in that commit didn't work in software, except dither mode. And maybe dither mode was removed because increasing the color depth didn't work in software. With dithering off you get bad color blending unless you can increase the color depth.

**Comment by Warriors-Blade** [comment]
It seemed fine to me, it was there as a preference and it worked fantastic in software.

**Comment by Awakened0** [comment]
The dithering options were re-enabled for software: edd467f6388a8436e626d38542081623a261e124 :)
