### ISSUE TITLE
Retropad w/ Analog does not support rumble

### ISSUE THREAD

**Issue by Kierek** [libretro/beetle-psx-libretro#153]
I experience some weird behaviour with psx core and rumble support. In retroarch I have my controller set as Retropad w/ Analog and rumble works fine in parallel n64 core with rumble expansion enabled.

With psx core though, I have to manually change gamepad type to DualShock, Retropad w/ Analog doesn't seem to advertise rumble support. When I load different core, or no core at all, the controller type is seen as "unknown".

Retropad w/ Analog
![zrzut ekranu z 2017-01-26 12-05-28](https://cloud.githubusercontent.com/assets/4080084/22329174/513ee710-e3c0-11e6-92f9-dd62954265e8.png)

Dualshock
![zrzut ekranu z 2017-01-26 12-05-59](https://cloud.githubusercontent.com/assets/4080084/22329242/aee0bd80-e3c0-11e6-85a1-dddef7714ca9.png)

After changin to dualshock and loading different core
![zrzut ekranu z 2017-01-26 12-06-25](https://cloud.githubusercontent.com/assets/4080084/22329268/d1b77d80-e3c0-11e6-9a35-147e0eaa9edd.png)

**Comment by spinktvis** [comment]
I can confirm this issue, using RetroArch git on Arch Linux with a Logitech Rumble pad 2. Other cores seem to work fine. Only Beetle PSX seems to default the controls to a non analog controller, maybe for compatibility? Setting beetle psx core options to dual shock fixes it, but in all other cores the gamepad will be unknown.

**Comment by Papermanzero** [comment]
This is a correct behavior. The original PSX controller does not have rumble.
The PS1 had 3 controller: The classic, the classic with analog and the dualshock.
The dualshock introduced rumble. So if you select dualshock and rumble works, this is the expected behavior.

**Comment by rz5** [comment]
Like @Papermanzero said above.

Rumble should in theory work if you set Quick Menu > Controls > User 1 Device Type to "DualShock". In theory, if this is set to "RetroPad w/ Analog", rumble should be working as well.
But seeing that this is an old issue and radius has done the Override commits, any bug @Kierek might have found might be fixed.

@Kierek, please reopen this if you can still reproduce your bug today.

**Comment by medievil1** [comment]
doesn't work for me... dualshock is selected but as soon as rumble should be generated.. the games fps drops to 10fps or lower. I have the same experience in other cores (dolphin, for example)
psx-rearmed doesn't slowdown, but doesn't rumble, stand alone emus work fine (dolphin, epsxe) and windows configuration rumbles just fine...even tried sdl2 as the joypad driver.. no rumble... (it is directinput, no xinput)
The slowdown/stutter is like the driver is hanging with rumble

**Comment by fr500** [comment]
rumble works fine on xinput at least
