### ISSUE TITLE
Bad sector? 13 error on loading

### ISSUE THREAD

**Issue by pepedopolous** [libretro/beetle-psx-libretro#154]
Since updating the Mednafen PSX HW core via the online updater, all of my PSX games fail to load. After the BIOS completes there is a message 'Bad Sector? 13' then nothing else happens.

Using retroarch-git Arch Linux AUR package.

**Comment by QorQor95** [comment]
How did you solve it please? have same issue

**Comment by pepedopolous** [comment]
Hello,

I think this was solved by another update to the core.
