### ISSUE TITLE
vulkan sw core crash 

### ISSUE THREAD

**Issue by shinra358** [libretro/beetle-psx-libretro#155]
when trying to increase the internal resolution in the software core on the vulkan backend, retroarch crashes.

**Comment by shinra358** [comment]
Seems to happen when I have the slang scalefx shader on. Doesn't seem to happen without it:

[url=https://postimg.org/image/64n1ywucj/][img]https://s29.postimg.org/64n1ywucj/Clipboard01.png[/img][/url]

**Comment by hizzlekizzle** [comment]
Same thing happens here but I'm pretty sure it's because the giant framebuffer size is killing it rather than anything wrong with the core or vulkan backend. In your screenshot, the framebuffer is 36864x36864, which is unbelievably huge.

**Comment by shinra358** [comment]
I noticed that. But what is it due to? Is it the particular shader I'm using? https://mega.nz/#!Ph01RBZA!bIEH6zexopIAdbJaCZuF2E1cSMsk84acpnNkzmuHoAw

I don't even know how it would get that high. I don't recall messing with anything that'll make it that huge. The cg shader doesn't seem to do that and ends up fine.

**Comment by hizzlekizzle** [comment]
for the psx core(s), the internal resolution affects the framebuffer size. If you set it to 8x, for example, the first pass will already be 320x240 (or 320x480 if interlaced) * 8.0 in both directions (that is, 2560x1920) then make that another 9x just from the scalefx passes and you're going to be in bad shape.

**Comment by shinra358** [comment]
I tried putting the shader on x1 while the emu core option on x4. It still crashed unfortunately. But if I disable the shader completely and have the emu option on x4, it doesnt crash.

**Comment by shinra358** [comment]
I just saw another user on your youtube channel ask when are we going to be able to use shaders along with the higher internal rez so I guess this isn't isolated after all.

**Comment by shinra358** [comment]
So since there hasn't been any more responses, I took it upon myself to finally test the crashes that dealt with playing through the xmb. The newest version fixes that problem. VB nor the sega games I mentioned above no longer crash when starting through the xmb. So now only the psx scalefx+>1x resolution crashes remain.

So now I'm asking, if the program detects that too much whatever is being used, it can use the maximum allowed and display what it can at that maximum instead of downright crashing. I'm sure something that be done like that since no other thing crashes because of using a scaler filter but retroarch and this core.

**Comment by rz5** [comment]
@shinra358, if the bug you reported in here is fixed, go ahead and close the issue. You referenced this issue from another issue that also appears to be solved.

**Comment by shinra358** [comment]
except it isn't. the only thing fixed is the stuff I referenced later on in the thread. not the initial thing which I stated in my previous comment.

**Comment by rz5** [comment]
@shinra358 - I can't replicate this.

Windows 10, i5-4690k, GTX 970;
Latest RA and beetle-psx-hw;
Vulkan driver and software renderer;

Increasing and decreasing the internal resolution does not cause a crash. It does cause missing textures but that's being tracked in issue #211.

So please do check again if the bug still happens. Also test it with the gl driver and WITHOUT shaders. 
If the core is crashing for you while using the scalefx shader, it's good to report it  but after reading @hizzlekizzle's thoughts, I'd like that's a beetle-psx bug or if it happens on any core where the requested framebuffer size is too big that we run out of memory and crash as a result.

**Comment by shinra358** [comment]
"Increasing and decreasing the internal resolution does not cause a crash."
It still does with scalefx.

"Also test it with the gl driver and WITHOUT shaders."
It works without shaders. The problem was with it working with scalefx.

" it's good to report it but after reading @hizzlekizzle's thoughts, I'd like that's a beetle-psx bug"
It's a beetle bug. Nothing else does this. As stated before, not n64 core, not any of the n64 standalones with xbrz, not even the dreamcast core has this problem (and dreamcast default texture size is much larger). This is the only thing that does this now. Software and hardware.
