### ISSUE TITLE
ios Black screen

### ISSUE THREAD

**Issue by rbissoli** [libretro/beetle-psx-libretro#159]
I've downloaded this core and compiled using libretro-super, a dylib was generated. I signed this file and put inside modules folder on ios project. I've put the bios files inside retroarch system folder and games inside downloads folder. After loading the core, which loads ok, I select the game and it starts. I can hear the sound but I get a black screen ? Is this core fully compatible to ios 10 non-jailbroken devices ? The same thing happens using another mednafen core, for example, game boy advance core. The screen remains black :/

**Comment by BrilliantOne** [comment]
The same happens to me. I can hear the PSX boot up sound, but nothing shows up on the screen. The only thing I can see is the PSX overlay. I can press buttons and here the game start up. It seems that is loads the game properly but does not display anything on the screen. The output in the console in Xcode does not show any errors. Completely stumped on this one.

**Comment by twinaphex** [comment]
Don't use this on iOS. It's not ready for it at all.

**Comment by yoshisuga** [comment]
Bumping this up - this core seems to be the only hope of getting PSX emulation to work on RetroArch for iOS 11, which only runs 64-bit applications.

I built the dylib core using the arm64 architecture and get the same result - black screen with sound.

Is there anyway to use software rendering? I'm guessing it's because opengl isn't working on iOS?

**Comment by yoshisuga** [comment]
Did some testing today and with some help, found out that the issue most likely isn't the core but rather RetroArch not being able to display the XRGB8888 pixel format.

If you take a screenshot (w/ gpu screenshot disabled), you'll see the image.

https://github.com/libretro/RetroArch/issues/5181

**Comment by twinaphex** [comment]
I think we fixed this issue now, so closing.
