### ISSUE TITLE
core option for lower accurancy and better performace

### ISSUE THREAD

**Issue by eadmaster** [libretro/beetle-psx-libretro#16]
Since this is one of the most CPU-intensive cores in RetroArch i am looking for a way to speed it up a bit so it could run fullspeed on low-powered PCs (Intel Celerons, Atoms, etc.) and even some Android devices.
The better solution would be a core option to reduce accuracy a bit like the [bsnes-mercuty option 'bsnes_violate_accuracy'](http://wiki.libretro.com/index.php?title=Bsnes-mercury#Options).

**Comment by Papermanzero** [comment]
A better approach would be to use the GPU for certain tasks.

**Comment by rz5** [comment]
@eadmaster A way to get a significant speed up on this core is to use a MIPS R3000 to ARM/x86 dynamic recompiler, which we don't have yet. I know @Daeken has a project which will facilitate developing one, but he's been absent.

**Comment by eadmaster** [comment]
I've recently switched to x64 builds that provides fullspeed on my CPU with most games.
Now there is also the frame duping option that provides a small speedup, so i am closing this issue.
