### ISSUE TITLE
Current build broken?

### ISSUE THREAD

**Issue by axfelix** [libretro/beetle-psx-libretro#160]
Crashes whenever trying to open the retroarch menu during emulation

**Comment by retro-wertz** [comment]
does not seem so. i often build everytime there is new commit. you should give more details of the problem and how to recreate it, this it github anyways-for tracking bugs/issues. not forums.

**Comment by axfelix** [comment]
Pressing L3+R3 during emulation with the most recent build of this core from buildbot loaded -- afaik the only supported way to access core-specific settings -- currently crashes retroarch. This behavior does not occur with other cores. Is there anything in my environment that could cause this?

**Comment by axfelix** [comment]
I should note that I did not have this issue before updating the core this week. My last build was probably ~2 months old.

**Comment by retro-wertz** [comment]
i did quick test, but im using xbox 360 wired controller. i configure quick menu to be L3+R3. i can go in and out of quick menu without crashing. you probably need to update retroarch too with latest nightlies.

**Comment by axfelix** [comment]
Yup, updating to 1.4.1 worked, thanks! I guess new builds of cores don't always track with the current stable release of Retroarch...

One problem I'm having now is that framebuffer stuff (FMVs, etc.) seem to have the right 1/5 of the screen cropped out. Any idea what might be causing that? I can close this issue either way.

**Comment by axfelix** [comment]
Nevermind, already tracked in https://github.com/libretro/beetle-psx-libretro/issues/136

closing this :)
