### ISSUE TITLE
gcc build error in some Linux systems.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/beetle-psx-libretro#166]
libretro-common/rthreads/rthreads.o: In function `scond_wait_timeout':
/builddir/build/BUILD/libretro-20170303/libretro-mednafen_pcfx/libretro-common/rthreads/rthreads.c:457: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
gmake: *** [mednafen_pcfx_libretro.so] Error 1

**Comment by bparker06** [comment]
This is the wrong repo, you are looking for https://github.com/libretro/beetle-pcfx-libretro. Also when you post there, can you please elaborate on your system setup? Specifically what distro of Linux, what gcc version etc.

A complete build log may be helpful as well.
