### ISSUE TITLE
PSX-HW Vulkan compatibility?

### ISSUE THREAD

**Issue by razorache** [libretro/beetle-psx-libretro#167]
My (gtx 550) card only has partial vulkan support and crashes on start up when I try the vulkan driver. Is there a compatibility list or a known range of geforce cards that are known to work well with it?

**Comment by DukeJP** [comment]
You have the last drivers? My card is a gt 640 and i fix that startup crashes with the lastest drivers.

https://developer.nvidia.com/vulkan-driver

This is the list of supported cards. The full support started in the 600 series.

**Comment by razorache** [comment]
Thanks! My main gtx 760 works great but my 550 crashes on startup too.

**Comment by Margen67** [comment]
You also need to set the video driver to Vulkan in Retroarch's options.
