### ISSUE TITLE
PAL games don't run

### ISSUE THREAD

**Issue by chrism69** [libretro/beetle-psx-libretro#183]
I've tested a couple of games in both the software and HW cores with various renderers and I just get a black screen, no audio at all unlike some of the other issues I've read here.

Japanese and US games run fine, and just to be sure I tried the EU version of Spyro as in #67 but no luck.

**Comment by fr500** [comment]
You need to have all three BIOS images

**Comment by chrism69** [comment]
I do, they're all reported in the core information.

**Comment by DukeJP** [comment]
I just test Koudelka (spanish PAL) and works ok. Maybe is only Spyro pal game has this problem?

**Comment by chrism69** [comment]
Hmm I just tested that one and still nothing, which versions do you use? I have Retroarch 1.5.0 and the Beetle software core 0.9.39.2.

**Comment by DukeJP** [comment]
I have hardware core 0.9.39.2  55ea4ee

**Comment by chrism69** [comment]
I have 9c3a844 so that could be it. Can you upload your core .dll somewhere so I can test it?

**Comment by DukeJP** [comment]
Use the built in core downloader.

**Comment by chrism69** [comment]
Well obviously that won't work as I'll just get the latest version, which I already have.

**Comment by DukeJP** [comment]
Yes, you are right. I has a old version, but i updated to your version and Koudelka still works ok. 
I notice psx has a new core (pcsx Rearmed), you can try that. Or delete your ini and configure all again.

**Comment by DukeJP** [comment]
Well, gime some time to test Spyro pal game.

**Comment by DukeJP** [comment]
Tested and works ok.

![spyro the dragon europe en fr de es it -170411-131544](https://cloud.githubusercontent.com/assets/24689994/24919259/794c124e-1eb9-11e7-98a9-3ef21a7ed0d1.png)
![spyro the dragon europe en fr de es it -170411-131619](https://cloud.githubusercontent.com/assets/24689994/24919267/83be0bba-1eb9-11e7-914c-fb9fcc2203ab.png)
![spyro the dragon europe en fr de es it -170411-131755](https://cloud.githubusercontent.com/assets/24689994/24919289/95193d9e-1eb9-11e7-87fd-c0f7719df405.png)

**Comment by chrism69** [comment]
Ok turns out it was a BIOS issue, the MD5 was correct in core options but I tried a different file and that works totally fine.
