### ISSUE TITLE
Shared Memory Card Issue

### ISSUE THREAD

**Issue by omega64** [libretro/beetle-psx-libretro#189]
shared_memory_cards option won't work if use_mednafen_memcard0_method = libretro (like how is specified in readme.md)

with use_mednafen_memcard0_method set to libretro it won't make the correct files in saves folder, instead it save regular .mcr and .srm files with rom's name.

if use_mednafen_memcard0_method is set to mednafen it works, and create in saves folder:
mednafen_psx_libretro_shared.0.mcr
mednafen_psx_libretro_shared.1.mcr

**Comment by fr500** [comment]
well, when it's in libretro mode the core has no control whatsoever of the save name

**Comment by omega64** [comment]
so readme.md is incorrect?

**Comment by fr500** [comment]
Yeah seems the description for that option is wrong
