### ISSUE TITLE
Unable to access various Beetle HW options.

### ISSUE THREAD

**Issue by SpaceMonkey-92** [libretro/beetle-psx-libretro#192]
By going into Quick Menu > Options after loading up Mednafen's Beetle HW core, I seem to be unable to access some options I think I should have available to me.

For comparison, here is a picture of the options shown for another user:

http://i.imgur.com/jjWnHSz.png

And here is my own

http://imgur.com/Soba5L2

I know that screenshot shows me with the software core loaded, but I have the exact same options shown when running the hardware core as well. I am trying to do this with my visual driver set to OGL and I have made certain advanced options are enabled.

Any ideas?

**Comment by Kalcode** [comment]
In the picture 

> And here is my own
> http://imgur.com/Soba5L2

In the bottom left it says "Beetle PSX"  the HW version says "Beetle PSX HW", it seems you simply loaded the wrong core. For those options you need to download the HW core.

**Comment by rz5** [comment]
@SpaceMonkey-92 I assume you did as @Kalcode said and you loaded your content with the wrong type of core.

Try deleting the regular Beetle PSX core and just stay with the Beetle PSX HW core, see if your problem still happens. I'll close this issue for now.
