### ISSUE TITLE
[Feature Request] individual internal width and height resolution adjustment

### ISSUE THREAD

**Issue by whatwwkd4496** [libretro/beetle-psx-libretro#193]
for games with mixed 2D/3D, increasing only internal width resolution will preserve 2D elements clarity and smoothened 3D elements when using scanlines.
examples:
1x width <img src="http://i.imgur.com/jTtQidT.png">
6x width <img src="http://i.imgur.com/qe1N4C3.png">

**Comment by rz5** [comment]
@whatwwkd4496 - Hi, try out this core again. The software and GL renderers have both changed so that even when you change internal resolution, the "output" (for lack of better words) is basically the same as native resolution, so your scanlines will be as sharp.

**Comment by whatwwkd4496** [comment]
I'm using the nightly version 2017-09-09-x64 and using interlacing shader from misc folder with 480i interlacing option off and  4x resolution in beetle-psx-hw core with and without JINC2 texture filtering

without filtering
[](https://i.imgur.com/I0GdJH3.png)

with filtering
[](https://i.imgur.com/RexEPKk.png)

the results are visibly blurrier and jaggier than just increasing width, it's less than ideal but i'll take it for now, but please add separate height and width adjustment in the future.

**Comment by whatwwkd4496** [comment]
my results using nightly version 2017-09-09-x64 :
no filtering https://i.imgur.com/KuyQIE7.png
xbr filtering https://i.imgur.com/ju4SnfB.png
jinc2 filtering https://i.imgur.com/utfDn1H.png
