### ISSUE TITLE
Support for wayland?

### ISSUE THREAD

**Issue by maxlefou** [libretro/beetle-psx-libretro#194]
While the core works fine on Xorg/X11, trying it on wayland just leads to a black screen and this error in logs:
`RetroArch [ERROR] :: Failed to connect to Wayland server.`

Did i do something wrong or wayland isn't supported yet?

**Comment by hizzlekizzle** [comment]
RetroArch should work quite well with wayland AFAIK. Do other cores work?

**Comment by twinaphex** [comment]
Beetle PSX works for me on Wayland with both the Vulkan renderer as well as the GL renderer.
