### ISSUE TITLE
texture filtering don't work

### ISSUE THREAD

**Issue by whatwwkd4496** [libretro/beetle-psx-libretro#195]
I have two pcs with different gpus one is AMD legacy HD 6770 with no Vulkan support running on OpenGL, texture filtering works with it but only by manually editing the retroarch core options config file. and the other one is AMD 7750 with Vulkan support running retroarch on Vulkan driver and core renderer set to Vulkan but texture filtering don't work. I've tried to switch to OpenGL instead. Both in driver and core renderer it give me black screen.

**Comment by hizzlekizzle** [comment]
Right, texture filtering only works with OpenGL currently.
