### ISSUE TITLE
Beetle Hw Disable texture filtering

### ISSUE THREAD

**Issue by wingedonezero** [libretro/beetle-psx-libretro#197]
Hello can you include a option to disable texture filtering under options. There are multiple filters but no option to disable if i want to use a shader instead. The options are nice if you dont want to use a shader but i think it affects some shaders ive tryed and the option to disable seems like one that should be included.

**Comment by hizzlekizzle** [comment]
Nearest is what would be the equivalent of none/disabled

**Comment by wingedonezero** [comment]
Ok thank you or clarifying that i figured it was just another texture filter.
