### ISSUE TITLE
[Vulkan] [Feature Request] Texture Filtering for Vulkan Renderer

### ISSUE THREAD

**Issue by whatwwkd4496** [libretro/beetle-psx-libretro#198]

**Comment by shinra358** [comment]
+1

**Comment by Phiben** [comment]
Any updates on this?

**Comment by rz5** [comment]
Nothing being worked on as far as I know. It's not immediately obvious to someone fluent in OpenGL where the first point attack should be to start implementing per-terxure filtering

**Comment by hizzlekizzle** [comment]
I have some ideas on where to hook in but without a Vulkan-capable laptop, I don't really have any convenient way to work on it.

**Comment by Papermanzero** [comment]
Can someone try to implement the feature.
Opengl is completely buggy. Crashes, glitches, etc.
Vulkan is working has however not all features.

**Comment by simias** [comment]
I believe the code you want to modify is: https://github.com/libretro/beetle-psx-libretro/blob/1a9ad36e4fac85c0f4d986e2b4c02afda53c1b73/parallel-psx/glsl/vram.h#L10-L36

Actually there already seems to be a bilinear filter implementation but I don't know if it works because it's commented out in primitive.frag: https://github.com/libretro/beetle-psx-libretro/blob/1a9ad36e4fac85c0f4d986e2b4c02afda53c1b73/parallel-psx/glsl/primitive.frag#L32-L33

Maybe it'd be worth re-enabling that code to see if it worked, and then continue from there.

**Comment by simias** [comment]
Actually you'll want to keep sample_vram_atlas the way it is and add an other function for the filtering (exactly the way this commented bilinear code works) because otherwise it'll mess up transparent pixels that you don't want to filter. See primitive.frag.

**Comment by hizzlekizzle** [comment]
Agreed. That's where I was planning to hook in. The other complication of working with this code is that you have to use glslc to convert everything to SPIR-V each time you change anything, which is a hassle...

**Comment by simias** [comment]
@hizzlekizzle what's stopping you exactly? I thought Vulkan was pretty widespread nowadays. Don't even crappy integrated GPU support it?

**Comment by hizzlekizzle** [comment]
My laptop where I do my development is Sandy Bridge :(

**Comment by hizzlekizzle** [comment]
closed by https://github.com/libretro/beetle-psx-libretro/pull/404 and https://github.com/libretro/beetle-psx-libretro/pull/409

**Comment by saftle** [comment]
You guys are amazing. Thank you! @hizzlekizzle @iCatButler How should the bounty be dispersed?

**Comment by iCatButler** [comment]
@saftle I didn't really contribute anything to this, so any bounty should go to @hizzlekizzle.

**Comment by twinaphex** [comment]
I will give @hunterk another $25 as part of his troubles outside of Bountysource, making it a nice rounded $50 at least.

**Comment by saftle** [comment]
@twinaphex Could you also move the bounty from https://github.com/libretro/beetle-psx-libretro/issues/313 to this issue as well? It appears it's an anti aliasing shader incompatibility, rather than a bug. Thanks

**Comment by twinaphex** [comment]
This one?

https://www.bountysource.com/issues/55804488-vulkan-8x-rendering-produces-garbled-graphics-on-all-games-1-4x-works-great-30-bounty

So what do you want me to do there? Ask @hunterk to send a solution claim for that bounty? Or what are we going to do there? I don't think we can reallocate bounty money from one issue to another.

**Comment by saftle** [comment]
Yeah that would be the one. Yeah either/or. I didn't want to close the issue, since it is definitely a problem with the shader somehow, but wanted to move the bounty. I can contact bountysource directly in order to move it. I'll do that as soon I get off of work.

**Comment by hizzlekizzle** [comment]
I can take a look at the shader, as well, and see if it's just a rounding error somewhere.

**Comment by saftle** [comment]
Oh ok awesome. Then I'll just leave it there. @twinaphex then we are good to go with this one.
