### ISSUE TITLE
Visual c++ "runtime terminated in an unusual way"

### ISSUE THREAD

**Issue by plusfuture** [libretro/beetle-psx-libretro#20]
I am specifically using the 1.3.0 build with the Mednafen PSX core downloaded via the RetroArch GUI. I have placed three requisite bios files for Mednafen (MD5 checksum confirmed) in the `bios` subfolder in the RetroArch directory.

The crash happens immediately upon attempting to run a `.cue` file in the same directory as the `.bin`. I have confirmed that there is no directory listed in the `.cue` file; instead, it is simply the filename of the `.bin` file.

What can explain this error?

**Comment by sardiax** [comment]
I think I had this same issue. 
It was looking for the PSX bios inside the folder the cue was loading from.
In retroarch.cfg - my system folder was set to 'default', when I set system_directory path manually it solved this issue.

e.g.
system_directory = "c:\retroarch\system"

Running Retroarch 1.3.0 on Windows 10 Pro 64-bit.

**Comment by D-to-the-K** [comment]
I get this crash whenever I try to load a .cue whose .bin was renamed and no longer reflects the FILE tagged  in the .cue. It would be good if, like all other PSX emulators, the Mednafen PSX core tried to look for a .bin with the same name as the .cue when the one in the FILE tag isn't found.

**Comment by rz5** [comment]
@plusfuture - Are you still getting that crash?
