### ISSUE TITLE
[Feature Request] Force offscreen drawing (HW Version)

### ISSUE THREAD

**Issue by DjBlades** [libretro/beetle-psx-libretro#200]
Apologies if this isn't the right place for HW suggestions but I couldn't find a dedicated page for it. 

The widescreen hack is a nice feature, but for some games geometry that would not normally be onscreen is not drawn. The Crash Bandicoot series is the best example, as all levels exhibit the problem: http://i.imgur.com/ily4fWF.jpg

ePSXe has the feature but it's seperate from the Widescreen Hack, so it may be using an entirely different method than a normal Widescreen hack. http://i.imgur.com/TbtVt4C.png

**Comment by rz5** [comment]
@DjBlades And does ePSXe make it so e.g. Crash Bandicoot is both widescreen (show more stuff) AND the missing polygons aren't missing anymore?

https://en.wikipedia.org/wiki/Hidden_surface_determination#Viewing_frustum_culling

I'm not sure if this can be intercepted and undone on the rendering section of the emulator.

**Comment by DjBlades** [comment]
Ah sorry, I considered taking an ePSXe screenshot but it was uninstalled. I've got video examples now
Beetle HW with Widescreen hack: https://puu.sh/wpdyk/82914b6784.mp4
ePSXe with Offscreen Drawing enabled in video settings: https://puu.sh/wpdI2/9fe7de9d6c.mp4

It's also worth noting that I haven't got the widescreen hack enabled in ePSXe either, this is all in the video plugin's settings.

**Comment by rz5** [comment]
Thanks for the videos. Ideally you'd share a clip with ePSXe and the said widescreen hack enabled, plus the offscreen drawing to confirm if it's possible or not.

ePSXe:
![](https://snag.gy/q9m7O3.jpg)

Beetle:
![](https://i.snag.gy/HrYM9o.jpg)


Taking a quick glance at these two shots, ePSXe is only stretching the picture from 4:3 to 16:9, no extra geometry is actually shown, unlike the Beetle PSX core, which is widening the field of view and is stretching the picture to 16:9.

**Comment by DjBlades** [comment]
I can't believe I never noticed that...
When I disabled what I thought was this "Force offscreen rendering" option, it was identical. You're completely correct, it's just stretching the existing objects. I guess there's nothing on the sides to draw in the first place, hence why widescreen hacks don't show anything there.
Sorry for not looking properly at my own comparisons :P
