### ISSUE TITLE
[GL] Rendering issues in latest versions

### ISSUE THREAD

**Issue by shiba89** [libretro/beetle-psx-libretro#202]
Hi, I noticed some issue with Crash Bandicoot and Crash Bandicoot 3. I'm using [this](https://github.com/gentoo-mirror/abendbrot/tree/master/games-emulation/beetle-psx-libretro) overlay for Gentoo so I'll take the two versions available there as reference:

(20170507) Crash Bandicoot - Temple Ruins, Road To Nowhere, ecc.
![crash bandicoot europe edc -170711-181310](https://user-images.githubusercontent.com/3816409/28078647-dfdb9446-6665-11e7-859e-2f93dc58e8a0.png)
(20170612) Crash Bandicoot - Temple Ruins, Road To Nowhere, ecc. (Upper half of the screen)
![crash bandicoot europe edc -170711-180500](https://user-images.githubusercontent.com/3816409/28078636-d87005ca-6665-11e7-9027-f669faef247f.png)
(20170507) Crash Bandicoot 3
![crash bandicoot 3-170711-181327](https://user-images.githubusercontent.com/3816409/28078731-1b7370c8-6666-11e7-8ea8-06b3cd55ab9f.png)
(20170612) Crash Bandicoot 3 (Crash shadow)
![crash bandicoot 3-170711-180620](https://user-images.githubusercontent.com/3816409/28078739-1f99bfcc-6666-11e7-959c-ff402390423c.png)

Same configuration for both versions, but even changing everything possible (except switching to software rendering) doesn't solve the problem.

**Comment by orbea** [comment]
Can you git bisect the issue?

**Comment by shiba89** [comment]
Sure, I will try to do this next week though.

**Comment by RaydenX93** [comment]
i've got the same issue

**Comment by shiba89** [comment]
Sorry for the delay. Bisecting pointed out the problem started with commit db854a95b9dc79e0ccd6d24bfe94a8fbb3f5bd74. In master, removing the `doCleanFrame` condition at this line https://github.com/libretro/beetle-psx-libretro/blob/c647d03003ad3a04072bf558234ea8f664748ccd/rsx/rsx_lib_gl.cpp#L2622 seems to fix the issue for both Crash games for me.

I haven't studied libretro or beetle-psx code so I can't explain the reason behind this, I just see it works.

**Comment by twinaphex** [comment]
OK, I just mindlessly copied pasted this over from Citra so I think we should probably just go ahead and remove this altogether.

**Comment by shiba89** [comment]
Thank you very much!

**Comment by rz5** [comment]
@shiba89, if it's fixed on your system, go ahead and close the issue.
