### ISSUE TITLE
Unloading games leaves core unusable

### ISSUE THREAD

**Issue by albertofustinoni** [libretro/beetle-psx-libretro#203]
Looking in libretro.cpp I see
```
extern MDFNGI EmulatedPSX;
MDFNGI *MDFNGameInfo = &EmulatedPSX;
```

on top (line 156) outside of any function.

Then `retro_unload_game` has this line (3390)
```
MDFNGameInfo = NULL;
```

And finally `MDFNI_LoadCD`, called by `retro_load_game` does (line 3080)
```
memcpy(MDFNGameInfo->MD5, LayoutMD5, 16);
```

Which on loading a game for any time after the first is going to fail because of attempting to dereference a null pointer.

is there any reason why `MDFNGI *MDFNGameInfo = &EmulatedPSX;` can't be moved to `retro_load_game`?

**Comment by twinaphex** [comment]
I don't think there was an intent to do this, so you likely catched a very serious bug. Thanks for that.
