### ISSUE TITLE
[GL] mdec issues

### ISSUE THREAD

**Issue by retro-wertz** [libretro/beetle-psx-libretro#207]
mdec rendering issues when using OpenGL mode:

Tales of Phantasia:
![screenshot_2017-07-28_17-48-35](https://user-images.githubusercontent.com/23315382/28713214-caf131ae-73c0-11e7-8bcb-f46cf4bbfe8d.png)

software/vulkan runs fine.

1st BAD commit https://github.com/libretro/beetle-psx-libretro/commit/028a2c286e99f9536dee8571d55fc4082a2c4398

**Comment by orbea** [comment]
I am getting this too. It doesn't matter what game it seems. I have experienced it with Tekken 3, Parasite Eve and Lunar Silver Star Story.

**Comment by simias** [comment]
My guess would be that something broke 24bit mode.

If you want to confirm that you can try to boot up Spyro (the first one). The "Universal" logo is not decoded by the MDEC but is displayed in 24bpp. If it's displayed correctly then I'm wrong, if it's not then you can safely assume the MDEC doesn't have anything to do with it.

**Comment by orbea** [comment]
Spyro the Dragon
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/beetle-psx/2017-07-28-073418_1680x1050_scrot.png)

**Comment by rz5** [comment]
On that first bad commit, it might be this line:
https://github.com/libretro/beetle-psx-libretro/commit/028a2c286e99f9536dee8571d55fc4082a2c4398#diff-1cb9bd53ab051e7866bbed72a17356a0R2267

The string literal should be "depth_24bpp" instead of just "depth".
I'll see if I can replicate this issue and try this fix.

**Comment by rz5** [comment]
I can't replicate it, the opening cutscene in Tekken 3 looks fine to me:
https://i.snag.gy/zZWwti.jpg

**Comment by rz5** [comment]
Strangely enough, on a couple of Nvidia-based systems, the mdecs still play fine. But Twinaphex confirmed that on the first bad commit found by @retro-wertz, when we're poking the 'depth' uniform with the state of a 'depth_24pp'...we're poking the wrong uniform, basically.

I'll force a commit to correct it, hopefully it'll be fixed for you guys.

**Comment by orbea** [comment]
Its fixed here, thanks!

**Comment by simias** [comment]
Good catch.

**Comment by rz5** [comment]
@retro-wertz - Please test it again and feel free to close the issue if you want.

**Comment by retro-wertz** [comment]
this is fixed now. thanks. 
https://github.com/libretro/beetle-psx-libretro/commit/947ab86cf470e66a5a6b6ae0508da060d96dc079
