### ISSUE TITLE
[GL] internal GPU resolution  does not scale with display

### ISSUE THREAD

**Issue by retro-wertz** [libretro/beetle-psx-libretro#208]
there is scaling issues here when using OpenGL drivers. not specifc probably to Internal GPU resolution setting as setting this even to 1x will fill entire screen without proper ratio. this happens whenever there is a change in resolution whether its internal switching(like from sony logo -> psx logo, to intro mdec of game to titlescreen) or manual changing through Internal GPU resolution or texture filtering. Toggling the "Adaptive Smoothing" restores the correct ratio until next resolution switching occurs.

The quickest way for test is during the bios Sony logo -> Playstation transition. 
-Set Internal GPU resolution to 2x or 4x(i can only test upto 4x) then Reset core.
-Sony Logo should fill screen here(not in ratio) fix this by toggling Adaptive smoothing for now.
-when screen transitions to the Playstation logo this would again fill display instead of being scaled of in display ratio.

another test is just to play with Internal GPU resolution or texture filtering.

Sample running fullscreen 1600x900
![tales of phantasia japan -170729-032752](https://user-images.githubusercontent.com/23315382/28734094-d7f1b9f4-7411-11e7-9365-85989666d0fa.png)
![tales of phantasia japan -170729-032815](https://user-images.githubusercontent.com/23315382/28734095-d8059be0-7411-11e7-9605-d67e979f9212.png)
![tales of phantasia japan -170729-032833](https://user-images.githubusercontent.com/23315382/28734096-d80a6bf2-7411-11e7-9f5f-dda37ccda395.png)

**Comment by rz5** [comment]
Can confirm. For the life of me, I can't figure out where this stems from. Whenever we call the environment callback to set geometry, I ensured the same values are used as on the mednafen software renderer.

Maybe it's because fb_texture is always at 1x...hopefully @simias knows more or @twinaphex can chime in about how libretro handles integer scaling and stretch to fit.

**Comment by retro-wertz** [comment]
Looks like the correct way to maintain aspect-ratio on higher than 1x Internal GPU resolution on OpenGL is playing with Integer Scale = OFF, but the display will scale with Internal GPU resolution. you can resize window while in-game though(if running window-mode), but the menu fonts will be large. not sure if im making sense, so this screenshot should probably explain it(hopefully):

![tales](https://user-images.githubusercontent.com/23315382/28873616-ffc6d362-77c0-11e7-8b03-81b54208fba7.jpg)

with Integer Scale=ON, resizing the window will resize game resolution too, so a wide window will have a wide-screen game, a thin width will squeeze the game for example, the menu fonts are still big though....

**Comment by retro-wertz** [comment]
https://github.com/libretro/beetle-psx-libretro/commit/f11e727258400a7d215afacbc888d0ab5baf83bb

this commit looks better now. interger scaling does not stretch to full display anymore.
