### ISSUE TITLE
Dual Shock Controls Don't Work

### ISSUE THREAD

**Issue by KristopherTadlock** [libretro/beetle-psx-libretro#213]
I downloaded the newest version of Retroarch today using the portable version. Extracted the archive to a folder. Downloaded the Beetle PSX core using the online updater and then moved my bios files into the system folder. All retroarch and beetle PSX setting were left at stock/default settings.

When starting a game, in the controls section, every controller is set to a dualshock controller. None of the inputs register in game when this set. The only device setting that appears to work is the PS1 joypad option, which of course does not have support for analog or rumble.  

If I set each controller to a ps1 joypad, and select to save a core remap file, the game will automatically load with dualshock controllers again. There doesn't appear to be a way to save the ps1 joypad selection in the menus. 

The controller used for testing was an XBOX One joypad connected via USB. Retroarch registers it as Xbox One #1. The configuration file loads automatically, and the controller works in the retroarch menus. 
The game I used for the test was crash bandicoot. 

By default, retroarch uses the dinput input driver, and the xinput joypad driver. 

The same bug is also present in the Beetle PSX hardware version . 

Windows 10 64 Bit (with anniversary update applied)
Intel i7 7700K
Nvidia GTX 1080 
24 GB Memory DDR4

**Comment by fr500** [comment]
It's not the core but RA
https://github.com/libretro/RetroArch/issues/5257
