### ISSUE TITLE
Option for all 2D Elements to remain in 1x Resolution When Increasing Internal Rez

### ISSUE THREAD

**Issue by shinra358** [libretro/beetle-psx-libretro#222]
Would like the option for all 2D elements in psx games to remain in their native 1x rez when increasing the internal resolution for 3D elements. This way, the majority of the scaling like shaders can continue to work correctly and performance can be improved when increasing the internal resolution. I believe the n64 core has something like this as an option.

**Comment by rz5** [comment]
There's something like that in the Vulkan renderer, albeit the with a different design goal (looks vs performance). The associated core option is called 'Adaptive smoothing'.

Read more about it in https://www.libretro.com/index.php/introducing-vulkan-psx-renderer-for-beetlemednafen-psx/

The section is called "Feature - Adaptive smoothing" under "Implementation details". He did a very interesting write-up on it, gets into some nitty-gritty stuff if you're into that kind of stuff.

Remember to close the issue.
