### ISSUE TITLE
problem w/ bin not being extracted

### ISSUE THREAD

**Issue by klepp0906** [libretro/beetle-psx-libretro#223]
So i use retroarch to emulate everything that it can emulate.  Im running into an issue with the mednafen psx cores (I think the fault lay with them?)

Due to space I run everything zipped.  I have a temp directory chosen and it works without fail (until now).

For example with sega cd games which are in the same bin/cue format as my zipped psx games, I can check the temp directory and see that it is  extracting the bin and the cue.

With Mednafen - for some reason only the cue is being extracted.  Running hte debug console leaves me with an error saying "no such file title.bin" because well, there isnt.

No issues so far, until mednafen.

Not pointing fingers, i have the utmost respect, appreciation, and frankly awe - at what you guys can do.  I just dont know if the issue is with retroarch, with the core, or if its not a bug at all and simply things not implemented yet. 

For all i know its something fixable on my end.

**Comment by ofry** [comment]
It's NOT core bug, but Retroarch bug...

Issue queue for RA bugs:
https://github.com/libretro/RetroArch/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20sort%3Aupdated-desc

2nd. This feature request already described here.

https://github.com/libretro/RetroArch/issues/4331

**Comment by klepp0906** [comment]
Ah, thank you for the reply!  Apologize for the irrelevant post then. 

I'm new to RA and largely loving it.

Do I need to repost this or comment in either of those?

**Comment by rz5** [comment]
Since it affects the frontend and not the core, you should close the issue here and reopen it on the RA bug tracker
