### ISSUE TITLE
Not loading on linux x86-64(Black screen on game load)

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/beetle-psx-libretro#230]
When loading it just loads to a black screen and sits.

Beetle PSX hw crashes on load due to lack of vulkan support so I could not test it.

This core works on my android phones but is too slow to use(5-10fps) so the core is not completely broken.

The directory the files are in has 0x0777 permissions so RetroArch can read all the files fine. 

Device: Dell Latitude E6410
OS: Ubuntu 16.04 lts
Version: Retroarch 1.6.7
Core Version: Beetle PSX 0.9.44.1 d1ef37
Drivers: (Video)gl, (Audio)pulse

**Comment by hizzlekizzle** [comment]
Seems okay here. I'm on Ubuntu 16.04, as well.

Are you using packages from the PPA or cores from the core updater?

**Comment by meepingsnesroms** [comment]
RetroArch binary from flatpak and cores from the core updater.

**Comment by rz5** [comment]
@meepingsnesroms - Do you have the required firmware inside whatever your 'system' directory is?

**Comment by retro-wertz** [comment]
works fine here, gl and vulkan mint-sonya.. must be filename case of bios?

**Comment by meepingsnesroms** [comment]
Yep, I was using all uppercase SCPH550*.BIN instead of scph550*.bin
