### ISSUE TITLE
Fifa 98 (Road to World Cup) crash

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/beetle-psx-libretro#235]
Game goes to menus and you can alter options but it freezes and crashes RetroArch before the match starts.

**Comment by DukeJP** [comment]
Please give more information about your game, your emulator version and options,  and your system.
The game works ok for me in the Beetle PSX software core, NTSC version.

First loading screen
![fifa - road to world cup 98 usa en fr de es nl sv -170921-145754](https://user-images.githubusercontent.com/24689994/30711175-4daa8b3e-9ede-11e7-91f3-34164310c41d.png)


Options menu:
![fifa - road to world cup 98 usa en fr de es nl sv -170921-145903](https://user-images.githubusercontent.com/24689994/30711212-71b487f0-9ede-11e7-8649-3374b134ee7e.png)

Memory Card works ok here.
![fifa - road to world cup 98 usa en fr de es nl sv -170921-145939](https://user-images.githubusercontent.com/24689994/30711251-9857162a-9ede-11e7-9ec7-21a5e2f7c3eb.png)

Select a team in league mode:
![fifa - road to world cup 98 usa en fr de es nl sv -170921-150036](https://user-images.githubusercontent.com/24689994/30711349-d5792408-9ede-11e7-8acd-829ab439d012.png)

Loading screen:
![fifa - road to world cup 98 usa en fr de es nl sv -170921-150123](https://user-images.githubusercontent.com/24689994/30711361-dee4eb62-9ede-11e7-80ca-2cbf36e290bf.png)

DA Game:
![fifa - road to world cup 98 usa en fr de es nl sv -170921-150208](https://user-images.githubusercontent.com/24689994/30711366-e63fe358-9ede-11e7-9803-1f3993d43a72.png)

**Comment by Tasosgemah** [comment]
Had this issue yesterday twice. Then i gave up the game because i thought it's problematic. But now it also works for me... can't reproduce the issue. Maybe it was a combination of teams or a specific stadium. Or maybe it was my system for some reason. I have to test the game further to see if i can make it crash again.

I also use US NTSC version of the game and the latest Beetle PSX core on a i54670 + 1060 card.

**Comment by rz5** [comment]
@Tasosgemah - If you can find a way to reproduce it, do update this thread. For the moment, consider closing it.
