### ISSUE TITLE
[Suggestion/Request] Show log info if bios is found and/or not and safer exit when bios is not found.

### ISSUE THREAD

**Issue by retro-wertz** [libretro/beetle-psx-libretro#239]
I believe the method to check is calling BIOSFile.size() here:
https://github.com/libretro/beetle-psx-libretro/blob/master/libretro.cpp#L1485
to check if a bios was loaded or not. But I leave it to the experts how the checking should be.

also probably show the bios name used as not everyone is accustomed to psx bioses(i always though EU was using scph5501)

While we are on the subject, i think if bios is not found, psx show safely prompt message and safely exit core. Missing bios just confuses users since psx will still load but stuck at black screen.

This should also be a nice info when troubleshooting. Thanks.

**Comment by rz5** [comment]
I was planning on reworking how beetle-psx would detect the presence of a required BIOS file but never got back to it.

Currently, it seems beetle-psx is taking whatever the 'system' directory is, combining it with the name of whichever BIOS file is currently needed and trying to open the resulting path as a file, which may or may not exist (if it doesn't, it exits).

My proposal would involved a dependency on retro_dirent, to allow traversing through the filenames of some directory, fetching the names of these elements and comparing them (ignoring case) to the currently required firmware.
This would allow upper and mixed-case names for BIOS files. It would also print an error message in case no file with the required file's name was found.

The code would go something like this:

```
   const char *bios_name;

   if(region == REGION_JP)
      bios_name = "scph5500.bin";
   else if(region == REGION_EU)
      bios_name = "scph5502.bin";
   else if(region == REGION_NA)
      bios_name = "scph5501.bin";
   else
      abort();

   {
      /* Open the directory where BIOS files are stored */
      RDIR *system_directory = retro_open_dir(retro_base_directory);

      char *entry_name = NULL;
      size_t bios_name_size = strlen(bios_name);
      char bios_path[4096];
      bios_path[0] = '\0';
      bool found = false;

      /* Traverse the directory, comparing the files names to bios_name, ignoring letter case */
      do
      {
         entry_name = retro_dirent_get_name(system_directory);
         if (casecmp(bios_name, entry_name, bios_name_size))
         {
            /* If a directory entry matches bios_name, save the bios_path and break from looping */
            snprintf(bios_path, sizeof(bios_path), "%s%c%s", retro_base_directory, retro_slash, entry_name);
            found = true;
            break;
         }

      } while (retro_readdir(system_directory) != NULL);

      retro_closedir(system_directory);
      
      /* If the right BIOS file was not found, gracefully exit */
      if (!found)
      {
         log_cb(RETRO_LOG_ERROR, "%s was not found, aborting...", bios_name);
         abort();
      }

      FileStream BIOSFile(bios_path, MODE_READ);

      BIOSFile.read(BIOSROM->data8, 512 * 1024);
   }
```

However I am unsure if this is proper core behavior - looping through files/folders. And RetroArch also has a feature under Core called 'Check for Missing Firmware Before Loading' which would stop the core from crashing if it's missing firmware...

**Comment by retro-wertz** [comment]
it doesn't have to be complicated for a starting point, the purpose of the log-request is to be able to help troubleshoot issues faster with others, like if we asked them to post log, most details can be already seen in log instead of asking another question and waiting for the other party to respond. :D

**Comment by rz5** [comment]
Alright @retro-wertz, check if it's to your liking now. I did a couple of commits that add extra logging.
Specifically, after the core can see the details of the game, we query which region the game is from and we check if we have the appropriate BIOS:

If we do have it, the log will say the BIOS was found, print the full path to the BIOS file and the known good SHA1 value.
If it's found but its SHA1 value isn't good, again we say so in the log, printing the expected and obtained SHA1 values.
If it's not found, we print the filename we expected to find.

The core is also a bit more forgiving in terms of the BIOS filenames it accepts. Far from perfect or robust but it prevents the core and RetroArch from hanging in a black screen if you didn't read the manual.

**Comment by retro-wertz** [comment]
some slight adjustment probably is needed if the correct bios is not found...

```
No such file or directory
[libretro ERROR] Firmware has invalid SHA1: 
/home/retro/EMULATORS/retroarch/system/
[libretro ERROR] Expected SHA1: B05DEF971D8EC59F346F2D9AC21FB742E3EB6917
[libretro ERROR] Obtained SHA1: DA39A3EE5E6B4B0D3255BFEF95601890AFD80709
[libretro ERROR] Content cannot be loaded
```
its comparing to something else, and not showing the expected file.

**Comment by ThatInvaderGuy** [comment]
Would it be possible to add an option to throw a warning on an incorrect hash instead of preventing boot? I've been using a bios dumped from my PSP and it's worked fine for the most part. Kind of silly to assume everyone has the exact same Playstation model.

**Comment by rz5** [comment]
@ThatInvaderGuy I'll meet you halfway. I'll change the detection behavior allow your dump to be used. But, like the author said, "you'll likely cause emulation glitches".

**Comment by ThatInvaderGuy** [comment]
@rz5 Thanks! I assume you need the hash?

CRC-32: 5660F34F
MD5: C53CA5908936D412331790F4426C6C33
SHA-1: 96880D1CA92A016FF054BE5159BB06FE03CB4E14
SHA-256: CBE758E1C8ECE593C8E14CE1E8B3436428A01C608032A02613B3A4B442B4D712

The hashes for this specific bios are kind of hard to find.

**Comment by rz5** [comment]
Sorry, forgot to add: I'll allow it but you'll have to rename your file to match something the core expects. It's inconvenient but I'd like to preserve the author's intent about there being only 3 supported BIOS versions.

**Comment by ThatInvaderGuy** [comment]
That's fine. I was actually already doing that anyway.

**Comment by retro-wertz** [comment]
case closed. thanks.
