### ISSUE TITLE
Metal Gear Solid (USA) m3u loading issue

### ISSUE THREAD

**Issue by aionys** [libretro/beetle-psx-libretro#248]
For some reason, Metal Gear Solid freezes whenever the game tries to load when running from an m3u playlist.

With skip BIOS enabled, the game never starts.

With it off, the game gets to the difficulty select screen before it happens.

I tested to see if it was an issue with the disc itself by loading the Disc 1 .cue directly, and there were no issues. I saved the state after the intro cutscene where you get out of the water, loaded up the m3u, and loaded that state, and it played fine, up until the point where you go up the elevator and the second cutscene happens, at which point the problem happens again.

This happens regardless of software, ogl, or vulkan rendering, so I'm pretty sure it's not a graphics related issue. In all cases the behaviour is exactly the same: black screen, no audio, game seems frozen. RetroArch is working fine, can load the menu, save/load state, etc., but the game itself is frozen on that black screen. I left it going all night while I slept and it was still a black screen when I woke up.

Again, this only happens when loading the m3u, not when loading the .cue for Disc 1 directly. Also, it doesn't have this problem with any of the other m3u playlists I've tried thus far. Out of curiosity, I added the MGS VR Missions disc to the m3u and tried to run it. Got the same black screen issue.

"Metal Gear Solid (USA).m3u":
```
Metal Gear Solid (USA) (Disc 1) (v1.1).cue
Metal Gear Solid (USA) (Disc 2) (v1.1).cue
Metal Gear Solid - VR Missions (USA).cue
```

Version info: RetroArch Beetle PSX HW 0.9.44.1 6960ecf

I tried running RetroArch with "retroarch --menu --verbose >> log.txt 2>&1" but the log it gave seems to have no useful information for this issue. The last 4 lines are messages about config loading at launch-time, there's nothing during the actual play.

In case it does have something useful, here's the pastebin for the log: https://pastebin.com/CAG27rfb

Hopefully I've provided enough information. I can also create a save state with it in the black screen and upload it somewhere if that'll help.

**Comment by aionys** [comment]
Also, RetroArch is version 1.6.7 (Git a235c0b)

**Comment by rz5** [comment]
In order:
Tested if MGS1 in CHD format loads if Skip Bios is enabled - works.
Tested if the following file loaded if Skip Bios is enabled: 
    Metal Gear Solid (USA) (Disc 1) (v1.1).m3u
```
Metal Gear Solid (USA) (Disc 1) (v1.1).chd
```

It works too;

Tested the same file, but renamed to 'Metal Gear Solid (USA)' - works too.

@aionys - I can't replicate your bug, if you could write more specific instructions on how to replicate the bug. Specifically watch out if other core options are set to non default values too.
Speed hacks like CD access mode, CD load speed and CPU overclock might all influence things.

**Comment by aionys** [comment]
Everything is set to default, but I'm using .bin/.cue, not .chd

I'll see if converting it to .chd fixes it for me.

**Comment by aionys** [comment]
Yeah, no problem when using .chd

From my testing, this issue apparently ONLY happens when loading an MGS disc (including VR Missions) in .bin/.cue format from an .m3u playlist. Which is horrendously specific.

**Comment by rz5** [comment]
huh. Might be worth checking if this happens in Mednafen standalone as well.

**Comment by aionys** [comment]
Converting the .bin/cue worked for me, which as far as I'm concerned means issue solved, so I'm marking this closed.
