### ISSUE TITLE
Dynamic recompiler [BOUNTY] [$365]

### ISSUE THREAD

**Issue by Autechre64** [libretro/beetle-psx-libretro#249]
Original thread here -

https://www.bountysource.com/issues/48048939-dynamic-recompiler-305-bounty

@simias @webgeek1234 @rtissera @hrydgard @Denu8thell @ajshell1 @wiired24 @rz5  @DuckZ

**Comment by deltabeard** [comment]
The issue is already open [here](https://github.com/libretro/beetle-psx-libretro/issues/214).

**Comment by twinaphex** [comment]
Yes, this issue is no longer necessary now.
