### ISSUE TITLE
analogue L2 and R2 Problem

### ISSUE THREAD

**Issue by FiLeonard** [libretro/beetle-psx-libretro#268]
I do have the following problem. Since i have an Xbox Controller L2 and R2 are mapped analogue as +2 and -2. (analogue button) Now e.g. FF8 fleeing doesn't work, since +2 and -2 cannot be triggered simultaneously. This may be a problem with the libretro analogue button implementation, not with beetle psx.

windows 10
retroarch 1.6.9
Beetlepsx 0.9.44.1f10cc4e

**Comment by hiddenasbestos** [comment]
This sounds like an issue with the way Microsoft implemented the trigger as a shared axis in DirectInput.
Try using the XInput driver as that supports independent triggers - mine was set to dinput and had the same thing - I switched it over and it now maps to +4 and +5 (had to restart RetroArch for it to take effect) which I assume will let you press L2+R2 in FF8

**Comment by FiLeonard** [comment]
Thanks, i didn't consider an input driver change. i thought maybe it is useful to allow the same axis to be triggered in opposite directions. maybe there are some (awkward) devices where it does make sense. But my problem is definitely solved.

**Comment by hiddenasbestos** [comment]
I think it was a backwards compatibility thing to make it like the rudder you'd get in a traditional PC joystick. Probably made sense back then but now joysticks aren't so popular and you probably want two trigger axes it does get a bit annoying. Luckily xinput exists :)

**Comment by FiLeonard** [comment]
Now i think of my sidewinder joystick back in the days :P you're probably right. The ability to map axis wasn't that good, and axis had to work out of the box in a game. Makes sense to turn your mech with the second axis on those L and R trigggers ^^
