### ISSUE TITLE
Uising vulkan driver causes segfault on Slackware64-current

### ISSUE THREAD

**Issue by khronosschoty** [libretro/beetle-psx-libretro#273]
Steps taken: start retroarch load beetle-psx core, load content. The game begins to start but quickly segfaults before even getting past the Sony PSX  boot logo.  RA menu is set to use Vulkan driver and the beetle-psx is set to use Vulkan driver. 

This was with: 
Linux kernel 4.14.2
Intel(R) Core(TM) i7-7500U CPU
mesa-2017.11.29_d93fabb013_master-x86_64-1_git
libdrm-2.4.88-x86_64-1
beetle-psx-libretro-2017.08.11_a6bbea0-x86_64-1_SBo

 > GNU gdb (GDB) 8.0.1
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-slackware-linux".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from retroarch...done.
> (gdb) ruin[K[Kn
> Starting program: /usr/games/retroarch 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> [New Thread 0x7fffdc3b0700 (LWP 3429)]
> [New Thread 0x7fffd9c6d700 (LWP 3435)]
> [New Thread 0x7fffd529c700 (LWP 3483)]
> [New Thread 0x7fffc3815700 (LWP 3485)]
> [Thread 0x7fffd9c6d700 (LWP 3435) exited]
> [Thread 0x7fffc3815700 (LWP 3485) exited]
> [Thread 0x7fffd529c700 (LWP 3483) exited]
> [Thread 0x7fffdc3b0700 (LWP 3429) exited]
> [New Thread 0x7fffdc3b0700 (LWP 3514)]
> [New Thread 0x7fffd529c700 (LWP 3520)]
> unhandled setting UI: psx.input.port1.gun_chairs
> unhandled setting UI: psx.input.port2.gun_chairs
> unhandled setting UI: psx.input.port3.gun_chairs
> unhandled setting UI: psx.input.port4.gun_chairs
> unhandled setting UI: psx.input.port5.gun_chairs
> unhandled setting UI: psx.input.port6.gun_chairs
> unhandled setting UI: psx.input.port7.gun_chairs
> unhandled setting UI: psx.input.port8.gun_chairs
> [New Thread 0x7fffc3815700 (LWP 3521)]
> [New Thread 0x7fffd9c6d700 (LWP 3570)]
> [New Thread 0x7fffc3014700 (LWP 3571)]
> [Thread 0x7fffc3815700 (LWP 3521) exited]
> Vulkan error at parallel-psx/vulkan/semaphore.hpp:40.
> terminate called without an active exception
> 
> Thread 1 "retroarch" received signal SIGABRT, Aborted.
> 0x00007ffff166dc9f in raise () from /lib64/libc.so.6
> (gdb) bt
> #0  0x00007ffff166dc9f in raise () from /lib64/libc.so.6
> #1  0x00007ffff166f717 in abort () from /lib64/libc.so.6
> #2  0x00007ffff4a0dc05 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib64/libstdc++.so.6
> #3  0x00007ffff4a0b9f6 in ?? () from /usr/lib64/libstdc++.so.6
> #4  0x00007ffff4a0ba41 in std::terminate() () from /usr/lib64/libstdc++.so.6
> #5  0x00007fff990759ae in Vulkan::SemaphoreHolder::consume (this=0x19aee60) at parallel-psx/vulkan/semaphore.hpp:40
> #6  0x00007fff99070541 in Vulkan::Device::submit_queue (this=0x1e6e6b0, fence=0x0, semaphore=0x0) at parallel-psx/vulkan/device.cpp:291
> #7  0x00007fff99070ebf in Vulkan::Device::flush_frame (this=0x1e6e6b0) at parallel-psx/vulkan/device.cpp:395
> #8  0x00007fff99036218 in PSX::Renderer::flush (this=0x1fba300) at parallel-psx/renderer/renderer.hpp:183
> #9  0x00007fff990a8a99 in rsx_vulkan_finalize_frame (fb=0x0, width=700, height=0, pitch=2800) at rsx/rsx_lib_vulkan.cpp:249
> #10 0x00007fff9902a0dc in rsx_intf_finalize_frame (fb=0x0, width=700, height=0, pitch=2800) at rsx/rsx_intf.cpp:241
> #11 0x00007fff9902275e in retro_run () at libretro.cpp:3858
> #12 0x0000000000419666 in core_run () at core_impl.c:415
> #13 0x000000000041ec3d in runloop_iterate (sleep_ms=0x7fffffffe0a0) at retroarch.c:3120
> #14 0x000000000041806e in rarch_main (argc=1, argv=0x7fffffffe1b8, data=0x0) at frontend/frontend.c:131
> #15 0x00000000004180cb in main (argc=1, argv=0x7fffffffe1b8) at frontend/frontend.c:151
> (gdb) bt full
> #0  0x00007ffff166dc9f in raise () from /lib64/libc.so.6
> No symbol table info available.
> #1  0x00007ffff166f717 in abort () from /lib64/libc.so.6
> No symbol table info available.
> #2  0x00007ffff4a0dc05 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib64/libstdc++.so.6
> No symbol table info available.
> #3  0x00007ffff4a0b9f6 in ?? () from /usr/lib64/libstdc++.so.6
> No symbol table info available.
> #4  0x00007ffff4a0ba41 in std::terminate() () from /usr/lib64/libstdc++.so.6
> No symbol table info available.
> #5  0x00007fff990759ae in Vulkan::SemaphoreHolder::consume (this=0x19aee60) at parallel-psx/vulkan/semaphore.hpp:40
>         ret = 0x438
> #6  0x00007fff99070541 in Vulkan::Device::submit_queue (this=0x1e6e6b0, fence=0x0, semaphore=0x0) at parallel-psx/vulkan/device.cpp:291
>         wait = 0x7fff990524f0 <std::allocator<VkCommandBuffer_T*>::~allocator()+24>
>         semaphore = @0x19aee40: {data = 0x19aee60}
>         __for_range = std::vector of length 1, capacity 1 = {{data = 0x19aee60}}
>         __for_begin = {data = 0x19aee60}
>         __for_end = {data = 0x2b904a0}
>         cmds = std::vector of length 0, capacity 1
>         submits = std::vector of length 0, capacity 2
>         last_cmd = 0
>         waits = {std::vector of length 0, capacity 0, std::vector of length 0, capacity 0}
>         signals = {std::vector of length 0, capacity 0, std::vector of length 0, capacity 0}
>         stages = {std::vector of length 1, capacity 1 = {1024}, std::vector of length 0, capacity 0}
>         cleared_fence = 0x2e39520
>         cleared_semaphore = 0x7fffffffdba0
>         result = 32767
> #7  0x00007fff99070ebf in Vulkan::Device::flush_frame (this=0x1e6e6b0) at parallel-psx/vulkan/device.cpp:395
> No locals.
> #8  0x00007fff99036218 in PSX::Renderer::flush (this=0x1fba300) at parallel-psx/renderer/renderer.hpp:183
> No locals.
> #9  0x00007fff990a8a99 in rsx_vulkan_finalize_frame (fb=0x0, width=700, height=0, pitch=2800) at rsx/rsx_lib_vulkan.cpp:249
>         scanout = {data = 0x2b90250}
>         image = @0x164bfc0: {image_view = 0x43f, image_layout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, create_info = {
>             sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO, pNext = 0x0, flags = 0, image = 0x43e, viewType = VK_IMAGE_VIEW_TYPE_2D, 
>             format = VK_FORMAT_R8G8B8A8_UNORM, components = {r = VK_COMPONENT_SWIZZLE_R, g = VK_COMPONENT_SWIZZLE_G, b = VK_COMPONENT_SWIZZLE_B, 
>               a = VK_COMPONENT_SWIZZLE_A}, subresourceRange = {aspectMask = 1, baseMipLevel = 0, levelCount = 1, baseArrayLayer = 0, layerCount = 1}}}
>         semaphore = {data = 0x7fffffffddb0}
> #10 0x00007fff9902a0dc in rsx_intf_finalize_frame (fb=0x0, width=700, height=0, pitch=2800) at rsx/rsx_intf.cpp:241
> No locals.
> #11 0x00007fff9902275e in retro_run () at libretro.cpp:3858
>         updated = false
>         rects = {700 <repeats 240 times>, 0 <repeats 336 times>}
>         spec = {surface = 0x1ae3750, VideoFormatChanged = false, DisplayRect = {x = 0, y = 0, w = 0, h = 0}, LineWidths = 0x7fff995f2a00 <retro_run::rects>, 
>           IsFMV = 0x0, InterlaceOn = false, InterlaceField = false, skip = 0, SoundFormatChanged = false, SoundRate = 44100, SoundBuf = 0x0, 
>           SoundBufMaxSize = 0, SoundBufSize = 734, SoundBufSizeALMS = 0, MasterCycles = 563946, MasterCyclesALMS = 0, SoundVolume = 1, soundmultiplier = 1, 
>           NeedRewind = false, NeedSoundReverse = false}
>         espec = 0x7fffffffde60
>         timestamp = 563946
>         __PRETTY_FUNCTION__ = "void retro_run()"
>         fb = 0x0
>         width = 700
>         height = 0
>         upscale_shift = 0 '\000'
>         interbuf = 0x7fff993e8140 <IntermediateBuffer>
> #12 0x0000000000419666 in core_run () at core_impl.c:415
> No locals.
> #13 0x000000000041ec3d in runloop_iterate (sleep_ms=0x7fffffffe0a0) at retroarch.c:3120
>         i = 5
>         input_nonblock_state = false
>         settings = 0x7ffff7fc5010
>         max_users = 5
> #14 0x000000000041806e in rarch_main (argc=1, argv=0x7fffffffe1b8, data=0x0) at frontend/frontend.c:131
>         sleep_ms = 0
>         ret = 0
>         args = 0x0
> #15 0x00000000004180cb in main (argc=1, argv=0x7fffffffe1b8) at frontend/frontend.c:151
> No locals.
> (gdb) quit[K[K[K[Kf a a [K[K[K[K[K[Kt aa[K a f
> 
> Thread 10 (Thread 0x7fffc3014700 (LWP 3571)):
> #0  0x00007ffff6cace6f in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
> 
> Thread 9 (Thread 0x7fffd9c6d700 (LWP 3570)):
> #0  0x00007ffff174168b in poll () from /lib64/libc.so.6
> 
> Thread 7 (Thread 0x7fffd529c700 (LWP 3520)):
> #0  0x00007ffff6cac98b in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
> 
> Thread 6 (Thread 0x7fffdc3b0700 (LWP 3514)):
> #0  0x00007ffff6cac98b in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
> 
> Thread 1 (Thread 0x7ffff7f60d80 (LWP 3423)):
> #0  0x00007ffff166dc9f in raise () from /lib64/libc.so.6
> (gdb) quit
> A debugging session is active.
> 
> 	Inferior 1 [process 3423] will be killed.
> 
> Quit anyway? (y or n) y

**Comment by orbea** [comment]
Its easier to read in code tags so...
```
[New Thread 0x7fffc3815700 (LWP 3521)]
[New Thread 0x7fffd9c6d700 (LWP 3570)]
[New Thread 0x7fffc3014700 (LWP 3571)]
[Thread 0x7fffc3815700 (LWP 3521) exited]
Vulkan error at parallel-psx/vulkan/semaphore.hpp:40.
terminate called without an active exception

Thread 1 "retroarch" received signal SIGABRT, Aborted.
0x00007ffff166dc9f in raise () from /lib64/libc.so.6
(gdb) bt
#0 0x00007ffff166dc9f in raise () from /lib64/libc.so.6
#1 0x00007ffff166f717 in abort () from /lib64/libc.so.6
#2 0x00007ffff4a0dc05 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib64/libstdc++.so.6
#3 0x00007ffff4a0b9f6 in ?? () from /usr/lib64/libstdc++.so.6
#4 0x00007ffff4a0ba41 in std::terminate() () from /usr/lib64/libstdc++.so.6
#5 0x00007fff990759ae in Vulkan::SemaphoreHolder::consume (this=0x19aee60) at parallel-psx/vulkan/semaphore.hpp:40
#6 0x00007fff99070541 in Vulkan::Device::submit_queue (this=0x1e6e6b0, fence=0x0, semaphore=0x0) at parallel-psx/vulkan/device.cpp:291
#7 0x00007fff99070ebf in Vulkan::Device::flush_frame (this=0x1e6e6b0) at parallel-psx/vulkan/device.cpp:395
#8 0x00007fff99036218 in PSX::Renderer::flush (this=0x1fba300) at parallel-psx/renderer/renderer.hpp:183
#9 0x00007fff990a8a99 in rsx_vulkan_finalize_frame (fb=0x0, width=700, height=0, pitch=2800) at rsx/rsx_lib_vulkan.cpp:249
#10 0x00007fff9902a0dc in rsx_intf_finalize_frame (fb=0x0, width=700, height=0, pitch=2800) at rsx/rsx_intf.cpp:241
#11 0x00007fff9902275e in retro_run () at libretro.cpp:3858
#12 0x0000000000419666 in core_run () at core_impl.c:415
#13 0x000000000041ec3d in runloop_iterate (sleep_ms=0x7fffffffe0a0) at retroarch.c:3120
#14 0x000000000041806e in rarch_main (argc=1, argv=0x7fffffffe1b8, data=0x0) at frontend/frontend.c:131
#15 0x00000000004180cb in main (argc=1, argv=0x7fffffffe1b8) at frontend/frontend.c:151
(gdb) bt full
#0 0x00007ffff166dc9f in raise () from /lib64/libc.so.6
No symbol table info available.
#1 0x00007ffff166f717 in abort () from /lib64/libc.so.6
No symbol table info available.
#2 0x00007ffff4a0dc05 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#3 0x00007ffff4a0b9f6 in ?? () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#4 0x00007ffff4a0ba41 in std::terminate() () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#5 0x00007fff990759ae in Vulkan::SemaphoreHolder::consume (this=0x19aee60) at parallel-psx/vulkan/semaphore.hpp:40
ret = 0x438
#6 0x00007fff99070541 in Vulkan::Device::submit_queue (this=0x1e6e6b0, fence=0x0, semaphore=0x0) at parallel-psx/vulkan/device.cpp:291
wait = 0x7fff990524f0 <std::allocator<VkCommandBuffer_T*>::~allocator()+24>
semaphore = @0x19aee40: {data = 0x19aee60}
__for_range = std::vector of length 1, capacity 1 = {{data = 0x19aee60}}
__for_begin = {data = 0x19aee60}
__for_end = {data = 0x2b904a0}
cmds = std::vector of length 0, capacity 1
submits = std::vector of length 0, capacity 2
last_cmd = 0
waits = {std::vector of length 0, capacity 0, std::vector of length 0, capacity 0}
signals = {std::vector of length 0, capacity 0, std::vector of length 0, capacity 0}
stages = {std::vector of length 1, capacity 1 = {1024}, std::vector of length 0, capacity 0}
cleared_fence = 0x2e39520
cleared_semaphore = 0x7fffffffdba0
result = 32767
#7 0x00007fff99070ebf in Vulkan::Device::flush_frame (this=0x1e6e6b0) at parallel-psx/vulkan/device.cpp:395
No locals.
#8 0x00007fff99036218 in PSX::Renderer::flush (this=0x1fba300) at parallel-psx/renderer/renderer.hpp:183
No locals.
#9 0x00007fff990a8a99 in rsx_vulkan_finalize_frame (fb=0x0, width=700, height=0, pitch=2800) at rsx/rsx_lib_vulkan.cpp:249
scanout = {data = 0x2b90250}
image = @0x164bfc0: {image_view = 0x43f, image_layout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, create_info = {
sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO, pNext = 0x0, flags = 0, image = 0x43e, viewType = VK_IMAGE_VIEW_TYPE_2D,
format = VK_FORMAT_R8G8B8A8_UNORM, components = {r = VK_COMPONENT_SWIZZLE_R, g = VK_COMPONENT_SWIZZLE_G, b = VK_COMPONENT_SWIZZLE_B,
a = VK_COMPONENT_SWIZZLE_A}, subresourceRange = {aspectMask = 1, baseMipLevel = 0, levelCount = 1, baseArrayLayer = 0, layerCount = 1}}}
semaphore = {data = 0x7fffffffddb0}
#10 0x00007fff9902a0dc in rsx_intf_finalize_frame (fb=0x0, width=700, height=0, pitch=2800) at rsx/rsx_intf.cpp:241
No locals.
#11 0x00007fff9902275e in retro_run () at libretro.cpp:3858
updated = false
rects = {700 <repeats 240 times>, 0 <repeats 336 times>}
spec = {surface = 0x1ae3750, VideoFormatChanged = false, DisplayRect = {x = 0, y = 0, w = 0, h = 0}, LineWidths = 0x7fff995f2a00 <retro_run::rects>,
IsFMV = 0x0, InterlaceOn = false, InterlaceField = false, skip = 0, SoundFormatChanged = false, SoundRate = 44100, SoundBuf = 0x0,
SoundBufMaxSize = 0, SoundBufSize = 734, SoundBufSizeALMS = 0, MasterCycles = 563946, MasterCyclesALMS = 0, SoundVolume = 1, soundmultiplier = 1,
NeedRewind = false, NeedSoundReverse = false}
espec = 0x7fffffffde60
timestamp = 563946
PRETTY_FUNCTION = "void retro_run()"
fb = 0x0
width = 700
height = 0
upscale_shift = 0 '\000'
interbuf = 0x7fff993e8140
#12 0x0000000000419666 in core_run () at core_impl.c:415
No locals.
#13 0x000000000041ec3d in runloop_iterate (sleep_ms=0x7fffffffe0a0) at retroarch.c:3120
i = 5
input_nonblock_state = false
settings = 0x7ffff7fc5010
max_users = 5
#14 0x000000000041806e in rarch_main (argc=1, argv=0x7fffffffe1b8, data=0x0) at frontend/frontend.c:131
sleep_ms = 0
ret = 0
args = 0x0
#15 0x00000000004180cb in main (argc=1, argv=0x7fffffffe1b8) at frontend/frontend.c:151
No locals.
(gdb) quit��[K��[K��[K��[Kf a a ��[K��[K��[K��[K��[K��[Kt aa��[K a f

Thread 10 (Thread 0x7fffc3014700 (LWP 3571)):
#0 0x00007ffff6cace6f in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0

Thread 9 (Thread 0x7fffd9c6d700 (LWP 3570)):
#0 0x00007ffff174168b in poll () from /lib64/libc.so.6

Thread 7 (Thread 0x7fffd529c700 (LWP 3520)):
#0 0x00007ffff6cac98b in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0

Thread 6 (Thread 0x7fffdc3b0700 (LWP 3514)):
#0 0x00007ffff6cac98b in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0

Thread 1 (Thread 0x7ffff7f60d80 (LWP 3423)):
#0 0x00007ffff166dc9f in raise () from /lib64/libc.so.6
```
