### ISSUE TITLE
Some games will not boot with video driver set to Vulkan

### ISSUE THREAD

**Issue by madig** [libretro/beetle-psx-libretro#275]
1. Set video driver to Vulkan
2. Try various PSX games with Beetle PSX HW

Some games work fine (e.g. Tomb Raider The last Revelation), others (I tried Legacy of Kain and Megaman X4) fail to boot. In the second part of the BIOS boot screen, the 3D PS is missing and the screen freezes there.

It doesn't matter if the rendering method is set to Vulkan or software in the core options. Only when I set software in the core and the video driver to OpenGL will all games work normally.

Self-compiled RA 1.6.8 with up-to-date Beetle PSX HW core, on Fedora 26 x86_64, GeForce 970 with NVidia driver 387.34.

**Comment by rz5** [comment]
@madig could you clone this repo and build it after  changing https://github.com/libretro/beetle-psx-libretro/blob/master/Makefile#L395 to -O2 instead? I might've let that change slip in despite being advised not to do it. If that's the cause of it on your system, I'll revert it right away.

**Comment by madig** [comment]
No change. Compiled it with both `make` and `make HAVE_HW`, both cores exhibit the same behavior: if the video driver is set to Vulkan, some games will not boot. they work normally once the video driver is set to OpenGL. I noticed the following console output with the Vulkan video driver that does not turn up with the OpenGL video driver:
```
[INFO] Environ SET_MESSAGE: Bad sector? - 7
[INFO] Environ SET_MESSAGE: Bad sector? - 8
[INFO] Environ SET_MESSAGE: Bad sector? - 9
[INFO] Environ SET_MESSAGE: Bad sector? - 10
[INFO] Environ SET_MESSAGE: Bad sector? - 11
[INFO] Environ SET_MESSAGE: Bad sector? - 12
[INFO] Environ SET_MESSAGE: Bad sector? - 13
[INFO] Environ SET_MESSAGE: Bad sector? - 18
[INFO] Environ SET_MESSAGE: Bad sector? - 2
```

**Comment by rz5** [comment]
Oh right, I remember a bug related to CHD/PBP that only happens when using the vulkan video driver. Are your dumps in bin/cue format or in single pbp/chd files?

**Comment by madig** [comment]
Bin/cue. The game that works (TR4) just so happens to be ccd/sub/img. That's curious.

**Comment by rz5** [comment]
I built RA and beetle-psx-hw for Windows, Legacy of Kain: Soul Reaver (bin/cue) boots and runs just fine. So despite some platform specific bugs (fullscreen causes all cores to emit black frames), I can't replicate this bug.

Windows 10, GTX 970 (Nvidia 388.59)

**Comment by madig** [comment]
Right, games work normally on Win10 here, too. Weird.

I'm wondering, what can make the "PS" graphic in the BIOS boot screen disappear (and the text below read "PS-X EXE" instead of "Playstation") when the video driver is set to VULKAN, even when the software renderer is used?

**Comment by madig** [comment]
Same with RA git master and up-to-date Beetle PSX core.

**Comment by remyabel** [comment]
Set "CD image cache"/"CD access method" to precache.

**Comment by madig** [comment]
Ah, that solves it, thanks! Closing this as a duplicate.
