### ISSUE TITLE
PGXP Perspective Correct Texturing Glitch - Syphon Filter

### ISSUE THREAD

**Issue by CammKelly** [libretro/beetle-psx-libretro#278]
Can be found in Syphon Filter 1.1 NTSC on Gabe's suit on 
Mission 2
Level 6: Expo Center Reception

Have uploaded a screenshot showing PGXP Perspective Correct Texturing On & Off (PGXP PCT On creates the glitch, PCT off removes it).

![syphon filter usa v1 1 -171217-222425](https://user-images.githubusercontent.com/10457377/34079074-005b0da0-e37a-11e7-891c-6d178929bec2.png)
![syphon filter usa v1 1 -171217-223243](https://user-images.githubusercontent.com/10457377/34079087-41439d96-e37a-11e7-8c3c-818d7808b8df.png)

**Comment by saftle** [comment]
This is the same bug as reported here: https://github.com/libretro/beetle-psx-libretro/issues/257. There is an open bounty on the issue. So far it has been fixed on GL, but not Vulkan. I recommend closing this issue, and attaching the screenshots to the other one. You can also contribute to the bounty if you would like.

**Comment by CammKelly** [comment]
My apologies. Feel free to delete.

**Comment by saftle** [comment]
Oh, I am not a moderator. You can just hit the "Close" button at the bottom of this thread.
