### ISSUE TITLE
Emulator Renders With Image Offset

### ISSUE THREAD

**Issue by Shalashaskka** [libretro/beetle-psx-libretro#286]
When booting up the game, the emulator's screen boots up offset, both in the BIOS menu as well as in-game. I've tried this with multiple different games, and I've tried to adjust the cropping options within the emulator options itself. At most, all this has managed to do is shift the screen from rendering too high on my monitor to too low.

I'm using OpenGL, and switching over to Vulcan didn't change anything.

The thing is that this issue just sort of spontaneously happened: I installed and ran the emulator just fine yesterday without any settings adjustments (at least, to the best of my memory). Then I booted it up today and found it in the state that its currently in.

![iwypf0m](https://user-images.githubusercontent.com/34748936/34266464-34eb5eba-e647-11e7-9fab-7ad84657652b.jpg)

**Comment by remyabel** [comment]
Backup your current config, delete the original file, let the emulator regenerate the config then perform a `diff`. That should tell you what setting is causing the issue.

**Comment by Shalashaskka** [comment]
Managed to reset the image by deleting the file like you said. Once the emulator rebuilt the config, it ran without issue.

**Comment by retro-wertz** [comment]
initial scanline and last scanlines........

**Comment by saftle** [comment]
Don't forget to close the issue :)
