### ISSUE TITLE
FMV doesn't work correctly with some shaders scaling

### ISSUE THREAD

**Issue by Great-Dragon** [libretro/beetle-psx-libretro#292]
![final fantasy vii usa disc 1 -170904-234400](https://user-images.githubusercontent.com/12208533/34696057-f107ce48-f4d5-11e7-9bc6-fdbdeaa84497.png)

How to reproduce:
- Change internal resolution to something bigger than 1x
- Load "crt-lottes-multipass-interlaced-glow" shader
- Change Resize to 1x for "shader16 = shaders/crt-lottes-multipass/crt-lottes-multipass-glow"

It looks like this is because FMV doesn't scale by the same value as a game. It remains 1x while a game itself renders based on "internal resolution" scale factor.

**Comment by ggdrt** [comment]
Going to go ahead and close this. FMVs should be upscaled on all renderers as of 66ff383. 

crt-lottes-multipass-interlaced-glow was updated back in August 2018 ([link](https://github.com/libretro/slang-shaders/blob/1035b1b04d9786ebe15c44d756ef73a36a3342c0/crt/crt-lottes-multipass-interlaced-glow.slangp)) and no longer matches the version specified in this issue.
