### ISSUE TITLE
Savestates broken in latest builds of PSX HW 0.9.44.1 (i.e. d2fb176)

### ISSUE THREAD

**Issue by tapperp** [libretro/beetle-psx-libretro#297]
Noticed my existing savestates don't work. Also tested making a brand new savestate with a different game, and loading it, and that also didn't work. In both cases the games would just hang up. Not crash, but just freeze basically.

Using RetroArch 1.70 Windows 10 64bit:
mednafen_psx_hw_libretro.dll nightly build 0.9.44.1 d2fb176 -- broken savestates
mednafen_psx_hw_libretro.dll older build 0.9.44.1 f25da35 -- working savestates

Thank you for your attention and the great emu core.

**Comment by ofry** [comment]
Try to use latest nightly version of Retroarch first.

Then... could you bisect this isssue? (last "good" commit (savestates works) and first "bad" commit (savestates doesn't work)?

**Comment by tapperp** [comment]
OK, I updated to the latest RA nightly for 1/16/18, and downloaded the latest PSX HW core via the online updater.

When I load a savestate, the state is retrieved properly, so for example I will be back in the gameplay where it was left off. BUT, as soon as disk access is needed by the game it freezes like there is no disk. In fact, when loading a state RA shows the "disk tray closed" message in the lower left corner. I have tried using sync and precache methods for disk loading with the same results. I have also tried making a new savestate then loading it, so it's not just old savestates that aren't working.

As far as which build was the one that first had this issue, I'm sorry I don't know. I was only using RA sporadically the past few months. So the last build I have that had good working savestates in PSX HW was the one I mentioned earlier, 0.9.44.1 f25da35 from around 7/27/17. Using that core build, the savestates work perfectly.

**Comment by twinaphex** [comment]
Your savestates from a few moments ago are likely incompatible with the most recent version.

**Comment by tapperp** [comment]
But it happens even with savestates made with the new version.

**Comment by fr500** [comment]
@tapperp does it happen with non-HW too?

**Comment by fr500** [comment]
I just tried on the latest master with the non HW core with GT2 bin+cue.
Are you using CHD? PBP? multidisk or something?

**Comment by tapperp** [comment]
PBP. I will try bin-cue later and see if that makes a difference. Odd though, because I am using the precache load option, so the whole disk image should be in RAM, no?

I will also try the non HW core.

Thanks.

**Comment by tapperp** [comment]
So, using the latest buildbot builds of PSX HW and non HW with latest RA 1.70 build.

First I tried a clean good bin-cue of Super Puzzle Fighter II Turbo (USA), and then made a new fresh PBP of that bin-cue to try.

PSX HW (software render, 2x CD speed, precache), playing **Bin-Cue** -- save state worked normally, load state worked normally.
PSX HW (software render, 2x CD speed, precache), playing **PBP** -- save state worked normally, load state freezes at any disk access --> seems to make the virtual disk image disappear (says "Virtual CD Tray Closed" upon state load. 

So, the culprit appears to be PBP's, or at least the code related to them. Since I am precaching the disk image, I would've thought the storage format would be inconsequential so long as the disk image is loaded initially into RAM. But apparently the precache of the image from PBP is getting lost upon savestate loading, but does not get lost when using bin-cue.

Thanks for your attention, and hopefully my info is helpful. I personally do prefer keeping PBP's because they save a lot of space when you have a good number of images.

**Comment by remyabel** [comment]
You say f25da35 works but d2fb176 breaks. That's a 210 commit range. Can you narrow it down using `git-bisect`? However, you'll need to compile from source and test it everytime, which is fairly tedious. I'd start with commits around those two first.

**Comment by tapperp** [comment]
I'm afraid that's a bit beyond my understanding. Never even heard of git-bisect before. Just an old gamer with some very basic understanding of programming concepts (i.e. back in the 80's I taught myself some Basic).

**Comment by retro-wertz** [comment]
im assuming @tapperp is using this on a 1-disc game/title? if so PR should fix this.

test done with 1 disk game. save state during intro (or fmv portion) and loading state stops emulation during disc access.

**Comment by tapperp** [comment]
retro-wertz, yes that's correct. I tested using Super Puzzle Fighter II Turbo (USA) which is only 1 disk. The problem happens even with brand new savestates.

**Comment by retro-wertz** [comment]
this should be fixed then when buildbot updates

**Comment by remyabel** [comment]
Nice job finding the fix. I feel like:

```
if((!cdifs || CD_SelectedDisc >= PBP_DiscCount) && PBP_DiscCount > 0)
CD_SelectedDisc = -1;
```

and

```
if(!cdifs || CD_SelectedDisc >= (int)cdifs->size())
CD_SelectedDisc = -1;
```

should be moved to `CDSelect`. Having the logic in one place will make it easier to find bugs/maintain. But I'll wait until he confirms your PR fixes the issue.

**Comment by retro-wertz** [comment]
no update?

**Comment by ofry** [comment]
I will test it soon (I hope till weekends).

**Comment by tapperp** [comment]
Sorry, I've been very ill.

Just tested the 1/18 PSX HW build with the 2/1 RA build, and savestates seem to work normally again with PBP images. 

Thank you for fixing this issue!

**Comment by rz5** [comment]
Good job @retro-wertz. Closing the issue.
