### ISSUE TITLE
RetroArch instantly crashes when going full-screen in OpenGL mode (f hotkey)

### ISSUE THREAD

**Issue by bryc** [libretro/beetle-psx-libretro#300]
I was playing a game for a good two hours, and left RetroArch running overnight. I came back today and decided to continue. I pressed F to go into full screen mode (was in window mode previously) and RetroArch instantly crashed. _All progress since I started that session was lost_ - I guess it only saves memory card updates to file if RetroArch closes properly, which it did not. 

Anyway, the bug is reproducible. It just crashes every time I press F for fullscreen. It also crashes when I switch the OpenGL internal resolution and resume gameplay. It does not occur in the software mode. 

I haven't been able to test Vulkan, as RetroArch itself crashes when minimizing the window (regardless of core). What a great time to be alive!

**System info:**
Windows 7
RetroArch 1.7.0
Beetle PSX HW 0.9.44.1 ad23401

**Comment by twinaphex** [comment]
@simias @rz5 I can confirm this issue.

It happens too when we try to change the internal resolution from 1x to any higher value.

We have had this issue before and now it's back again out of the blue. Are we not waiting properly until the GL context has been properly initialized by the frontend? The crashes happen in random rsx functions (rsx_gl_finalize_image I saw it crash at once, but also in rsx_gl_image_load - or whatever it's called).

**Comment by twinaphex** [comment]
Note: this only happens with the GL renderer. Vulkan is fine in this regard.

**Comment by twinaphex** [comment]
> I haven't been able to test Vulkan, as RetroArch itself crashes when minimizing the window (regardless of core). What a great time to be alive!

I think that latter issue could be resolved by updating your Nvidia drivers (assuming you have an NV GPU).

**Comment by bryc** [comment]
@twinaphex 

Just updated Nvidia drivers and restarted, doesn't help the vulkan minimizing crash. I am on Win7 btw, might be relevant since Win10 is becoming defacto OS.

**Comment by twinaphex** [comment]
Yeah I can reproduce it -

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000076d8ee24 in vk_optimusGetInstanceProcAddr ()
   from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_7a39871618b19f06\nvoglv64.dll
(gdb) bt
#0  0x0000000076d8ee24 in vk_optimusGetInstanceProcAddr ()
   from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_7a39871618b19f06\nvoglv64.dll
#1  0x000000000057fd3e in vulkan_acquire_next_image ()
#2  0x0000000000577e10 in vulkan_frame ()
#3  0x000000000044b042 in video_driver_frame ()
#4  0x000000000044815d in video_driver_cached_frame ()
#5  0x00000000004f3d09 in menu_driver_render ()
#6  0x000000000040394c in runloop_check_state.constprop ()
#7  0x00000000004077ef in runloop_iterate ()
#8  0x0000000000401680 in rarch_main ()
#9  0x00000000007f8068 in main_getcmdline ()
#10 0x00000000004013f7 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#11 0x00000000004014fb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184
(gdb) q
A debugging session is active.

Ugh, more nvidia driver shenanigans. So maybe we cannot call GetInstanceProcAddress when the window is minimized? Any thoughts @Themaister ?

**Comment by simias** [comment]
Is this a regression? If so, what caused it?

**Comment by twinaphex** [comment]
This should fix it -

https://github.com/libretro/beetle-psx-libretro/commit/94bf8ae57396edd50d75d075c020da8c54e16301

**Comment by bryc** [comment]
wow simple fix, that did it alright
