### ISSUE TITLE
RFE: Another attempt to the 'make disk change seamless' idea

### ISSUE THREAD

**Issue by i30817** [libretro/beetle-psx-libretro#305]
I've requested a closed issue to 'automatic' disk change before, that wouldn't work because it expected a push api where the volume identifier of the psx game was a argument for a library function to check it (this function apparently doesn't exist).

I had another idea now. How about if a user shortcut was created that when pressed:

1. changed disks for the 'next' disk on a set (from m3u or whatever)
2. waited for successful read only io on the psx drive (games typically recognize changed disks from trying to find a file, not parsing a ID)
3. If the first read succeeds, or you cycled through all disks on the collection stop.
4. If the first read fails, goto 1.

It's only a minor ergonomic gain but do you think it could work and it's possible to hook into the 'read' function of the ps1 like this?

**Comment by simias** [comment]
How do you define and identify a "successful read"?

**Comment by i30817** [comment]
The system call open returns success (0 if i recall my C-ishms)

**Comment by i30817** [comment]
The one thing i don't know if it's possible is to get at the system call parameters and return in psx memory. It's part of the bios i suppose right?

**Comment by simias** [comment]
I guess to be sure one would have to look at how games usually handle this and if a generic method can be devised. I'm not sure if having a successful `FileOpen` is enough for most game, what if it then looks for a certain identifier within the game? What if it executes a program on the disc instead? What if it uses a raw sector read?

Hooking the PSX BIOS functions would be the easy part, you just have to check for jumps to fixed addresses in memory.

**Comment by i30817** [comment]
If the method fails nothing happens. I think it's worth trying.


And, what's the problem with it searching another file? Even if it does that, the beauty of this method is that it doesn't need to be the *first* thing that the game does, but just one of them. In this case, when it finds the executable and execs it, 'a' game file will eventually be opened and success can be called that way.

But your observation reminded me that SYSTEM.CNF;1 should be blacklisted from this process. It contains the pointer to the executable in most ps1 games (and ps2), so it being opened for reading on disc change is not indicative.

**Comment by simias** [comment]
I think you should formalize exactly the procedure you have in mind (and how you ended up with it). I know fairly well how the CD code works and I have some trouble understanding what you want to do exactly. Are you guessing how games are working or did you actually check to make sure that it's what's happening? It wouldn't surprise me if different games handled disc switching differently.

What I'd like to see is 1/ a *factual* technical explanation of how disc swaps works in your average PSX game 2/ how you propose to hook emulator code into that to automate it.

I realize that you've already done some of that but I have some trouble discriminating what's fact and what's guesswork. I can help with the low level stuff but I can't be bothered to reverse engineer a bunch of games to figure out how they implement disc swapping.

**Comment by i30817** [comment]
It's honestly all guess work. My intention is as was stated: 
ps1 disc change success needs to open a first file. This is obvious because regardless of the method the game used to change cds, the game needs to continue, and opening a file with success to access new data.

The main problem comes from some failure cases which may leave the process in a limbo or wrongly assume success:
The game opens a 'first' file, but it's a for parsing a ID that is different on each disk (many pc games did this). Success opening here is not indicative the game recognized a new file.
The game doesn't open a file but uses `firstfile` and friends to find a file, but fails, so it won't ever get to use `FileOpen`

The second has a workaround by using a timeout. The first not so much. I'd honestly suggest just to try it to see how common it is, and blacklist opening SYSTEM.CNF because it seems the 'obvious' way to implement this if you're lazy.

However i think these would be *very* unusual. Because the 'best' way would be to just check that the executable exists, which is named differently in all of the disks. This is always true from a cursory check of redump, except on very very early games like Kings Field (Japan) where the executable was the default 'psx.exe' (these games don't even have a SYSTEM.CNF). However these games also don't change discs because they only have one.

**Comment by i30817** [comment]
Ok, you know what? This idea actually has further holes in it because even the failure case may open files (think of the changing screens in FFVII disc changes). And in the end it's not very much better than a manual disc change cycle shortcut, because games often require 'input' to detect the closed tray. I'll close this as a idea, sadly (because the situation is even worse than the ps1 in many other cores like x68000).

**Comment by simias** [comment]
I think making disc switching simpler is a noble cause, but I wonder if the first step wouldn't be to make the UI for disc switching a little simpler and more accessible. I haven't played a lot with disc-swapping so far but as far as I've heard it's a bit tricky to make it work in RA.

**Comment by i30817** [comment]
Well, it's not terrible if you have:
1. a m3u file (this can be automated, based on filenames and i made a script for personal use that does this based on dumping groups habits. It's simple enough to find files of certain extensions in a dir, sorting them, and grouping filenames with common substrings and stuffing those files in a m3u
2. shortcuts for switching, which RA has.

Problems occur when:
1. the core doesn't have m3u support, but needs it (far too many cores in RA)
2. the core needs two or more files at the same time, or the m3u pattern can't be applied because it uses another mechanism to list (dosbox, x680000 etc).

**Comment by i30817** [comment]
@simias , i created https://github.com/libretro/RetroArch/issues/6324 for my 'VFS m3u' idea if you're interested on it or working on it.
