### ISSUE TITLE
Silent Hill White Squares with OpenGL

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#306]
OpenGL seems to have several issues.
On the one hand the boot logo from the playstations is not correct (text is missing), on the other hand silent hill has a lot of graphical glitches.

Justa ctivate opengl, upscale the game and look at the results.

![silent hill-180217-231151](https://user-images.githubusercontent.com/10263536/36346110-3c7ac944-1438-11e8-84d7-deb0753f24ca.png)

**Comment by simias** [comment]
It's the infamous mask bit emulation issue. It's well understood but it's a bit of a pain to implement.

**Comment by twinaphex** [comment]
@simias We still badly require an implementation for this in the GL renderer.

**Comment by 07416** [comment]
Here is a screenshot of the game at native resolution:

![retroarch_2018_07_10_22_51_53_536](https://user-images.githubusercontent.com/14923168/42534322-21adee66-8495-11e8-9805-8b525f1b49dd.png)

**Comment by 07416** [comment]
Which renderer (video driver) should I use?

**Comment by Papermanzero** [comment]
Vulkan or software

**Comment by Papermanzero** [comment]
As simias already stated. It is the mask bit issue, which is described here in this news post:
https://www.libretro.com/index.php/introducing-vulkan-psx-renderer-for-beetlemednafen-psx/

An opengl implementation is possible, but it seems difficult. 
Nevertheless it is needed for the transparency effects in several games.

**Comment by twinaphex** [comment]
This pull request should finally fix this issue -

https://github.com/libretro/beetle-psx-libretro/pull/377

**Comment by Papermanzero** [comment]
This is fantastic. Bug is fixed. Meanwhile the core is really great. Time for a newspost on libretro.com ;-)

**Comment by iiiGerardoiii** [comment]
@07416 hmm I don't see anything tbh

**Comment by 07416** [comment]
@iiiGerardoiii I didn't quickly find any editing setting to highlight the issue in Gimp, sorry,

![Uploading retroarch_2019_01_30_21_16_22_973.png…]()

Do you see now?

**Comment by iiiGerardoiii** [comment]
oooh I see it now.

Good catch

**Comment by 07416** [comment]
> 
> 
> @iiiGerardoiii I didn't quickly find any editing setting to highlight the issue in Gimp, sorry,
> 
> ![retroarch_2019_01_30_21_16_22_973](https://user-images.githubusercontent.com/14923168/52007555-57232380-24d7-11e9-88f3-bbd044e9dcb4.png)
> 

Looks the same also in Mednafen (1.22.1) — I assume that this isn't an emulation bug.
