### ISSUE TITLE
[Vulkan] 16x rendering results in a crash

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#314]
A few months ago 16x in Vulkan worked without problems. It is reproducible with the following:

- Beetle PSX HW (Commit: 063eec6dc73f90c3da21829c6adbd2e421d3b9e5)
- Vulkan renderer
- Geforce GTX 970
- Nvidia Driver 391.01
- Windows 8.1 x64

I have attached the log file that is associated with the crash here:
[retroarch-log.txt](https://github.com/libretro/beetle-psx-libretro/files/1780425/retroarch-log.txt)

**Comment by saftle** [comment]
I just realized that a few months ago I switched from Windows 10 to Windows 8.1, so perhaps the problem is exclusive to Windows 8.1 Can anyone confirm?

**Comment by TransparentBlue** [comment]
I don't have that issue on my end.
- Beetle PSX HW (Commit: 063eec6, Stock core options outside of vulkan renderer and 16x resolution)
- Geforce GTX 1070
- Nvidia Driver 390.77
- Windows 7.1 x64 Ultimate

**Comment by rz5** [comment]
@saftle, this may just be a simple case of you running out of VRAM. In the log you posted, I notice you're using a shader that does a 4x upscale.

Ideally, the frontend would catch this this error and print a suggestive message about lack of VRAM (or refusing to honor the user-selected upscale factor)

**Comment by MoochMcGee** [comment]
Can we close this issue? It seems to be mostly resolved.
