### ISSUE TITLE
Render issues with Wild Arms 2 on Geforce GT730

### ISSUE THREAD

**Issue by shadelegend333** [libretro/beetle-psx-libretro#318]
Using windows 7, nvidia driver 388.13, Beetle PSX HW:

-PGXP only works on things within certain range of camera (mountains in the background still shake all over the place, while closer ground stays still, for ex).
~~-Certain texture filters cause glitches: gaps between texture tiles, character sprites aren't filtered properly (garbled).~~
-Right side of the background texture of windows and menus are glitched.
~~-3D character models' triangles separate from each-other with movement. gaps & overlaps.~~
-Battle transition makes screen render at 1x resolution with filtering, despite settings.
-When a character sprite walks into a forest 3d model on world map (and I think with teleportation), for ex, becomes garbled.
?-Texture filtering doesn't apply to fmvs (might be just how it works, maybe add video filter as feature?)

Can upload screens later if needs be.

**Comment by twinaphex** [comment]
Can you retest the PGXP issues again? PGXP has recently been updated and it could fix a lot of the display issues.

**Comment by shadelegend333** [comment]
[Accidentally clicked close.]

**Comment by twinaphex** [comment]
Can you upload some screenshots?
