### ISSUE TITLE
[Vulkan] No Texture Filtering on Vulkan anymore it is broken.

### ISSUE THREAD

**Issue by Kristijan1001** [libretro/beetle-psx-libretro#326]
Texture filtering used to work on Vulcan no it doesn't anymore i don't know what happen, here is a video of it working.

**# Core Version:** 

![](https://i.imgur.com/sTjLdpE.png)

**# Gif of showing that Texture Filtering Worked on Vulcan**

https://i.imgur.com/Jr8W1mP.gifv

**Comment by rz5** [comment]
In the gif you posted, you almost certainly are not using the Vulkan renderer. Those filtering options only ever worked on the GL renderer.

If I had to guess what's happening it's that RetroArch's video driver is still set to 'gl' when it should be set to 'vulkan'. Do check if this is right, I'll close this for now

**Comment by Kristijan1001** [comment]
@rz5 i never knew that this is how it worked , now the other feature of removing it makes sense !
