### ISSUE TITLE
¿Tearing? in beetle psx software

### ISSUE THREAD

**Issue by DukeJP** [libretro/beetle-psx-libretro#340]
(Its a copy/paste from libretro forums)

I am having tearing in the Beetle HW in software mode. This is the intro of jojo bizarre adventure and its notorious when the "thunder" sound and the light fills the screen. Its weird, not all games have tearing, in fact, Jojo works very well all the time aside from the intro.

![jojo s bizarre adventure usa -180607-114802](https://user-images.githubusercontent.com/24689994/41131534-34e63ef4-6a8a-11e8-9a22-0593a09a9c98.png)

In Hardware mode, there is no tearing here, but this mode is buggy for many games, i prefer the software mode.
My question is: maybe the intro (in real hardware) HAVE tearing? 

I am using retroarch 1.7.3, with vulkan driver, i have a nvidia gt640 video card and the option "triple buffer" and "vertical sync" set to "active" in the control panel. And the "vertical sync" option in retroarch too. My computer can run all psx games to 60fps with any problem.

EDIT: i tried al direct X drivers, and open gl too, and have the same problem.

**Comment by ggdrt** [comment]
I doubt this is a bug since the software renderer draws on a per-scanline granularity rather than a per-frame granularity like the hardware renderers. These sort of tearing issues are reproducible on upstream mednafen.
