### ISSUE TITLE
2d games running in different resolutions & my temporary solution to that

### ISSUE THREAD

**Issue by Gagert** [libretro/beetle-psx-libretro#342]
When emulating different retro systems in RetroArch, there's almost always an option to get a pixel perfect aspect ratio by doing integer scaling, thereby making each pixel a perfectly aligned square filling up the whole screen (with black borders where the image stops).

In systems like the NES and the GBA for example, the resolution is fixed and thereby the pixel amount is the same in each and every game. On the PSX on the other hand, the resolution varies quite a lot from game to game. That makes it a bit more tricky to get the games looking good while in fullscreen, and by good I mean making each and every pixel of the games being squares enlarged at a set integer value, and none of the pixels appearing rectangular in any shape or form.

The sort of games I'm thinking about are the 2D sprite based games on the PSX, not the 3D polygon based ones. Games such as Rayman, Castlevania Symphony of the Night, the Oddworld-series and Disney's Hercules and so on. In my opinion those games looks the best when each pixel is a perfect square no matter how much you enlarge the image.

Since simply applying a fixed resolution at the global config-file in the Beetle core itself would not do the trick for all those different 2D sprite based games, the first thing you would need to do is to find out the actual native resolution of the given game. To do that, you will first need to start the game of choice, press F1 to return to the Quick Setting Menu and from there press the Take Screenshot icon. After that navigate to the Screenshot-directory in your OS and find the screenshot from the game. The screenshot contains info of the actual native resolution of the game itself, so in the case of Castlevania Symphony of the Night the games native resolution is 256x240.

You would then need to create separate configs for each and every chosen game, selecting Aspect Ratio as Custom, and choose a resolution that is an integer of the games native resolution. As I'm personally using a full-HD TV with a resolution of 1920x1080, I could increase both the height and width of the image four times, thereby my resolution of choice for Castlevania Symphony of the Night is 1024x960.

My config file for this game now looks like this (RetroArch -> config -> Beetle PSX):

custom_viewport_width = "1024"
custom_viewport_height = "960"
aspect_ratio_index = "22"

Now I'm able to enjoy this game while playing it in full screen with big square pixels.

There are other resolutions also used by 2D sprite based PSX games. Disney's Hercules and Rayman uses 320x240, the Oddworld-games uses 364x240 and Mickey's Wild Adventures uses 320x252.

It would be nice if the Beetle core itself had the ability to find the games native resolution on the fly and thereby enlarge the image using the right aspect ratio settings automatically, without any user input. It could be very beneficial if a user has multiple monitors of different resolutions, and it would make this core a bit more user friendly for the end user (I have no idea how much work and effort that would take though).

**Comment by dankcushions** [comment]
isn't this just the 'integer scale' option? for it to take effect you have to remove your custom aspect ratio + viewport settings, but then it will use the largest integer scale it can, within your displays resolution.

**Comment by hizzlekizzle** [comment]
I think the issue is that he wants to do even smaller than integer, but on an automated basis. I think the console-border shaders serve a similar function, and the image adjustment shader also has a zoom function. Finally, using a custom aspect with integer scaling enabled does let you change the viewport size in integer increments, so you can set it as small as you like and then save a core override to make it load whenever the core is loaded.

**Comment by Gagert** [comment]
After reading [this guide,](https://forums.libretro.com/t/guide-removing-black-top-bottom-borders-keeping-aspect-ratio/17033/6) I figured out a more practical way around this issue. It's still a bit complicated, but I suppose that the way this guide handles the resolution switching is the proper way to do this.
