### ISSUE TITLE
[Vulkan] Alundra / Alundra 2 - Video Playback Offset

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#346]
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: Off
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: bilinear
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Memory only
PGXP vertex cache: On
PGXP perspective correct texturing: On
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 2x

GPU: Nvidia 760GTX

Description: Alundra and Alundra 2 (PAL version) have offsets during the playback of the intro and other video scenes. The video should be in the centre of the screen.
refernce: https://www.youtube.com/watch?v=gzJdlXPJaHs

Screenshot Alundra:
![alundra-180624-205444](https://user-images.githubusercontent.com/10263536/41822845-5ae3858e-77f6-11e8-9cb1-b21b6b89b0e1.png)

Screenshot Alundra 2:
![alundra 2 - der beginn einer neuen legende-180624-205622](https://user-images.githubusercontent.com/10263536/41822854-6de63528-77f6-11e8-8d6a-303af2102a6a.png)

**Comment by twinaphex** [comment]
It happens with the Vulkan renderer too. Only the software renderer gets it right.

**Comment by ggdrt** [comment]
Confirmed fixed for the GL renderer as of 7e76756

**Comment by ggdrt** [comment]
@hizzlekizzle I'm reopening this since unfortunately it's still not fixed for the Vulkan renderer yet. 

It's a GP1 display range command issue, I'll label the all the issues related to this in the next day or so.
