### ISSUE TITLE
[OpenGL] [Upscaling] Clock Tower 2 - Text is not correctly displayed & Verticle Lines

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#353]
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: Off
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: bilinear
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Memory only
PGXP vertex cache: On
PGXP perspective correct texturing: On
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 2x

GPU: Nvidia 760 GTX

Description: The text in clock tower 2 (PAL) is not correctly displayed. The characters do not have the same height. Moreover some screens have verticle lines (like the predecessor)
![clock tower 2 - the struggle within-180624-211111](https://user-images.githubusercontent.com/10263536/41823077-e013a4f2-77f9-11e8-9e05-0c80ec0c4df3.png)
![clock tower 2 - the struggle within-180624-211038](https://user-images.githubusercontent.com/10263536/41823084-f2345e38-77f9-11e8-8ce9-dcea677d210f.png)

Screenshot:

**Comment by Papermanzero** [comment]
Partially fixed with commit  a8aa726.
Intro screen still shows black lines

**Comment by twinaphex** [comment]
Looks fine to me now with the most recent commits -

![image](https://user-images.githubusercontent.com/1075274/42869930-c1968938-8a76-11e8-8d74-ed7ac20bf633.png)

**Comment by Papermanzero** [comment]
I can still reproduce the issue. Even with  6094309

**Comment by Papermanzero** [comment]
Sorry :-)
The vertical lines. This is due to the bilinear filter issue I linked
