### ISSUE TITLE
[OpenGL] Crash Bandicoot - Background tiles

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#354]
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: Off
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: bilinear
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Memory only
PGXP vertex cache: On
PGXP perspective correct texturing: On
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 2x

GPU: Nvidia 760 GTX

Description: The sprites and backgrounds in Crash Bandicoot (PAL) are totally broken. They have white lines. The issue can be avoided by changing the texture filtering. Compared to PCSX-PGXP (standalone), this is not occuring with bilinear filtering activated. Also the successor games (Crash 2 and 3 - PAL) version do not have issues with the filtering.

Screenshot:
![crash bandicoot-180624-211213](https://user-images.githubusercontent.com/10263536/41823117-6e367ff2-77fa-11e8-97be-0fd7bb9e74a2.png)

**Comment by twinaphex** [comment]
Nearest neighbor filtering would do that, yes. Try sabr instead, it should not suffer from that.

**Comment by twinaphex** [comment]
Also, turn off PGXP vertex caching. Dont make bug reports with it turned on from now on.

**Comment by Papermanzero** [comment]
Fixed with commit  a8aa726
