### ISSUE TITLE
[OpenGL] Ape Escape - Broken Backgrounds

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#356]
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: Off
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: bilinear
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Memory only
PGXP vertex cache: On
PGXP perspective correct texturing: On
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 2x

GPU: Nvidia 760 GTX

Description: Ape Escape has broken backgrounds. Some images which are used as background are completely distorted.

Screenshot:
![ape escape-180625-144627](https://user-images.githubusercontent.com/10263536/41851071-0c6f93c0-7887-11e8-9c8c-dad75614b3bc.png)

**Comment by twinaphex** [comment]
have you tried turning software framebuffer on?

**Comment by twinaphex** [comment]
Also, turn off PGXp vertex caching.

**Comment by Papermanzero** [comment]
Fixed with a8aa726
