### ISSUE TITLE
[OpenGL] Dead or Alive - Black Polygons & Broken Backgrounds

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#357]
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: Off
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: bilinear
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Memory only
PGXP vertex cache: On
PGXP perspective correct texturing: On
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 2x

GPU: Nvidia 760 GTX

Description: In Dead or Alive (PAL), the characters are sometimes rendered with black polygons. Also the background image is broken. The background image is somehow skewed.

Screenshots:
![dead or alive-180625-143228](https://user-images.githubusercontent.com/10263536/41851273-a2a56752-7887-11e8-9337-5bb302861e78.png)

![dead or alive-180625-143241](https://user-images.githubusercontent.com/10263536/41851307-bd19c3d0-7887-11e8-86ec-dae9b0558b08.png)

**Comment by twinaphex** [comment]
have you tried turning software framebuffer on? it is actually needed to be used in combination with the hardware renderer.

**Comment by Papermanzero** [comment]
Fixed with commit  a8aa726
