### ISSUE TITLE
[Vulkan/OpenGL] Gran Turismo 2 - HUD flickers and half render rate

### ISSUE THREAD

**Issue by HighBunkerHxH** [libretro/beetle-psx-libretro#361]
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: On
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: nearest
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Off
PGXP vertex cache: Off
PGXP perspective correct texturing: Off
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 1x

GPU: Nvidia GTX 750ti

Description: In Menu it runs Fine, but during racing the hud flickers every second and it runs very choppy

https://gfycat.com/TatteredPowerfulFlickertailsquirrel

**Comment by rz5** [comment]
I edited the issue title.

The HUD flickering also happens in the vulkan renderer. It can be slightly ameliorated if the "CPU frequency scaling (overclock)" core option is increased to 150%.

And something I noticed is that the effective framerate is lower than what's obtained with the software renderer, despite the internal framerate reporting 29,97fps on both cases. It feels like every odd frame is being skipped somehow.

**Comment by HighBunkerHxH** [comment]
Hello again, I updated the core again however while I increased the CPU frequency to 150%, it still has pretty low frame rate despite the internal framerate reporting 29.97 fps and I´m using Vulkan

**Comment by ToniBC** [comment]
Exactly the same happens to me, if the Framebuffer is deactivated the flashes disappear but other things may fail, but the speed is as low although as the companion the FPS marks them correctly. All this in Vulkan.

**Comment by HighBunkerHxH** [comment]
Hello again i found a weird fix regarding of Gran Turismo 2´s half render rate, it turns out that you have to turn run ahead to reduce latency option and set the number of frames to 1, this will fix the half render rate but since the run ahead option is pretty demanding for the emulator, this is very costly to the peformance, yes it will fix the half render rate but the peformance drops dramaticly when you use this hot-fix so I hope someone will fix the half render rate without resorting to use the run ahead latency option, just letting you know

**Comment by ToniBC** [comment]
Yes, activating run ahead and set the number of frames to 1, the speed seems to be correct, then you have to disable PGXP because it causes errors in this game in its two modes and as @rz5  commented, with CPU frequency scaling (overclock) at 150 % blinks are removed.

For the loss of performance, we now have Dynarec, so if the game is slow, it would have to be activated.

It is not the best solution, but while repairing or improving the hardware renderer, there is no other option. They are now focused on the Dynarec.

**Comment by ggdrt** [comment]
This issue should be solved on the Vulkan renderer as of e3e511b and on the OpenGL renderer as of 7d235b9. These patches also respectively address the significant screen tearing in the opening FMV of this game when played on the hardware renderers.

Seems like we can put this long-standing issue (https://github.com/libretro/beetle-psx-libretro/issues/129#issuecomment-265221182) to rest.

**Comment by rz5** [comment]
Can confirm, the issue has been fixed. Excellent work.
