### ISSUE TITLE
[Open GL] Arc The Lad III Disc 2 - specific location lock ups.

### ISSUE THREAD

**Issue by OCRBonk** [libretro/beetle-psx-libretro#362]
Now that i'm on to disc 2, i'm starting to run into lock ups.
 During Job #81 when you enter Cariote Cave after the character converse and take the left path. The first screen after, there are multiple points where the game just locks up. Music keeps playing but nothing happens. 
Easy and repeatable: 
Take left path, just go straight, once you hit a certain spot it just locks up. Try to move to the left most wall and move up and it locks up too.

I've encountered that in a few other places as well.

It happens in the software core or the HW core. I've tried multiple disc images and setting changes as well.

Here's my memory card if anyone wants to test. (It's the 4th save file at around 48 hours. Exit the town and go to the cave to the west.)
http://www.mediafire.com/file/w99nvrupxy9qh94/CDROM_2.1.mcr
http://www.mediafire.com/file/cb9a7th8u4q51sm/CDROM_2.srm

I had to bust out the ps2,crt,dex drive and memcard rex to switch discs as that doesn't work either in Mednafen. (Or in the standalone core) I might have to do it again. Or switch to playing on my PSP or something..

Windows 7 x64
i7 950
GTX 980 388.59 drivers
Retroarch build 1.7.2 (April 13,2018)
Using the latest downloaded cores.

**Comment by OCRBonk** [comment]
I should probably get the dex drive out (And get teh PS2 out of the closet again) and verify these lockups dont' occur on actual hardware I guess too.

**Comment by OCRBonk** [comment]
Whoah, ok. So this happens on the official PSN Eboot on a PSP GO as well. In the same exact spot.

I guess i really gotta check this on real hardware then..

**Comment by saftle** [comment]
Be sure to check the image against the redump.org CRC to verify whether it's a valid dump.

**Comment by OCRBonk** [comment]
Yeah I've already done that with my own image, a redump image from online and also from ripping the image from a PSN eboot.

However, this can be closed as it turns out this seems to be just an actual game breaking bug unless somehow my save file can cause this.

Because i've replicated the lock up glitch with the following.

1.Beetle SW/HW with 3 different images. An online downloaded Redump (Supposedly verified) image, the images ripped from the official PSN release, and my own disc images. (Don't have the hardware for a perfect rip, but it's good enough).
2.On the PSN release on a PSP (Using CWCheat to inject the memory card save)

3.The most important one on real hardware, I used my dexdrive and memcard rex to transfer the save to a memory card and the game locks up in the exact same location as everywhere else actual hardware (earlier PS1 model with the expansion port. Don't know which exactly as I have an aftermarket case on it.).
