### ISSUE TITLE
[Vulkan/OpenGL] Silent Hill Tree Textures Glitch

### ISSUE THREAD

**Issue by theoldsport** [libretro/beetle-psx-libretro#368]
On either hardware renderer, Silent Hill's tree textures seem to stretch/wrap the screen when close to camera. Not present on the software renderer. This occurs regardless of any enhancements settings

Build used- a8aa726
![image](https://user-images.githubusercontent.com/13494133/42273763-032a2528-7f3f-11e8-831b-597fca64e153.png)

**Comment by iCatButler** [comment]
I believe I've discovered why this is glitching specifically in hardware. It's to do with how quads are handled differently.

In the polygon rendering code there is a check that discards any triangle that extends beyond the limits of the screen like this. The software renderer treats quads as two separate triangles, testing each one before drawing it. The hardware renderers draw the quad as a whole on the submission of the second triangle, so the first triangle can fail this test but still be drawn if the second one passes.

At the moment I've fixed the issue just by killing the whole quad if either test fails, but I think it might be more correct to demote it to a triangle if only one part fails the test.

**Comment by rz5** [comment]
@iCatButler - That is awesome.

It would be interesting to add some hacks to that section of code, to prevent discarding triangles that would otherwise be seen when the widescreen hack is on...

**Comment by iCatButler** [comment]
@rz5 isn't the widescreen hack anamorphic, like that supported on the Wii?

So the vertex positions are squeezed horizontally into the original 4:3 aspect ratio during perspective transformation and then stretched to 16:9 when the final image is displayed. In which case they shouldn't exceed these bounds. Although there is still frustum culling done by many games that will remove objects before they even reach the transform stage.

**Comment by iCatButler** [comment]
I've put in a PR to fix this and improve visual stability of 3D quads, where the UV offset code for flipped sprites was incorrectly detecting them.

**Comment by theoldsport** [comment]
Tested latest build, looks great, culling correctly 👍

**Comment by orbea** [comment]
@iCatButler I just want to say that I appreciate the attention you have been giving this core lately. :)

**Comment by iCatButler** [comment]
@orbea thanks. It's a great project to be working on and the scope of these issues is just about right for me at the moment. They're also a good way to learn more about PS1 emulation in general.

For instance, the flipped sprite detection problem also occurs in the GPU plugins for PCSX-R, but it was only when I was refactoring Beetle's code for issue #398 that I fully understood the problem it was addressing and how. 
The extra fix that was submitted in my last PR seems to stop all the false positives, and the accompanying visual judder, and should be portable anywhere PGXP is integrated.
https://www.youtube.com/watch?v=EWFc9lR0Faw
