### ISSUE TITLE
Silent Hill white squares [OGL/Vulkan]

### ISSUE THREAD

**Issue by billywade** [libretro/beetle-psx-libretro#372]
Man, this game is popular.

Running a current (as of probably 30 minutes ago) build of the hardware variant, both OGL and Vulkan, using either software or hardware options, gives me the same error as #306. No amount of playing with the settings seems to fix it either.

EDIT: Stupid mistake on my part: soft resetting doesn't alter the video driver, Retroarch has to be exited and re-entered. Redacted.

**Comment by twinaphex** [comment]
No, Vulkan works fine with this game.

**Comment by billywade** [comment]
I get that Vulkan should, but I still get the error when using Vulkan. My guess is that this is an obscure discrepancy between mainline and HW.

**Comment by twinaphex** [comment]
This should be fixed now in the GL renderer -

https://github.com/libretro/beetle-psx-libretro/issues/306#issuecomment-406883424
