### ISSUE TITLE
[Feature Request] Speed up PAL games to 60Hz/FPS

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#376]
An option to speed up PAL games to 60Hz/FPS would be convenient.
Almost every developer only ported NTSC to PAL via a slowdown from 60Hz to 50Hz.
Therefore gamespeed and music playback are all slower than the original version.
An option to increase the speed (to get the original experience back) would be great.
Especially translated games could be improved in this manner.

**Comment by hizzlekizzle** [comment]
If you raise the max timing skew to 15% or so, it should push PAL games up to 60 fps.

**Comment by Papermanzero** [comment]
I will try. :-)

**Comment by Papermanzero** [comment]
Is working perfectly.
