### ISSUE TITLE
Expose support for negcon

### ISSUE THREAD

**Issue by retro16** [libretro/beetle-psx-libretro#38]
I found that the code already supports negcon but it is not exposed to libretro. Seems just a matter of calling SetInput with "negcon" pad type, and maybe a few declarations.
I failed to enable it myself since I don't know a thing about libretro's interfaces.

**Comment by phaseIV** [comment]
I did exactly this, enable negcon support, but for pcsx_rearmed/libretro/retropie. Maybe the code helps;
https://github.com/phaseIV/pcsx_rearmed

Reply here if this request still stands.

**Comment by hiddenasbestos** [comment]
Hi @retro16 I've just submitted a pull request to add this feature.
