### ISSUE TITLE
[OpenGL/Vulkan] 007 - The World Is Not Enough / 007 - Tomorrow Never Dies / Asteroids - Garbled graphics before/after CG movies

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#391]
This was first reported by me here: https://github.com/libretro/beetle-psx-libretro/issues/43#issuecomment-223126739

Both instances can be reproduced with default options in both the GL and Vulkan renderers. The software renderer does not have this problem. This was tested against the latest commit: 581a08fc62a21515e4f9d9fb2d0e96e5da434f43

Instance 1: Opening - Garbled Textures When EA logo fades away.

GL/Vulkan:
https://cloud.githubusercontent.com/assets/852777/15725546/c45c8f34-284c-11e6-9e4b-a4e0fa3b48cb.png

Software:
https://cloud.githubusercontent.com/assets/852777/15725627/0e087788-284d-11e6-93a6-b74b57c4af46.png

Instance 2: Opening - Green flash before MGM Interactive video starts.

GL/Vulkan:
https://cloud.githubusercontent.com/assets/852777/15725851/14054098-284e-11e6-9649-c52f07469fa7.png

Software:
Just a black screen.

Both instance 1 and 2 can also be reproduced in 007 - Tomorrow Never Dies (USA) and Asteroids (USA). When skipping the opening videos the garbled textures appear and the green screen flash occurs before the MGM video starts and after it ends.

**Comment by ggdrt** [comment]
Fixed, details in #619.
