### ISSUE TITLE
[OpenGL] Soul Blade - Water Level

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#396]
The water in the flowed ride level is broken.
There are a lot of white stripes or white areas

![soul blade-180726-230018](https://user-images.githubusercontent.com/10263536/43289346-f951014a-912a-11e8-94e5-8c7b16ddbbd3.png)

![soul blade-180726-225946](https://user-images.githubusercontent.com/10263536/43289334-ef080102-912a-11e8-979f-bd792ae11da3.png)

![soul blade-180726-225958](https://user-images.githubusercontent.com/10263536/43289337-f30874d0-912a-11e8-901d-7377354ea754.png)

**Comment by saftle** [comment]
This is a duplicate of https://github.com/libretro/beetle-psx-libretro/issues/396.

**Comment by saftle** [comment]
This is a duplicate of https://github.com/libretro/beetle-psx-libretro/issues/385

**Comment by Papermanzero** [comment]
Then we can close the issue
