### ISSUE TITLE
Analog stick range issue

### ISSUE THREAD

**Issue by razorache** [libretro/beetle-psx-libretro#40]
There are a few select PSX games that dont interpret the full analog range of a 360 controller incorrectly. The stick will be fully tilted and only a light tilt will be received. This issue has a fix in the original mednafen but still persists with the lib core. 

http://mednafen.fobby.net/documentation/psx.html#Analog+Sticks+Range+Issues

Could a toggle switch for this be added to the core options?

**Comment by saftle** [comment]
I experienced the same issue on Chrono Cross. Sometimes when moving left, it would revert to walking rather than running. I was using an official wireless xbox 360 controller. I was also able to reproduce this using the Steam Controller (when using the gamepad x-input template)

**Comment by saftle** [comment]
Related Issue: https://github.com/libretro/beetle-psx-libretro/issues/11

**Comment by simias** [comment]
Maybe it would be better to model a real DualShock's analog range and write a function to convert "canonical" coordinates returned by properly calibrated modern pads to the emulated DualShock version? I could try to plot a real dualshock's response for various angles, although that would be a bit time consuming. I guess I could test 8 positions (left/right/up/down plus the diagonals) and a few angles for each. That would give us a decent profile I think.

**Comment by simias** [comment]
Ryphecha made a few plots already:

"From a DualShock on a PS1":

![ds-left-plot](https://cloud.githubusercontent.com/assets/7925386/15658860/25cd0bcc-26c2-11e6-8ee6-1e20dc27e1d3.png)

"From a third-party XBox 360 controller with Mednafen with no in-emulator coordinate adjustments":

![medna-f510-plot](https://cloud.githubusercontent.com/assets/7925386/15658865/3d873832-26c2-11e6-8f27-127202356c06.png)

**Comment by simias** [comment]
Since I'm guessing that not all PC pads have the same profile maybe the only way to have a completely accurate stick emulation would be to have a calibration step to get the pad limits and use that to automatically scale the emulated version. Sounds a bit tedious though.

**Comment by fr500** [comment]
There is an option in standalone to make it work better, we haven't implemented that option on the libretro core.

**Comment by simias** [comment]
I understand that, I just wish there was a way to handle that a bit better. It's more like a calibration issue.

**Comment by personaone** [comment]
I wonder if the issue I raised for RetroArch actually relates to this:

https://github.com/libretro/RetroArch/issues/2988

**Comment by saftle** [comment]
@razorache  Please check the solution in https://github.com/libretro/beetle-psx-libretro/issues/78 to see if it fixes the issue for you.

**Comment by razorache** [comment]
@saftle No, that did not but thank you. I have tried re calibrating my controller in windows and I can "trick" the calibration square by hitting the corners to make the analog circle appear to be square. This gave me up and left but down and right still do not register.

**Comment by simias** [comment]
I've just implemented a new option "Analog self-calibration", disabled by default.

When enabled it monitors the max values reached by the input controller and use that to guess how "far" the stick goes. Then it uses that to scale the analog coordinates sent to the emulator.

For best results when this option is enabled (or when you're restarting the emulator) you should rotate the sticks once or twice at max amplitude for the algorithm to get a good estimate of the scaling factor, otherwise it will adjust while you're playing.

Please let me know if that works correctly.
