### ISSUE TITLE
Mednafen PSX is abandoned ?

### ISSUE THREAD

**Issue by deivkiau** [libretro/beetle-psx-libretro#408]
PSX core have many issues, some of them very old. In official mednafen page new release is presented, but all fixes is about NES, SNES, SS. So my question is - does mednafen abandoned psx core improvement, development ?

**Comment by DukeJP** [comment]
No! Hell no!  A couple of important fixes in recent times: Duke Nukem Total Meltdown now renders ok and its playable, this game AFAIK cant be played for years until now. Silent Hill now renders correct in hardware mode. Li Long stage in Soul Edge now works ok in hardware mode. 
The PGXP has been corrected and works much better in games like Tomb Raider.

![portapapeles-1](https://user-images.githubusercontent.com/24689994/44167227-0001d180-a0a4-11e8-8193-5875b90642d2.jpg)


Just see this in the main page: the core was updated a few days ago. There is active development here. You can be sure Mednafen PSX is the best psx emulator, way better than ePSXe.

**Comment by saftle** [comment]
@deivkiau I think your question is more suited for the Mednafen Standalone team, since Beetle PSX is in no way affiliated with that team, other than it being a fork.
