### ISSUE TITLE
Re2 dual shock edition won’t show game saves for disk 2

### ISSUE THREAD

**Issue by tetsuge1** [libretro/beetle-psx-libretro#415]
So I beat the game with the Claire disk and when I start the Leon disk there’s no save data even though the Saba data shows up on the Claire disk

**Comment by fr500** [comment]
That's not an issue, you should rename the save to match the disk 2 filename

**Comment by saftle** [comment]
Or play games using m3u playlist files that include all of the discs, that way you have one save for the m3u itself, rather than per disc.

**Comment by tetsuge1** [comment]
Already tried to rename the saves with no luck

**Comment by tetsuge1** [comment]
how do you make the iso into m3u files

**Comment by saftle** [comment]
@tetsuge1 on the docs page, it explains how to create an m3u playlist: https://docs.libretro.com/library/beetle_psx/. Please don't forget to close this issue :)

**Comment by tetsuge1** [comment]
Unfortunately that didn’t work either

**Comment by tetsuge1** [comment]
lol late reply yes the m3u worked loading both disk but the save data didnt and changing the save data name after the new m3u files didnt work either. I just cut my loses and moved on im going to close the thread thank you everyone for helping.
