### ISSUE TITLE
User should be informed when software rendering is used as a fallback (and why)

### ISSUE THREAD

**Issue by brianblakely** [libretro/beetle-psx-libretro#416]
If the user is not using either the OpenGL or Vulkan video driver, then Beetle PSX HW automatically falls back to software rendering.  A user unaware of this behavior may believe that the core is running in hardware mode, and that their device is simply under-performing.

The user should be notified that this fallback happened, and how to fix it.  Something similar is done when slow CD reads are detected: a notification tells the user to set their CD read mode to "precache".

**Comment by ggdrt** [comment]
Added in 748d4f8 with some more messages added in 62b6333.
