### ISSUE TITLE
PSX Beetle core freezes, lag, etc., on any backend since update. [Nvidia]

### ISSUE THREAD

**Issue by Khronikos** [libretro/beetle-psx-libretro#418]
Hello, currently playing Lunar, or not, and while the new RA is awesome, Beetle appears nearly broken. Not sure if Nvidia or what is going on here. Feel free to close report, but the issues are pretty bad on my end. Nothing changed in my RA settings, yet nearly every backend has problems, and OpenGL in general will only run normally in windowed mode. Any kind of fullscreen and there is huge amounts of drops in FPS. Other backends tend to freeze or just quit when trying to do anything in the menu.

Does not matter what shaders are using. Core is broken here. I am on the Nvidia drivers just before the last one, so I guess update and see what is going on? From forum posts not everyone liked the new drivers, and some people seem to think this is Nvidia's issue. Just posting in case this helps anyone.

**Comment by hizzlekizzle** [comment]
You may have already known this, but just to be sure/clear: DX11 driver will only work with the software renderer.

**Comment by Khronikos** [comment]
Hey, looks like this was resolved with the newest drivers here. I did a DDU uninstall just in case, and I am seeing no more issues with the FPS problems.

**Comment by gnufred** [comment]
@Khronikos I had the same issue and fixed it in the same manner. The default windows 10 NVIDIA drivers were causing this issue for me.

I had the same problem on all Libretro PSX core; BeetlePSX, BeetlePSX HW and PCSX ReARMed. I've tried dozens of options in all the cores and nothing would fix it.

Installing the latest NVIDIA drivers from their website fixed it for me.
