### ISSUE TITLE
Q: fog or draw distance incorrect, reveals pop-in geometry

### ISSUE THREAD

**Issue by mick-p1982** [libretro/beetle-psx-libretro#419]
Apologies, but can anyone comment on why a particular game (https://en.wikipedia.org/wiki/King%27s_Field_II) would emulate with its black fog too far back, or possibly without a gamma-correction style table that would crush blacks? 

The ePSXe emulator does the same as yours. The fog effect is crucial to hide pop-in elements. The fog is a form of clipping. How is it possible that two prominent emulators cannot get this right in this case?

I'm just seeking clues. The fog is not slightly off, but is way off, revealing defects that the game's producers probably would have fixed if they had ever played it without fog! I'm in the process of porting this game to a 3D RPG maker for Windows produced by the same company: From Software. If the black fog is a hardware style effect, or combination, then how on earth can emulators be so far off?

P.S. This game also a prominent emulation defect that results in its transparent menu panels overlapping, and so forming what looks like a crosshair. Especially on the main panel, which is apparently a composite of four pieces. Someone told me it is displaying this with sprite primitives, but I have no idea how they know that (I didn't press them.)

ANYWAY, these are two major glitches, which I hope that anyone with an interest in PlayStation emulation will find time to investigate. It's not like PlayStation emulation is in its infancy. Thanks. 

EDITED: I want to add that two features are easy to see how the fog effect is far off its mark. The first is the little island that you start the game on. If you step back from it, two sides of it will become unnaturally black. This is a weird effect in itself. But it does happen in the game, except it's barely visible because it should be engulfed in black fog. 

Second is the waterfall in the starting area. In it the fog should be very close.... even 2 times closer than it is in the emulator. As a result, not only does the waterfall disappear piece by piece, as it should not be visible except for the thinned fog... and even the mountainside behind it disappears. This is a first person game, so it's really troubling when prominent features completely disappear.

**Comment by twinaphex** [comment]
These issues might be related also to this other issue that happens with King's Field 1 (the Japanese-only game) -

https://github.com/libretro/beetle-psx-libretro/issues/307

It only renders correctly with the software renderer, both Vulkan/GL seem to exhibit what can only be described as wrong culling of geometry around the view frustum.

**Comment by mick-p1982** [comment]
RE #307 I think I tried SW, and I'm certain I tried the HW version with the Software option on. In any case, checking to be certain, the SW mode does remedy the menu (crosshair) problem, and I believe it also even fixes a similar problem on loading/continue panel that appears even on a fat PS2 I'm using for comparison.

The SW fog is definitely darker/closer. It makes the starting point's glitches less noticeable (enveloping them in fog more quickly) but not nearly as well as on the PS2. I never noticed this glitch, and if the developers had it would have been fixed, but knowing that it exists, I can see it on the PS2...

The waterfall however is still very bad in SW. Possibly even worse. The whole thing disappears from a distance. The PS2 covers it in fog from the same distance. I am somewhat familiar with PS internals, and file formats, however I do not know how fog is implemented, or if this is fog precisely. But I say I'm familiar because I hope someone sympathetic will shed some light on this for me, even if it doesn't come to a fix for the emulator. I'm really just looking for answers. Still, it's 2018, and it seems like this shouldn't be a problem for both this and ePSXe, after almost 20 years. I mean, how many games rely on fog to hide the limits of their draw distance after all? JK :)

**Comment by anothername99** [comment]
What makes it seem like it shouldn't be a problem in 2018?

**Comment by TheStolenBattenberg** [comment]
I'd like to state that the crosshair/grid formation in menus is caused by FromSofts use of 9-patch sprite/texture, i.e nine different quads with a part of the texture make up the entire menu background. This is done to avoid unwanted stretching on the corners and edges of the texture when scaling. The issue is probably down to bad scaling in the GPU emulation with these particular quads.

Here is an image for those unaware of how a 9-patch works. Red arrows represent which way a quad will scale stretching: [https://cdn.pbrd.co/images/HC391TJ.png](url)


It should be known that King's Field games are plagued with issues in every emulator. I don't think I've seen anything close to accurate ever.

**Comment by iCatButler** [comment]
PS1 games apply fog by adjusting the vertex colours based on their distance from the camera, this happens before vertices are supplied to the GPU, usually using the GTE to perform the calculations. The GPU then multiplies the interpolated vertex colour at each pixel with the texture colour to get the intended result.
In the software renderer and on original consoles the colour gradients will be implemented using stippling which helps break up the image even more. 

Out of curiosity. If you ramp up the contrast and brightness on the display when running the game on PS2 do you see the geometry errors more clearly?

**Comment by mick-p1982** [comment]
@iCatButler 
> Out of curiosity. If you ramp up the contrast and brightness on the display when running the game on PS2 do you see the geometry errors more clearly?
I will check another day, but doubtful, since it's pitch black and the television is carefully balanced, whereas the emulator is plain as day. Using Direct3D 9 fog calculations, I would compare the emulator to setting the fog distance to double the actual required distance. It's incredibly dramatic. I can't honestly see how it could be the result of vertex color calculations, unless calculator itself is off by a baseball outfield.

Below is a quote that mentions "fog" from a PDF called "Everything You Have Always Wanted to Know...".

> "The CPU is backed up by the GPU (Graphics Processing Unit), which takes care of all the data from the CPU and passes the results to the 1024K of dual-ported VRAM, which stores the current frame buffer and allows the picture to be displayed on-screen. Part of this picture involves adding special effects such as transparency and fog, something that the PlayStation excels at. This was to be the most impressive display of hardware the home gaming world had ever seen"

Just out of curiosity, my impression of the PS is that its rasterizer proper (hardware, or coprocessor) is effectively 2D. Meaning, it draws triangles, and doesn't do "transform and lighting." But I'm seeing a lot of things of late that cause me to wonder. Including the "PGXP" effect, which I've just learned about. I'm curious if programs hand off 2D or 3D polygons to the firmware like pipeline. And if the "GTE" is just software implemented on the CPU, or a ROM/firmware on another processor. If not, I wonder if emulators are picking apart the game EXE files, expecting them to be similar. Or if the BIOS is the GTE? Or if the GTE is a known entity that can be simulated. Sorry for the long wording, but I don't want to have to have to ask this twice.

**Comment by iCatButler** [comment]
You're correct that the PS1's GPU works entirely in 2D, the vertices it processes lack a Z or W component or surface normals. All transform and lighting is handled before hand by the GTE (Geometry Transform Engine), which is a custom maths coprocessor attached to the main CPU. The CPU is used to write primitives and other GPU commands as a linked list that it then signals the GPU to process in sequence.

The GTE performs a number of well documented operations on vertex data, such as transforming them from local to screen space, back-face culling, calculating basic coloured lighting values, linear interpolation (often used for animation) and calculating colour modification for fog. Most of which would be handled in modern hardware by vertex shaders.

PGXP (Parallel Geometry Xform Pipeline) stores the results of GTE transform instructions in floating point (with W component) and then mirrors all the operations that are performed on the resultant vertices (memory reads/writes) until they're read from memory by the GPU. At this point these higher precision data can be retrieved and used in place of the standard precision values, rendering more stable geometry with perspective correct texturing.

**Comment by mick-p1982** [comment]
@iCatButler So, did developers program/modify the GTE? Or is it a fixed function library? Did developers have the option of using the GTE's coprocessor for other purposes?

If these are vcolors, then what could be the cause of the GTE producing way off colors? Please if you can, see the game for yourself. I don't know how easily you guys are able to obtain disc images, but if it's not too much trouble, please give it a look. It only takes a few minutes to locate these glitches from the start of the game.

**Comment by iCatButler** [comment]
The GTE is a fixed function coprocessor, it doesn't load or run any form of microcode. It has instructions that can copy values from CPU registers to those of the GTE or load them directly from a memory address. It has other instructions that will trigger it to perform the desired operation on the data in its registers and then further instructions to write those back to the CPU registers or memory.

Both PCSX-R and Mednafen/Beetle emulate GTE functionality at a pretty low level, emulating all registers and flags involved and all the mathematical quirks of the fixed point arithmetic it uses. I'd imagine this behaviour has been documented by reverse engineering, which would have been pretty trivial given developers are able to address the GTE directly (even on Net Yaroze).

There are quite a few games that use the GTE to perform operations not related to visible geometry. This is a particular problem for PGXP as it modifies the returned values of NCLIP to prevent small triangles from being culled. For instance the Ridge Racer series use the GTE for collision detection, which at one point lead to cars bouncing off invisible walls when using PGXP.

I'll have a look at this and see if I can get some capture from a PS2 using component output for comparison (although Windows updates seem to have broken my capture setup). It seems more likely to me that this is related to the output signal becoming skewed rather than an error in the fog calculations.

Tomb Raider, which uses vertex fogging in a similar but less aggressive fashion, looks pretty much the same on both capture and emulation (accounting for 32-bit vs dithered 16-bit output): https://www.youtube.com/watch?v=sUpCD9Hxe_o

**Comment by iCatButler** [comment]
I've uploaded a video comparing capture from the PS2 and Beetle: https://www.youtube.com/watch?v=q5IAF8KpopI

I can't really see a great deal of difference between the two, the PS2 has slightly more contrast. The console capture is from a slim SCPH-90006 unit via component cable (and mislabelled it in the video, lol).

Let me know how this compares to what you're seeing.

**Comment by mick-p1982** [comment]
> Let me know how this compares to what you're seeing.

Well, I explained that yes, this glitch is visible. However, your PS2 capture is far more visible than my PS2. I think if this glitch was visible in the original that it would not have made it into the game. HONESTLY I think your PS2 may be using an emulator internally. PSN games have bad emulation on the PS3. And I think slim PS2s have emulators also.

My PS2 shows the waterfall transition smoothly. At no point do polygons disappear. The game does have polygons that disappear on the sides at some times, because the clipping frustum is 2D/top-down, but this is not one of those cases.

But I can add that, I recently purchased this title from Japan's PSN store, and played it. I did not encounter these glitches then. Unfortunately my PS3 croaked a while back. So, if your PS2 shows this issue, the PSN store version was made to work before putting the game on sale.

Were it myself, I would be very intrigued by this. Many emulators have this problem, so solving it should be a big event for the PS emulation community.

**Comment by Papermanzero** [comment]
Can you make a video?

**Comment by saftle** [comment]
@mick-p1982 Is it possible to record the TV (with a smart phone, camera, etc) to showcase the issue, rather than using a capture card?

**Comment by iCatButler** [comment]
@mick-p1982 I use ImgBurn to rip PS1 games and then check their MD5 hash against the values published by redump.org, so they should be of good quality.

> HONESTLY I think your PS2 may be using an emulator internally.
I believe that's correct. The later models of PS2 replaced the IOP chip with a PowerPC chip that emulated the original with a program called Deckard.

To test your theory further I braved the attic and dug out my original PlayStation console. It doesn't output component video directly but I was able to convert RGB scart output to component for some reasonable quality. Coupled with my low quality C875 capture card the input lag was horrendous.

Here's the resulting capture, once again compared to Beetle's Software output: https://www.youtube.com/watch?v=xXT5GGWtCYQ

I did try lower quality connections and there was a tendency toward crushed blacks, but increasing the brightness always made the geometry popping visible.

**Comment by mick-p1982** [comment]
Update: I am looking at it again. Funny thing, when I checked the PS2 the other day, I thought it was on its last leg, but when I thought about the colors it was making, it occurred to me that the R component might be plugged into the Red stereo output. Now I noticed the picture was very bright, nearly blinding so. So I didn't have to adjust the brightness. It also seems to depend on how you approach the elements that glitch out.

I never noticed these things in the past. The squares that go black are very noticeable. I wonder if the PSN store game is made to darken the screen, to approximate an NTSC television or something like that. Of course, it's my favorite game, so I've played it since I was young, although not obsessively.  

I don't see a brightness option in RetroArch, for all of its options. You'd think it would have a color settings menu! 

P.S. I'm sorry that my weird coincidence of having that cable plugged in wrong caused a ruckus. If not for that oddity, we would have been on the same page yesterday. Still... it seems to me that the game is mastered for a different color profile than what emulators are providing.

**Comment by mick-p1982** [comment]
BTW: About your latest video, do you see how the PlayStation's waterfall seems to be blend into the sky behind it smoothly, and is less noticeable. It could be down to where you stand, but it seems to me still that there is a difference. It's hard to say where. The Beetle waterfall just kind falls apart in giant square polygons.

Not to beat a dead horse.

**Comment by hizzlekizzle** [comment]
Looked approximately the same to me in the comparison vid.

For the brightness thing, we use shaders for all that stuff. Check out the image-adjustment shader in 'misc'. Many CRT shaders also include gamma adjustment, which darkens the screen a little bit.

**Comment by iCatButler** [comment]
@mick-p1982 ha, I'm sure I've done that before.

The console output will have been converted from digital to analogue and back again, not to mention been converted from RGB to YUV and encoded by the capture device (my raw USB3.0 capture card didn't want anything to do with it). That might account for the slight variance in brightness and colour balance.

> It also seems to depend on how you approach the elements that glitch out.

I've noticed the fog darkens more quickly toward the centre of the screen, as I was turning on the spot objects would get brighter as they moved to the sides, even though they weren't any closer. It's probably just a quirk of the maths used.

> Still... it seems to me that the game is mastered for a different color profile than what emulators are providing.

The emulators are outputting raw digital values directly from the console's VRAM whereas real hardware has a number elements that will alter the final image you see. The game's colours will likely have been balanced to the displays used in the development studio, regardless of how well calibrated they were or what connection type was used.

**Comment by Papermanzero** [comment]
So we can close the issue?

**Comment by mick-p1982** [comment]
@hizzlekizzle Well, color correction shouldn't require a shader (it should be injected into it) so it has an appropriate UI alongside the other options. I was able to set up an NTSC shader the other day, but combining it with other shaders did not fly. So I think the RetroArch shader UI leaves much to be desired, and is a poor man's substitute for color correction options.

**Comment by mick-p1982** [comment]
To everyone, yeah I'm red-faced, but don't know what to tell you. I don't believe the game was ever meant to be seen like this. But it's not really an emulation problem. I don't know if the PS2 I'm using is emulated or not (it has a hard drive that I use, that I don't think was part of the original models.... I had a Japanese one, but it died, as did my Japanese PS3. Both of which had PS/PS2 hardware.)

I will Close with this comment, but feel free to respond/discuss color balance solutions.

**Comment by hizzlekizzle** [comment]
@mick-p1982 As with most stuff in RetroArch, the shader system is immensely powerful and a person can do pretty much anything they want with it, as long as they know how to twiddle the right knobs, so to speak. In addition to the image-adjustment shader, there's also the color-mangler and the tone-mapping LUT shader. Here's a tutorial for using the LUT shader with photo editing software to produce a custom tone map: http://filthypants.blogspot.com/2017/06/retroarch-tone-mapping-lut-shader.html

**Comment by saftle** [comment]
Also the Natural Colors shader under the misc folder is perfect for PSX, since it adds alot of the saturation that older CRT TVs had.

**Comment by mick-p1982** [comment]
@saftle @hizzlekizzle I don't see anything like this in RetroArch, downloaded last week. I see Apply Presets, which chooses a single shader file, that doesn't have any useful parameters, none of which are called "Natural Colors" and most of which reduce RetroArch to running at 1fps even when it is paused! And the game in the background should either be a snapshot, or able to be hidden by disabling menu transparency if that's too much to ask. So I'm not impressed with RetroArch in the shader dept. I grade it an F. Needs work. I don't see any way to use it to address color issues via the provided UI. Thanks though.

**Comment by hizzlekizzle** [comment]
>So I'm not impressed with RetroArch in the shader dept. I grade it an F
rofl, ok.

This is better suited for the libretro forums, if you'd like to continue over there.

**Comment by twinaphex** [comment]
If a shader preset reduces your FPS to 1fps, your GPU is simply not powerful enough. It is as simple as that, really. If you run a really intense shadertoy at shadertoy.com, your FPS will grind down to a halt too. We are not going to put something in that will 'magically' disable the shader if it reaches below a certain FPS, RetroArch is not going to hold your hand when selecting shaders and is not going to get in your way either in the name of full configurability. 

Honestly, if you can write GLSL/slang shaders yourself, why is this an issue? All of the shaders were written by contributors, we have github repos for them. Anyone is free to submit more to them, and 99% of the time we merge them as-is.

**Comment by twinaphex** [comment]
>  So I'm not impressed with RetroArch in the shader dept. I grade it an F. Needs work.

Frankly this is a ridiculous claim to make. There are few programs that are as configurable and extensive when it comes to shaders as RetroArch. We pretty much made a shader spec that even Microsoft themselves use in Windows right now. There is literally dozens and dozens of downstream software making use of this shader spec. There are also few other programs that allow you to configure 16/32 passes, all with configurable FBO sizes, etc.

**Comment by twinaphex** [comment]
You can read more about the shader spec here -

https://docs.libretro.com/specs/shader/

Keep in mind there are two of them, or three to be exact.

Cg - deprecated, is kept around mainly because some older game consoles like PS3/Xbox 360 supported it and they still run on GL/D3D9 on PC.

GLSL - Works with the OpenGL driver. Is heavily used on both PC and mobile.

Slang - our new shader spec that is very close to being universal. Supported by Metal/D3D10/D3D11/D3D12/Vulkan video drivers. This should be the latest spec and once we have D3D9/GL support for it, you will see slang become the main shader spec.

**Comment by saftle** [comment]
@mick-p1982 my mistake, it's called Natural Vision. Shaders are very subjective, so can't say if it'll please your eyes as it does mine :)

**Comment by mick-p1982** [comment]
@saftle My comment was from one developer to others, that you can do much better by RetroArch's end-users. My life doesn't revolve around RetroArch/video games, so either the UI is half decent, or I can wait :)

**Comment by saftle** [comment]
This is why I mentioned the docs. The shader parameters are what you were missing. Also be sure to check out the news article here: https://www.libretro.com/index.php/retroarch-1-7-4-released/ under "Live shader editing with the desktop UI!." This is probably what you're looking for and is already in built-in.

A github issue should normally be created when you've thoroughly went through a given feature set. This probably would have been better suited as a forum thread, so that other users could have helped you. Instead developers were forced to handle a support issue.
