### ISSUE TITLE
[VULKAN] Chrono Cross severe graphical glitches with overclocking

### ISSUE THREAD

**Issue by Electricstar** [libretro/beetle-psx-libretro#422]
![hot garbage](https://user-images.githubusercontent.com/14850864/45060957-585b3c00-b070-11e8-8aa3-e811e0dc5139.png)

Chrono Cross has severe glitches when overclocking, most of which start happening at 150% CPU speed. However, in some situations, having the clock set to even 110% will cause graphical glitches. For some reason though, changing the resolution will undo the glitching, at least until you go somewhere problematic again (in terms of having high overclock).

**Comment by Electricstar** [comment]
'Running away from battle' test @ 240% OC

OpenGL:
![cchardwareogl](https://user-images.githubusercontent.com/14850864/47045251-594bb700-d160-11e8-9520-47f59e7f6d9d.png)

![cchardwarevulkan](https://user-images.githubusercontent.com/14850864/47045276-6f597780-d160-11e8-904a-ad516082e563.png)

**Comment by theoldsport** [comment]
This happens in Silent Hill and some other games too, exact behavior as you described. Perhaps change the title to be more general?

**Comment by iCatButler** [comment]
@Electricstar there should be a fix in the latest build for this if you could test it.

**Comment by theoldsport** [comment]
@iCatButler no more vertex explosions with Vulkan in Silent Hill, or any of the games I saw similar problems. Deep down I hoped you might inadvertently solve this issue #368, but it's clearly unrelated.
