### ISSUE TITLE
HW: Software framebuffer option doesn't work at start/restart in 32bpp mode, and is dithered when 32bpp mode is not dithered

### ISSUE THREAD

**Issue by mick-p1982** [libretro/beetle-psx-libretro#427]
FYI: In my experience, the Software framebuffer option (which I assume enables read-back effects?) doesn't work when a game is started. However, going into the options and setting any other option, makes it begin to work.

FWIW: I have a game that seems to save its picture, and use it as a background when you go into the game's menus. When I turn the game on, the background is always black. The only way to fix it is to go into Beetle's options and monkey with them. It's not enough to just open the Options screen, but changing anything seems to enable the background.

**Comment by hizzlekizzle** [comment]
I just tested the FF7 battle transition swirl, which I believe is a framebuffer effect as well, and it worked straightaway without having to change any other options first.

**Comment by mick-p1982** [comment]
In case anyone cares to follow-up, same game as here (https://github.com/libretro/beetle-psx-libretro/issues/419#issuecomment-418260663) (https://en.wikipedia.org/wiki/King%27s_Field_II)

Starting the game cold, and choosing New Game (or continue) the menu background is black. Go into Bettle Options, and toggle Software Framebuffer to OFF and back ON (should not functionally change anything) and the menu background now appears.

**Comment by mick-p1982** [comment]
EDITED: Just FYI the menu for entering the game has a black background... not to be confused with the menu inside the game, which shows the contents of the frame-buffer before the menu was entered.

**Comment by mick-p1982** [comment]
I found out from #441 that disabling 32bpp mode also fixes this problem. 

There is another problem also, in the 32bpp disables dithering (I think disabling Dithering is a better way to disable dithering) except that the frame buffer effects are **_still_** dithered in 32bpp mode. (#441)

**Comment by mick-p1982** [comment]
**If #441 is to be closed, please read over it, and address the problem with the Options screen allowing the dithering option in 32bpp mode, or consider adding a dithering pattern to 32bpp mode. Either way would be better than responding to a hundred bug-reports about dithering every year!**
