### ISSUE TITLE
Bizarre graphical glitches

### ISSUE THREAD

**Issue by foahchon** [libretro/beetle-psx-libretro#431]
I'm getting all sorts of graphical glitches with Beetle PSX HW. Basically, triangles flash all over the screen at all times. These glitches happen in all games, and even on the Sony/Playstation logo BIOS screens. I thought it might've been a BIOS problem, but the software renderer works fine and the BIOS checksums check out. Latest GPU drivers are installed. GPU is a GTX 960, and I'm running Windows 10. Thanks.

![doom usa -180920-125949](https://user-images.githubusercontent.com/7809059/45834617-9c3b7b80-bcd5-11e8-8d00-a0a5ff88eac4.png)
![doom usa -180920-130240](https://user-images.githubusercontent.com/7809059/45834618-9c3b7b80-bcd5-11e8-8bb0-a7f0568a92d0.png)

**Comment by saftle** [comment]
Could you please list all of the core options you have set, and which video driver you're using?

**Comment by foahchon** [comment]
Using the gl driver. Options are:

Renderer (restart): hardware
Software framebuffer, Adaptive smoothing, and Crop Overscan: on
All other on/off options are off.
Internal GPU resolution: 8x
Internal color depth: dithered 16bpp
Texture filtering: nearest
Line-to-quad hack: default
All speed options are set to native.

**Comment by foahchon** [comment]
Update: I just found out that if I start a game using the Reicast OIT core first, then start a game using Beetle PSX HW, the above issues go away.

**Comment by saftle** [comment]
The Adaptive Smoothing core option only appears if you're using the Vulkan driver. Are you using a frontend and/or are saving core specific options? I suggest creating a new retroarch installation separate to your current installation, to see if you have a problem on a freshly configured retroarch setup.

**Comment by foahchon** [comment]
If I go Settings > Driver, the video driver is set to gl, and in retroarch.cfg video_driver is also set to gl, but Adaptive Smoothing is still appearing in the pause menu options for Beetle PSX HW. At any rate, the issue is apparently resolved, though I don't know exactly how. The only thing I can figure is, I had some of the Latency options enabled (and recently disabled), and those were causing the graphical glitches. If I re-enable them, Beetle PSX HW does behave oddly, and I do get graphical glitches, though not identical to the ones I was getting before. I also tried a fresh installation of RA, just to see what would happen, and Beetle PSX HW ran fine there too (though Adaptive Smoothing still appears in the Options menu). So, I guess this one's resolved. Thanks for responding, saftle.
