### ISSUE TITLE
Framebuffer effects ghost image in Beetle HW

### ISSUE THREAD

**Issue by razorache** [libretro/beetle-psx-libretro#436]
Hi, 

Its been quite a while since I have been on here so if any of the posting rules have changed please inform me so I may repost correctly :)

I'm having an issue with certain framebuffer and transition effects (FF9 Jade cocoon, MGS) on Beetle HW at every resolution but 1x. When a swirl or blur effect is present the after image is left on screen and leaves a ghost image. I have regularly updated retro-arch and all of my cores regularly for the last 6 months so It is difficult to tell where it exactly came from.  Applying different texture filters removes the stuck image but garbles text windows and other small effects.

Thanks for your help!

**Comment by razorache** [comment]
![metal gear-180818-195133](https://user-images.githubusercontent.com/19499190/46447626-ed755180-c750-11e8-84ac-b5a0ecb28f18.png)
![metal gear-180818-195138](https://user-images.githubusercontent.com/19499190/46447627-ed755180-c750-11e8-8af1-42734ab8b170.png)
![jade cocoon-181003-112834](https://user-images.githubusercontent.com/19499190/46447628-ee0de800-c750-11e8-9850-e9a9a26339f7.png)
![jade cocoon-181003-113001](https://user-images.githubusercontent.com/19499190/46447629-ee0de800-c750-11e8-8363-374ed1e18c6d.png)

**Comment by razorache** [comment]
I am using 
i7 950
Win7 x64
Geforce 760 GTX
All drivers are up to date

**Comment by rz5** [comment]
Also list your core options and, if you're using RetroArch, which video driver you're using (vulkan, gl, etc).

**Comment by razorache** [comment]
Its Vulkan and all core options are default except for 

Software Framebuffer = On
Resolution = 2X
color = 32 bit
Dithering = Off

**Comment by razorache** [comment]
After some further testing it seems to no longer happen in MGS but still happens in Jade cocoon. The MGS screen shots are from a few weeks ago so something must have been fixed since then.

**Comment by RedPyramids** [comment]
Can you confirm it stayed gone? My core is up to date and I'm pretty sure this is the same issue that can be seen in Parasite Eve II. Only way around it is software mode, which has graphical glitches of it's own.

I also can't use Vulkan for some reason. It seems there is a bug with Nvidia that created black artifacts that tear down the screen (even over the retroarch overlay).

So, not sure if it has been resolved with Vulkan but it still persists for me with GL.

**Comment by razorache** [comment]
Well, I'll be. My problem came back. I was fiddling with it switching between software and Hardware and I somehow got MGS to display correctly at 2x with Vulcan but after updating again its back to broken.


![jade cocoon-181102-133316](https://user-images.githubusercontent.com/19499190/47931885-74c7f900-dea6-11e8-8226-e0bff65b693c.png)
![metal gear-181102-130726](https://user-images.githubusercontent.com/19499190/47931887-75608f80-dea6-11e8-94a0-c6057ce199e7.png)
![metal gear-181102-130741](https://user-images.githubusercontent.com/19499190/47931889-75608f80-dea6-11e8-9b6c-95140477ca0f.png)

**Comment by rz5** [comment]
@razorache - Lots of changes since you posted this bug. In hindsight, I am quite certain you were using the GL renderer inadvertently - these bugs are caused by #413 and #414 - because we used to let you pick vulkan or opengl, despite the vulkan renderer only being in effect if RetroArch also had its video driver set to vulkan.

Can you confirm that this is still happening to you?

**Comment by razorache** [comment]
That did it! I did a fresh install and it works now. I could have sworn I had the drivers set to vulkan previously but they somehow became unset.
