### ISSUE TITLE
[Feature Request] Add Chroma Subsampling Filter for FMV

### ISSUE THREAD

**Issue by whatwwkd4496** [libretro/beetle-psx-libretro#447]
![a1](https://user-images.githubusercontent.com/29114898/48670362-40f8fe80-eb49-11e8-831b-fa413e793b06.png)
it looks like this
![a2](https://user-images.githubusercontent.com/29114898/48670512-8caca780-eb4b-11e8-85ae-553e659447fa.png)
this one is manually converted with jpsxdec with bicubic chroma subsampling

**Comment by rz5** [comment]
Is this an actual bug with beetle-psx?

It seems like you're comparing beetle-psx's output with jpsxdec's output, which has a bicubic filter applied to it.

**Comment by whatwwkd4496** [comment]
it's not  a bug, should the title changed to enhancement.

**Comment by rz5** [comment]
Yes, if this is about requesting a feature, be as descriptive as you can be and change the title to something like "[Feature Request] Add feature X".

If you're using beetle-psx with RetroArch, there's a LOT of shader presets you can use, including presets that add CRT-like artifacts which would most probably hide the YCbCr <-> RGB errors you're noticing.
But I guess you're interested in smoothing out these errors only in FMVs?

**Comment by Themaister** [comment]
I suspect this would be accomplished by modifying the scanout shaders for 24-bit to look more like:
- Convert RGB to YUV
- Downsample UV with box filter and upsample it again with bilinear (can be merged to one pass)
- Convert Y + blurred UV to RGB again
- Pass to frontend.
