### ISSUE TITLE
SCEA logo

### ISSUE THREAD

**Issue by Naccarato** [libretro/beetle-psx-libretro#458]
SCEA load screen is missing text:

![final fantasy viii usa disc 1 -181205-183818](https://user-images.githubusercontent.com/7443004/49680028-23d79180-fa5e-11e8-8636-e0f685f87363.png)

**Comment by muskieratboi** [comment]
Bad Game Rip. try another.

**Comment by wesker265** [comment]
Is PGXP set to Memory Only or Memory +CPU? I have noticed text issues in certain titles when Memory+CPU is activated. Try changing that setting and see if it reproduces itself.

**Comment by ggdrt** [comment]
Closing this due to lack of info and issue being stale.
