### ISSUE TITLE
[Vulkan] Retroarch crashes when loading a game, shows video with wrong colors.

### ISSUE THREAD

**Issue by Trevor-Z** [libretro/beetle-psx-libretro#467]
## Description

Retroarch closes when loading a PSX game using the Vulkan renderer. Most of the time this happens immediately, but with some games a loading screen or intro video will come up before the crash. Two examples:

- Vagrant Story: A loading screen shows up, then RA crashes.
- Tenchu: The "Activision" and "Sony Music Entertainment" logo videos play, with wrong colors, then RA crashes.

### Expected behavior

The Beetle PSX HW core works normally with other backends.

### Actual behavior

A picture showing the wrong colors on the intro video of Tenchu. Left is normal behavior with other backends, right is Vulkan.
![untitled-1](https://user-images.githubusercontent.com/13950948/50034476-226d1280-ffe4-11e8-9f6a-c4ec54a519aa.jpg)

### Steps to reproduce the bug

1. Select the Vulkan video driver
2. Close and reopen RA so the change takes effect
3. Load a game

### Version/Commit

Retroarch 1.7.5

- Beetle PSX: 0.9.44.1 9ebdeb5

### Core options

Default options.

### Environment information

- OS: Windows 10, up to date.
- GPU: Intel HD Graphics 620, driver version 24.20.100.6286

**Comment by Jj0YzL5nvJ** [comment]
The `Intel HD Graphics 620` drivers on Win10 have been broken since November (**SolidWorks does not render**). Downgrading the drivers to 2017's ones makes it work again.

**Comment by Trevor-Z** [comment]
Welp. It seems you're right. I downgraded to the 15.47.02.4815 driver version, from 10/10/2017, but it didn't seem to have Vulkan support, or at least it wasn't mentioned in the "Intel Graphics Settings" app. Retroarch wouldn't even open.

But then I made Windows update the driver, which got me not to the latest version, but to 23.20.16.4973, from 28/02/2018, and now the Vulkan backend doesn't crash anymore, although the videos still have this weird green tint.

Do you know if someone filed a bug report with Intel?

**Comment by Jj0YzL5nvJ** [comment]
> Do you know if someone filed a bug report with Intel?

Even if they do, [make your own](https://www.intel.com/content/www/us/en/support/articles/000031275/graphics-drivers.html).
