### ISSUE TITLE
[Bug] Gun crosshair works correctly only in native resolution

### ISSUE THREAD

**Issue by voradori** [libretro/beetle-psx-libretro#471]
###  Description

Crosshair is behaving wrong on X-axis with internal resolution >1

### Expected behavior

Crosshair correctly follows mouse cursor and real ingame aim mark on any GPU render scale

### Actual behavior

a)
Crosshair's position on X axis is divided by N when using N image scaling. 
E.g. when scale = 2, and mouse is in the center, crosshair is between cursor\mark and left screen edge

Y axis works as expected.
It's just crosshair X position draw bug - real aim mark is where it should be. 

![beetle psx](https://user-images.githubusercontent.com/5952315/50057606-fab1b200-017d-11e9-8c5d-4978901658c2.png)

b)
There is also a very slight difference between crosshair and aim mark (and mouse cursor when windowed) even on native internal resolution -  the closer crosshair to left\right edge is, the bigger is the difference. But it's very minor thing - the biggest difference is about 0.5 cm on a standard fullhd 24" screen

![beetle psx 2](https://user-images.githubusercontent.com/5952315/50057642-4d8b6980-017e-11e9-98ac-6bfcfba14d9b.png)
![beetle psx 3](https://user-images.githubusercontent.com/5952315/50057643-4d8b6980-017e-11e9-9027-c9108c073eab.png)

### Steps to reproduce the bug

1. Set input device 1 to Guncon
2. Run Time Crisis to calibration screen
3. Shoot at the aim to spawn red aim mark
a)  4. Set internal gpu resolution to any value > 1
b)  4. Let Internal gpu resolution at 1
5. Move crosshair to Left and Right edges (try in both windowed and fullscreen)
### Version/Commit

0.9.44.1 beeee12 SW\HW core 
(There's no working crosshair and even shots under mouse cursor on HW core for gl\vulcan renderer, even in SW mode. DX renderers works with same problems as SW core)

### Core options
Internal GPU Resolution = 2
Skip Bios = True
Widescreen hack = true

### Environment information

- OS: Win10 Pro x64 1809
- Retroarch 1.7.5

**Comment by Jj0YzL5nvJ** [comment]
Is the widescreen hack. That option only works correctly on some 3D games. The "aim" is a 2D element.

**Comment by voradori** [comment]
don't judge with no testing. 
everything is the same for WS hack off

**Comment by Jj0YzL5nvJ** [comment]
This recall me a very old bug on Linux with the first generation of Intel HD Graphics...
What is your GPU and driver version?

**Comment by voradori** [comment]
GTX 980, driver 416.94

**Comment by SirFritz** [comment]
I also have this issue, and on higher resolutions than 2x crosshair disappears completely.  I have also experienced the slightly out of sync crosshair on the sides of the screen.

GTX970 417.71

**Comment by ggdrt** [comment]
Issue has been diagnosed to screen space scaling in `input_handle_lightgun()` and `input_handle_lightgun_touchscreen()` in `input.cpp`. The scaling formula needs to be modified to account for the internal resolution scale, horizontal overscan cropping, and potentially the initial/last scanlines setting.
