### ISSUE TITLE
Something wrong with BIOS timing

### ISSUE THREAD

**Issue by deivkiau** [libretro/beetle-psx-libretro#475]
## Description

Many games, but worst of all - KKND - Krossfire (Europe).
Couldn't find evident on real hardware, but as example from "xebra" emulator BIOS finished to load and then game started.

### Expected behavior

BIOS should load fully without interrupting and then game start. https://youtu.be/cCz39rtvOXE (XEBRA)

### Actual behavior

Looks like games starting to fast and interrupting BIOS. https://youtu.be/gXFqAH4-10U (Beetle PSX)

### Version/Commit

- Beetle PSX 0.9.44.1 1d6ba98

### Core options

Default.

### Environment information

- OS: Windows 10 PRO 64 [Version 10.0.17763.195]

**Comment by hizzlekizzle** [comment]
Youtube says the videos are unavailable.

**Comment by deivkiau** [comment]
Links fixed.

**Comment by ggdrt** [comment]
The BIOS-to-game transitions using the core are all reproducible in upstream mednafen, so unless mednafen changes anything in this area, there's not much of an incentive for us to do so as this issue does not negatively impact performance or general gameplay.
