### ISSUE TITLE
[Beetle PSX HW] Loading save state causes water to lose transparency in Tomb Raider II

### ISSUE THREAD

**Issue by hyrulegoomba** [libretro/beetle-psx-libretro#480]
(Note: More detailed description, including screenshots, at bottom.)

### Expected behavior

Load save state in Tomb Raider II without causing water to lose transparency.

### Actual behavior

Loading save state in Tomb Raider II causes water to lose transparency.

### Steps to reproduce the bug

1. Create save state.
2. Load save state.

### Bisect results

Recently installed RetroArch (v1.7.5) and Beetle PSX HW and this is the first time I've used either, so can't say if this issue existed in previous versions.

### Version/Commit

Beetle PSX HW: 0.9.44.1 1d6ba98
Beetle PSX HW: 0.9.44.1 c20eac9

### Core options

All core options are set to default.

### Environment information

- OS: Windows 10
- GPU: Nvidia GTX 1070

### Long description

This issue occurs using OpenGL with all core options set to default.  I have tried messing around with the core options a little, e.g., adjusting internal resolution, changing texture filters, toggling PGXP, (with full restarts in between) to no avail.  Also tried downloading and running the latest nightly for this core (c20eac9) with no change.

Switched to software renderer and *it does* work without issue, though, despite having a fairly decent machine (with an i7 4790), setting the resolution to anything above native causes quite a bit of slowdown.

Below are a couple of screenshots.  The screenshots are from the swimming pool in Lara's home, but I have tested it in areas with water in the first and second levels of the game, and the issue persists.

How it looks after selecting 'Save State':

![tomb raider ii-190108-133302](https://user-images.githubusercontent.com/45372132/50855060-6b4a8980-134c-11e9-9fbe-9e63ef0d73c1.png)

And how it looks after selecting 'Load State':

![tomb raider ii-190108-133317](https://user-images.githubusercontent.com/45372132/50855075-76051e80-134c-11e9-9803-e30997b968f6.png)

Please let me know if there is any other information I can provide.

**Comment by trostboot** [comment]
This is an odd one. For the record, also on Win10, GTX 1080, RetroArch 1.7.6 (Apr 17th 2019), Beetle PSX HW 0.9.44.1 5359198.

The level Living Quarters is excellent for testing this, as it starts underwater. Here's what I noticed. For the sake of testing, all rendering enhancements were turned off (native res, no MSAA, no perspective correction, no PGXP, no quad-to-line hack).

1. Loading into the level using Vulkan hardware rendering, quicksaving, then quickloading - water is now broken.
2. Switching to software rendering, restarting, then loading the savestate created in step 1 - water is now broken.
3. Still using SW rendering, reloading the level from within the game, quicksaving to a new slot, then reloading that save - water still works.
4. Switching to hardware rendering, restarting, then loading the savestate created in step 3 - water still works. In fact, quicksaving again and reloading that new state will still result in the water displaying correctly.

IOW, it looks like something goes wrong when the water is first loaded in using HW rendering, that somehow only manifests when a savestate created from that is loaded.

**Comment by trostboot** [comment]
Same issue also occurs during field battles in Suikoden - sky disappears after loading a savestate created using the HW renderer, but will remain visible if the state was created after loading the battle using the SW renderer.

![Yes sky](https://user-images.githubusercontent.com/17594477/58915290-f9227900-8720-11e9-9be8-8488305cb984.png)
![No sky](https://user-images.githubusercontent.com/17594477/58915289-f889e280-8720-11e9-8f8a-234b0162da82.png)
[Savestate for US version 1.0.](https://github.com/libretro/beetle-psx-libretro/files/3254583/Suikoden.NTSC-U.state4.zip) Just hit X to start the battle.

**Comment by ggdrt** [comment]
@hyrulegoomba @trostboot I know it's been a long time since this issue was opened, but can you test if the issue is still reproducible?

**Comment by trostboot** [comment]
Sure thing. Looks like it is fixed, tried both Tomb Raider II and Suikoden, fresh boot with Vulkan HW rendering, both test cases are still correct after loading a newly created savestate.

**Comment by ggdrt** [comment]
Thanks for confirming. Not sure what caused this issue, but if this problem ever resurfaces we can revisit it then.

**Comment by l-gthb** [comment]
hi, i'm having this problem with Tomb Raider II, using retroarch runner in lutris on fedora rawhide.
