### ISSUE TITLE
Can't launch "Square's Preview 5"

### ISSUE THREAD

**Issue by Electricstar** [libretro/beetle-psx-libretro#493]
The title should say it all, I can't launch Square's Preview 5, a demo disc containing demos of various Squaresoft games, in Beetle PSX.
If trying to launch it through the .cue file like any other PSX game, it comes up with an error saying it failed to load content. Trying to launch it through a .m3u file brings you to the PSX startup screen followed by the main menu as if a disc wasn't inserted (Black screen if "Skip BIOS" is on.

I made sure I had everything I needed, and sure enough, I did. I had scph5500.BIN, since it's a japanese-exclusive demo disc.

I'm mainly trying to get this demo disc to boot, as it has a demo for a beta version of Chrono Cross, which has me interested. Any reason this demo disc doesn't boot?

**Comment by hizzlekizzle** [comment]
Dunno, we'd need a log to even guess.

**Comment by Electricstar** [comment]
[retroarch-log.txt](https://github.com/libretro/beetle-psx-libretro/files/2949064/retroarch-log.txt)
The log.

**Comment by hizzlekizzle** [comment]
```
[libretro ERROR] Error opening file:
C:\Users\zack_\Desktop\Emulators\PSX (Games Only)\Square's Preview 5 (J) [SLPS-02171].bin
No such file or directory
```
Looks like a malformed cue file, based on the error.

**Comment by Electricstar** [comment]
That exact line had me suspicious, so I renamed the bin file I had as well.
Previously it was "Square's Preview 5 (Japan).bin". Then I changed it to what was shown in that log,
"Square's Preview 5 (J) [SLPS-02171],bin". To say the least, renaming the .bin file actually worked, and it loaded perfectly fine.
