### ISSUE TITLE
Beetle PSX Hardware Rendering Stretches Video Which Breaks Interlacing

### ISSUE THREAD

**Issue by xchimp** [libretro/beetle-psx-libretro#495]
## Description

When using hardware rendering, the screen stretches and breaks an interlacing shader when using a CRT monitor at 3840x480.

### Expected behavior

The video to be it's proper aspect ratio depending on the game.
![software](https://user-images.githubusercontent.com/31327707/54671246-8875a400-4ac3-11e9-9fec-9fd2b3c96add.jpg)

### Actual behavior

The video is being stretched, creating excessive black bars.
![hardware](https://user-images.githubusercontent.com/31327707/54671495-0c2f9080-4ac4-11e9-977b-5a9b1c310958.jpg)

### Steps to reproduce the bug

1. Set renderer to hardware
2. Enable interlacing shader

### Version/Commit

- Beetle PSX: 0.9.44.1 5359198

### Core options
Renderer = hardware

### Environment information

- OS: Windows 10 x64
- GPU: R9 380 4GB | Driver version: 19.3.1

**Comment by hizzlekizzle** [comment]
Does it act any better with the software renderer? Do you have integer scaling enabled?

**Comment by xchimp** [comment]
Yes, the expected behavior is a picture of it running in software mode, I should have clarified. Yes, it's enabled, disabling it doesn't fix it.

**Comment by hizzlekizzle** [comment]
Are you increasing the internal resolution? If so, I believe this is acting as expected if not as intended/hoped. That is, if you increase the internal resolution to be larger than the actual screen/res, RetroArch will downsample it to fit the screen, which does not take integer scaling into account.

I think if you enable super sampling in the Vulkan renderer, it should allow you to increase the internal res while maintaining the proper integer scaling.

**Comment by xchimp** [comment]
No, I'm running it at the native internal resolution, and the screen remains stretched no matter what I set the internal resolution to if using hardware rendering.

Where can I find that option to try it?

**Comment by hizzlekizzle** [comment]
Ok, yeah, looks like it is indeed being weird. I'm able to reproduce the same behavior with no good explanation or solution.

**Comment by xchimp** [comment]
That's good to know it's not only on my end then at least.

**Comment by Silanda** [comment]
I just tried playing D no Shokutaku - Complete Graphics, and ran into the same thing. Everything is fine when using the software core, however, in the hardware one the videos, which are mainly widescreen, are stretched to fill a 4:3 frame. I get the impression that the hardware core is stretching everything to 4:3 one way or another, irrespective of the selected internal resolution (it's almost like "crop overscan" is always turned on, even when it isn't) .

**Comment by rz5** [comment]
Feels like it's related to #510

**Comment by ggdrt** [comment]
@xchimp Can you confirm if this is working properly for you now with the GL hardware renderer on the latest build?

**Comment by xchimp** [comment]
@ggdrt Can confirm that it seems to be fixed as of the latest build. Thanks!

**Comment by ggdrt** [comment]
@xchimp This is now fixed for the Vulkan renderer as well of the latest build (3215862). Thanks for your patience.

**Comment by xchimp** [comment]
@ggdrt Unless that has already been implemented, it appears to still be happening when using Vulkan.

**Comment by ggdrt** [comment]
The latest build is not yet available through the online updater. It should be available sometime within the next day or so.

**Comment by ggdrt** [comment]
I forgot to mention that the latest build is not yet available through RetroArch's online updater. It should be available sometime within the day.

**Comment by xchimp** [comment]
@ggdrt Ah, my mistake. I just updated to check if it works and can confirm that it does. Thanks for your work to get this fixed.
