### ISSUE TITLE
Beetle PSX HW - Android 64bit - SnapDragon 845 performance

### ISSUE THREAD

**Issue by kikeminchas** [libretro/beetle-psx-libretro#496]
## Description
Comparing performance of a Xiaomi Pocophone (SD845) and a Shield TV. The Shield TV can go up until 4X resolution and be full speed. This is using Vulkan, no Software Framebuffer, Frame Duping on, all the rest default.

With the Pocophone I can only get full speed at 1x and 2x. Both the Shield and the phone have the same core version : Beetle PSX 0.9.44.1 5359198

In the phone as core options, I am using Hardware rendering and everything else default. I tried both Vulkan and OpenGL. I tried frame duping, no real difference. I have tried Sustained Performance mode in RA and the different game booster modes of the phone… no difference, only full speed at 1X and 2X resolution. This is what I don’t get so good also, if I’m able to reach 1x and I am using Hardware rendering, reaching 4X at full speed should not be such an issue, right? 

### Expected behavior
Phone should be capable of increasing internal resolution if compared to Shield TV, especially being full speed at 1x.

### Actual behavior
I used Crash Bandicoot as testing game in both phone and Shield TV. These are some results on the phone:

Title screen:

Beetle PSX HW (Hardware rendering): 1x/2x: Full Speed  / 4x IR: 35fps

Beetle PSX HW (Software rendering): 1x: Full Speed / 4x IR: 35fps

I also downloaded Beetle PSX (the no HW version) just in case: Beetle PSX: 1x: Full Speed /  4xIR: 35fps

All versions and options are full speed at 1x in game also (at least first stage). Results are pretty much identical with software/hardware rendering option. Again, NVIDIA Shield TV is happy at 4X with Beetle PSX HW and Vulkan. Is it possible the core is not using Hardware rendering at all?

### Version/Commit
Beetle PSX 0.9.44.1 5359198

### Core options
All default but
- Frame Duping ON
- No Software Framebuffer

### Environment information

- OS: Android 9.0 Pie
- GPU: SD 645 (Adreno 630)

*EDIT: I have modified the issue to reflect that the core is able to reach full speed at 2X with HW rendering (with room to spare, fast forwarding in title screen makes it go until 80fps). 2X is even full speed with PGXP (memory only) and Perspective correction ON. In this case, fps in fast forward in menu screen go down to 70. As soon as 4X IR is selected, fps go down to 35-40. Is the GPU becoming a bottleneck, shoudl be more powerful that the X1 in the Shield? Drivers maybe? Not sure how much the performance at this point depends on the core itself or possible software issues with the Adreno 630 implementation in the phone.

**Comment by rz5** [comment]
@kikeminchas - I've been told the Pocophone suffers from thermal throttling. So if you're expecting higher perf from the Adreno 630 as opposed to the Tegra X1's GPU, it might have to do with the Pocophone having the typical thermal/power constraints of a smartphone.

**Comment by fr500** [comment]
Most definitely, even if the SoC is faster, in a phone enclosure it's only gonna be faster for a few minutes :)

**Comment by kikeminchas** [comment]
The Pocophone is advertised as precisely quite resistant to thermal throttling... I have tried to save a state in the menu in the game i use for testing, go out of the core, let phone rest for a while, load core and immediately savestate. FPS go down to 35 straight away, in a matter of 2 secs. Then again , maybe some core activity is forcing the SoC to throttle immediately... I don't know, just find it weird... In Mupen64, I can just set IR to 1080p, fast forward and let the core run at 100-120fps for 10 minutes, no throttle.... Oh well...

**Comment by rz5** [comment]
@kikeminchas That advertisement bit is interesting because it's the opposite of what flyinghead over on the libretro Discord said as he was testing reicast's arm64 dynarec.

For shits and giggles, try strapping an ice cube tray to the back of your phone and see if beetle-psx-hw reaches maintains fullspeed at 4x upscaling.

**Comment by kikeminchas** [comment]
:D :D to mantain full speed at 4x would mean that it has reached that speed, even if for a couple of seconds.... Curious that you mention flyinghead, I was playing yesterday Virtua Tennis in reicast, no issues for the 15 minutes or so of the session... It was the 32bit version, mind you... I will try tomorrow the 64bit just out of curiosity
