### ISSUE TITLE
[Bettle PSX HW] Dino Crisis 2 (USA) GL Driver Issues on Menu and Cutscenes

### ISSUE THREAD

**Issue by detectorcaleta1** [libretro/beetle-psx-libretro#498]

**Comment by elgatov** [comment]
![image](https://user-images.githubusercontent.com/11425591/56083549-b3cf8280-5e26-11e9-8e29-b91fd2abc39a.png)

> Beetle PSX HW 0.9.44.1 5359198

![image](https://user-images.githubusercontent.com/11425591/56083546-aca87480-5e26-11e9-9142-061e898e9c32.png)

Works well in my end

**Comment by detectorcaleta1** [comment]
I am sorry, I did a mistake before, I updated my comment and attached pictures of the problem using video driver GL. On VULKAN no issues found.

**Comment by detectorcaleta1** [comment]
Sorry to bother you guys, please fix this issue, I am still experiencing it using GL Video Driver, I don't see more comments regarding this issue. Thanks you.

**Comment by detectorcaleta1** [comment]
Re-uploaded issue.
