### ISSUE TITLE
Not reporting correct resolution to RetroArch

### ISSUE THREAD

**Issue by bugreport1** [libretro/beetle-psx-libretro#5]
PSX games seem to only report a resolution of 320x240 to RetroArch, resulting in ugly graphics when using integer scaling if that game does not run at 320x240. (e.g. Symphony of the Night, which is natively 256x240)

**Comment by bugreport1** [comment]
After doing further testing I have to set the scale to 7x8 in RetroArch (too large for a 1080p screen) for the 16x16 tiles used in the backgrounds of Symphony of the Night to be displayed correctly.
 
At this scale, they are displayed as 128x128. Anything less than 7x8 displays artifacts from being improperly scaled.
 
Ideally the PSX core would output the correct resolution and I would be able to use something like a 5x5 scale, which would fit on a 1080p screen, and display these tiles as 80x80.

**Comment by rz5** [comment]
@bugreport1 - Check if you still have ugly graphics using integer scaling, specifically with the GL renderer.

**Comment by ggdrt** [comment]
256x240 is certainly the size of the display area used by Symphony of the Night during gameplay, but 16:15 is not the correct aspect ratio for the display area. Accurate aspect ratio correction will result in non-integer scaling along the horizontal axis. 

Aspect ratio correction can be disabled as of 04daeef, allowing for an incorrect aspect ratio but likely cleaner integer scaling.
