### ISSUE TITLE
[GL] [Windows] Black Screen [Cause : CG Shaders]

### ISSUE THREAD

**Issue by stevenstrike** [libretro/beetle-psx-libretro#50]
Tested on **Windows 10 x64** with **Radeon 7950** Radeon Software Version 16.5.3 (OpenGL 4.5 Context) and latest RA x64 and mednafen HW builds. 

When starting a game using opengl backend (everything else is set to default) : screen goes black but the game still run. 
Attempting to go back to RA (meaning using F1 or L3+R3), immediately close retroarch.

Debug doesn't provide much info : 
*snip*
OpenGL context reset
Building OpenGL state (1x internal res., 16bpp)
Target framebuffer size: 1024x512
Target framebuffer size: 256x240
Target framebuffer size: 640x240
Target framebuffer size: 256x240
Target framebuffer size: 640x480

**Comment by stevenstrike** [comment]
Found the culprit !
DIsabling Shaders is the only way to make it works
video_shader_enable = "false"

**Comment by rz5** [comment]
@stevenstrike Try using GLSL shaders instead of CG shaders.

**Comment by stevenstrike** [comment]
@rz5 Got it working using GLSL.

**Comment by twinaphex** [comment]
Cannot be helped, the GL renderer right now requires 3.3 core context and Cg doesn't work with that.

Cg is dead for anybody but nvidia's partners for which they still provide support. To the public it's essentially dead and buried.

**Comment by stevenstrike** [comment]
@twinaphex "Cg is dead for anybody (...)"
That's weird because on libretro.com everyone says that CG should be used instead of GLSL.

Anyway i'm glad to drop CG
