### ISSUE TITLE
[Beetle PSX HW] Android core is not actually HW but regular version

### ISSUE THREAD

**Issue by shlomi-toren-sp** [libretro/beetle-psx-libretro#507]
## Description

When you update the HW core via online updater on android, on either version of RA, the downloaded core is actually the normal version. It uses uses the same configuration and saves to the same directories as the normal version, even though the PC port uses other directories and is completely separate.

### Expected behavior

When loading the core, I expect it to say "Beetle PSX HW 0.99[whatever]".
Also, the config should be different than the normal version and saves should go to the "Beetle PSX HW" folders under saves and states.

### Actual behavior

The core appears identical to the normal, non HW version.

### Environment information

I'm using Samsung Galaxy Note 9, but I don't think it's relevant.

NOTE: This may not be relevant to this github. If it isn't, I would appreciate someone pointing me in the right direction. As far as I know, the RA buildbot doesn't have an address for such things.

**Comment by rz5** [comment]
@shlomi-toren-sp Is it still happening for you? Have you tried updating your Core Info Files before downloading the HW core?

I just took a peek at the buildbot recipe line which compiles beetle-psx-hw (https://github.com/libretro/libretro-super/blob/master/recipes/android/cores-android-jni#L48)

HAVE_HW is correctly set to 1, so it should just all work. If this still persists, I'll go wave my fist at the other devs for you.

**Comment by shlomi-toren-sp** [comment]
@rz5 yes, I tested it just now. Updated the core info files first, then the core itself, still the same.
For what it's worth, I've tried deleting the core and re-downloading, and I also tried editing the config so that the core is downloaded from other versions of the nightly android build (obviously the core doesn't work unless it's the correct build, but still worth a shot).
The name of the zip, as well as the core file itself have "hw" in them, but I guess that isn't enough.

I'd appreciate you contacting the devs. Thank you!

**Comment by orbea** [comment]
@rz5 I suspect this is because the jni makefile doesn't conditionally set the `TARGET_NAME` like the regular Makefile.
```
ifeq ($(SET_HAVE_HW), 1)
   FLAGS += -DHAVE_HW
   TARGET_NAME := mednafen_psx_hw
endif
```
I'm not quite sure how to hook this up though with jni, do you know?

**Comment by rz5** [comment]
@orbea - Thank for chiming in. I'm not sure if that's needed or not. I admit I'm not familiar with jni.

I suspect that what you're suggesting is not required due to how the buildbot workflow goes. Specifically, for cores built with ndk, you add a line in recipes/android/cores-android-jni (https://github.com/libretro/libretro-super/blob/master/recipes/android/cores-android-jni#L48).

The first string in a recipe line is the core's name, that's documented in this bash function: https://github.com/libretro/libretro-super/blob/master/libretro-build-android-mk.sh#L42-L62

I think all the pieces are there. If anything HAVE_HW=1 is being ignored...

**Comment by rz5** [comment]
@shlomi-toren-sp - Ok, the latest change should fix this. Give it half a day and please re-download the HW core.

The litmus test is if you see the PGXP and overclock options as new core options.

**Comment by orbea** [comment]
Linking the commit for reference.

https://github.com/libretro/beetle-psx-libretro/blob/7da4800b8d8a3b79c2c68a80fe5a41148f710d5d/jni/Android.mk

Good catch!

**Comment by shlomi-toren-sp** [comment]
@rz5 @orbea this very second, things look to be the same.
I'll keep testing throughout the day. Thanks regardless!

By the way: the PGXP options were always there. The issue is that I don't think the "hardware" options are taken into account, and also that the core doesn't appear to be separate from the regular core at all (meaning that saves for example are saved to the same"Bettle PSX" directory, and not the the "Bettle PSX HW folder like on PC).

**Comment by kikeminchas** [comment]
well, now I know why I lost my core config when core got updated this morning :) Seriously now, the performance of this core on Android is greatly dependent on GPU/Drivers.... It runs at 4x in my Nvidia Shield but only at 2x in my phone with Snapdragon 845 while in theory, the Adreno GPU in the phone is more powerful than the Shield....

**Comment by shlomi-toren-sp** [comment]
@kikeminchas glad to see it happening to someone else, I though I was going crazy.
Still, it appears @rz5 and @orbea found the issue and are kind enough to look into it.

Yeah, it worked great on my previous phone too, but I guess every phone is different. 
Currently I'm getting 50fps on 1x, and any change to the graphics settings seem to mess up the textures entirely. Not sure what's going on with that.

**Comment by rz5** [comment]
@kikeminchas - Can confirm that, by updating the HW core, you can now select 'hardware' as the renderer and see PGXP options? Also, remember to set RA's video driver to 'vulkan' if you phone can handle it. The GL renderer is disabled because the core won't compile otherwise.

@shlomi-toren-sp Same thing for you, set RA's video driver set to 'vulkan', set beetle-psx's renderer to 'hardware' and upscale it to 4x. If you leave RA's video driver to any other option, you'll be using the software renderer and you won't receive the benefit of having GPU accelerated upscaling.

The reason behind this issue was because, unlike on non-Android systems, the build system was not telling the compiler to include the HW version's features.

Don't forget to close the issue if it's working.

**Comment by kikeminchas** [comment]
@rz5 , I could select both Hardware and PGXP options also before this change. This change only seem to have affected the name the core displays and the related folders/config file (this means when user updates their saved core config, if any, it will be gone, that's how I came here :) ). I can also confirm I am using Vulkan. I can only reach fullspeed at 2x (and then not in all games), got a SnapDragon 845 so it doesn't get much better than this in terms of CPU/GPU...

**Comment by shlomi-toren-sp** [comment]
@rz5 My MAN! The core's name has changed now to "Beetle PSX HW", meaning the folders and configs are now correct. What @kikeminchas said is true, that the config is reset, but that's an easy thing to do again. Thank you so much!

On the performance side, basically, You're saying I need to have the HW core set to Vulkan and 4x in order for it to actually use the GPU?
I tested it now, and even with Vulkan and 4X, I'm getting 40fps and weird graphics, seen here:
![2](https://user-images.githubusercontent.com/27414398/58854104-0732b400-86a5-11e9-9aef-705fce7386f9.jpg)
![1](https://user-images.githubusercontent.com/27414398/58854106-0732b400-86a5-11e9-8963-90d70c9a9948.jpg)

If I need to change any other settings, or even open a new issue for this here, let me know.
Regardless, thanks again for your help, much appreciated.

**Comment by kikeminchas** [comment]
Not sure this is relevant to this bug anymore but try disabling software framebuffer for a speed up. Still, you're not going to get 60 fps in most games, not even close in some. I also have a phone with a SnapDragon 845... a pity but at the moment that is the situation...even at 2X some games like Gran Turismo are not consistent 60fps

**Comment by shlomi-toren-sp** [comment]
@kikeminchas tried that, no effect really.
It's a shame. Mine doesn't even have the SD, it's the Exynos model.

Still, pcsx for example seems work fine on 1x (no other option), so I'll even take that in Beetle HW, but that doesn't seem to achieve 60fps either.

**Comment by rz5** [comment]
Alright so the reported issue is fixed, good.

Like kikeminchas said, if you can't get fullspeed at 4x upscaling, drop it down till you can. If you still can't get stable framerates...well, you're out of luck. Frame duping and disabling the 'software fb' option will give you a very small perf increase.

The hardware renderer is only really faster at upscaling graphics. At 1x, it shouldn't be any faster versus the software renderer. 
For a true boost in performance, we need a dynarec like in pcsx-reARMed. If you got friends with experience in dynamic recompilation of MIPS to ARM/x86, tell them there's a 900$ bounty on the table if they can develop something for this core.

As for your graphics issues in THPS2, maybe open an issue if you can't get it fixed, maybe it's a bad dump, who knows.

**Comment by kikeminchas** [comment]
Last comment: pcsx rearmed has an enhanced resolution option that AFAIK, is equivalent to 2x. Use that instead of this core;

**Comment by shlomi-toren-sp** [comment]
@rz5 ok, thank you!

**Comment by rz5** [comment]
Reopening this because https://github.com/libretro/beetle-psx-libretro/commit/3930fdd8c706526629d4f24fd2a1029b25711a18 reverted the fix.

**Comment by shlomi-toren-sp** [comment]
@rz5 oh no! That literally only ruins what you've done!

@twinaphex Can we start a discussion?

**Comment by hizzlekizzle** [comment]
It's back in. TA already re-added it. Closing.

**Comment by gregoricavichioli** [comment]
This issue seems to be back. Both the regular and HW core options listed in the online updater download the regular version.

This happens on Android 12, Retroarch 1.10.3. There's only a _Beetle PSX_ config directory and the core options menu doesn't contain options for renderer, adaptive smoothing and supersampling, for example. The version displayed has 'HW' missing too.
