### ISSUE TITLE
Beetle HW: Chrono Cross soundtrack does not sound right

### ISSUE THREAD

**Issue by efdevelopersp** [libretro/beetle-psx-libretro#508]
On the first mission where you are in the tower it is very noticable that the song that is playing is missing some sound effects at the end of the song before the loop which should be an "uhhhh vishhh uhh ha, uhhh vish uhh ha" noise and this is not there.

Another issue is the echo / reverb used in this game which it seems that is not emulated as well.

In short, this issue is about some instruments and the echo / reverb that are not emulated.

**Comment by rz5** [comment]
@efdevelopersp - Is this exclusive to the HW version? Further, have you checked if this also happens in the latest standalone mednafen release?

**Comment by efdevelopersp** [comment]
@rz5 No, this happens on the regular version too. I haven't tried on the standalone release though, i'll check it out tonight and let you know.

I forgot to mention that i run this game on Retroarch Mac OSX port but i didn't know if this is relevant for this issue or not.

**Comment by efdevelopersp** [comment]
Never mind. It was caused by the audio configuration on the retroarch.
