### ISSUE TITLE
Beetle PSX HW - can't compile with hardware rendering support in MinGW Windows

### ISSUE THREAD

**Issue by ofry** [libretro/beetle-psx-libretro#512]
# First and foremost consider this:
- This is a DEVELOPER oriented channel dedicated to report bugs and suggest features about the libretro core, please do not ask for help;
- The upstream bug tracker is a forum thread, located at https://forum.fobby.net/index.php?t=msg&th=1114;
    - Note: As of October 2018, Microsoft email providers (think email addresses ending with hotmail/live/outlook) are rejecting email from the forum. If you want to register an account in the upstream project's forum, consider using another mail provider.
- For game-related bugs:
    1) First, check if it's already reported on the upstream bug tracker;
    2) If it's not reported there, try to reproduce the bug with mednafen;
    3) If it's reproducible with mednafen, report it on the upstream bugtracker;
    4) If it's not reproducible with mednafen, ONLY THEN should you report it here.
    
## Description

Beetle PSX HW - can't compile w/ hardware rendering

### Expected behavior

Compilation should be successful.

### Actual behavior

```
ofry@games MINGW64 ~/beetle-psx-libretro
$ git reset --hard
HEAD сейчас на aae54be Hide HW options in non-HW core

ofry@games MINGW64 ~/beetle-psx-libretro
$ make clean && make HAVE_HW=1
rm -f *.o
rm -f *.d
rm -f mednafen_psx_libretro.dll
make: *** Нет правила для сборки цели «libretro.h», требуемой для «rsx/rsx_lib_gl.o».  Останов.

```

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
[If you're using RetroArch, after the core has started, this information is on the bottom left]

- Beetle PSX: aae54be

### Core options
[List all the core options you have changed]

### Environment information

- OS: Windows 8.1 Enterprise x64
- Compiler: MSYS2/MINGW toolchain
- GPU: [Graphics card and driver version, if you're using the HW version]

**Comment by ofry** [comment]
```
$ make -v
GNU Make 4.2.1
Эта программа собрана для x86_64-pc-msys
Copyright (C) 1988-2016 Free Software Foundation, Inc.
Лицензия GPLv3+: GNU GPL версии 3 или новее <http://gnu.org/licenses/gpl.html>
Это свободное программное обеспечение: вы можете свободно изменять его и
распространять. НЕТ НИКАКИХ ГАРАНТИЙ вне пределов, допустимых законом.
```

**Comment by rz5** [comment]
@ofry - try ```git checkout * && make clean && make -j4 HAVE_HW=1```

**Comment by ofry** [comment]
Thanks, I found some trash in my working folder.

```
ofry@games MINGW64 ~/beetle-psx-libretro
$ git clean -d -f -x
Удаление libkirk/
Удаление libretro-common/file/
Удаление libretro-common/glsm/glsm.d
Удаление libretro-common/glsm/glsm.o
Удаление libretro-common/glsym/glsym_gl.d
Удаление libretro-common/glsym/glsym_gl.o
Удаление libretro-common/glsym/rglgen.d
Удаление libretro-common/glsym/rglgen.o
Удаление mednafen/cdrom/SimpleFIFO.o
Удаление mednafen/file.d
Удаление mednafen/file.o
Удаление mednafen/psx/dis.o
Удаление mednafen/trio/
Удаление mednafen_psx_hw_libretro.dll
Удаление rsx/gl/
Удаление rsx/rsx_lib_gl.d
Удаление rsx/rsx_lib_gl.o
Удаление rustation-libretro/
```

Then all work fine.
