### ISSUE TITLE
The Adventure of Little Ralph sync issues

### ISSUE THREAD

**Issue by TesterNes** [libretro/beetle-psx-libretro#514]
The adventure of little ralph running on beetle psx (software) presents tearing on the top of the screen during side scrolling.
This issue doesn't happen in Hardware mode/core.
 
Retroarch 1.7.7 windows 7 64bits.
core: Beetle psx 0.9.44.1 432feab  

maybe related to #340

**Comment by DukeJP** [comment]
https://forums.libretro.com/t/tearing-in-beetle-psx-software/16433/6
they insist that it is the right behavior.

**Comment by rz5** [comment]
If it happens in real hardware, it's not a bug.

**Comment by TesterNes** [comment]
Yeah, I've tested out in real hardware today and happen the same thing.
