### ISSUE TITLE
RPG Tsukuru 4 - Music plays too fast

### ISSUE THREAD

**Issue by Oggom** [libretro/beetle-psx-libretro#52]
The music in RPG Tsukuru 4 plays faster than intended. This was fixed in Mednafen 0.9.38.7.

**Comment by personaone** [comment]
Interesting, I thought this core is synced with the latest Mednafen release?

**Comment by Oggom** [comment]
@personaone It is not, it's based on 0.9.36.5-ish with some selected backports.

See also https://github.com/libretro/beetle-psx-libretro/issues/12

**Comment by personaone** [comment]
Hm, this could have something to do with the FF8 i've reported: #39

**Comment by twinaphex** [comment]
Most of the really significant things have all been backported.

The few that remain, feel free to help out with the backporting process. At this stage the Beetle PSX has enough on its own to recommend itself. Anything it lacks can easily be backported over.

If upstream had been more conducive for libretro-ization, the hard break would have never been necessary. But at the same time, I don't want to introduce a C++11 compiler requirement either that Ryphecha has imposed upon the codebase, so as long as there won't be a compromise in upstream to address these two very important issues, it will remain a hard fork.

**Comment by twinaphex** [comment]
On that note, check out the #if 0 portions in mednafen/psx/gpu.cpp. I could never figure out how to get the GPU texture cache emulation to work which is supposed to replace the old texwindow code. If/when we do change this code though, the GL renderer code should also have to be changed in light of it, so it might not be a trivial change.

**Comment by OptimalJew** [comment]
Updating this on request about backporting the fixed timer emulation code:
https://mednafen.github.io/documentation/ChangeLog.txt
![changelog](https://user-images.githubusercontent.com/31424143/31398860-59a1769e-adb8-11e7-92a2-7a100fd9ee67.png)
The game itself is dumped as RPG Tkool 4. http://redump.org/disc/4056/

**Comment by rz5** [comment]
@Oggom @OptimalJew - Once the buildbot is done building (or if you can build form source), could you please test if this bug still happens?

**Comment by Oggom** [comment]
@r5 I just checked it and the music is now playing at the correct speed. Thank you 👍

**Comment by OptimalJew** [comment]
@rz5 
Before: https://my.mixtape.moe/gujprv.webm
After: https://my.mixtape.moe/aqbyil.webm
Standalone: https://my.mixtape.moe/iiclzk.webm

I think you did it. Great job.
