### ISSUE TITLE
Failed to load content... while trying to open a CHD file

### ISSUE THREAD

**Issue by MarcoEstevez** [libretro/beetle-psx-libretro#521]
## Unable to load any CDHs compressed media

I did update the core recently and noticed no CHDs files are able to boot.

### Steps to reproduce the bug

1. Take any game, for instance bin/cue and convert it to CHD
2. Load resulted CHD

### Version/Commit
Not exactly sure, but few weeks ago was working just fine until today when I updated retroarch and this core.

### Environment information
- OS: Windows 10 (x64) (using last retroarch available and latest beetle-core version)

**Comment by MarcoEstevez** [comment]
mednafen_psx_hw_libretro and mednafen_psx_libretro cores both fail loading CHD content, however I downloaded pcsx_rearmed_libretro core and this one works just fine.

**Comment by CorruptAlpha** [comment]
I am also facing this issue with any CHD I try to load. I have seen this issue recently and I'm not sure what version or commit caused it; I am also using Windows 10 x64 with RetroArch 1.7.7 and the latest mednafen_psx_hw_libretro core.

**Comment by TriumphantD** [comment]
I am having the same issue. I updated to Retroarch 1.7.7 and downloaded the latest Beetle-psx core. I am now unable to load CHD files that previously worked. If I uncompress the CHD files back into bin/cue they work fine, but recompressing then to CHD again fails to load.

The log file shows:

[libretro ERROR] Unknown CUE sheet directive "MCOMPRHD".
[libretro ERROR] TOC first(99)/last(98) track numbers bad.
terminate called after throwing an instance of 'MDFN_Error'

**Comment by tiltowait** [comment]
Same issue here with similar error messages to @TriumphantD. The game in question (Intelligent Qube) works just fine as a CUE/BIN. I'm using Beetle PSX 0.9.44.1 a264b2b (same crash on the HW version) and chdman from mame0211b_64bit.

**Comment by sephore** [comment]
It seems buildbot cores from 2019-07-14 and before are working (those are also a bit larger).

**Comment by tiltowait** [comment]
@sephore Would you happen to have a link? I checked [this page](http://buildbot.libretro.com/nightly/windows/x86_64/2019-07-14_cores/), but the directory is empty (as are all the other `_cores` directories).

**Comment by MarcoEstevez** [comment]
Pinging @bparker06 any Idea what might have caused the issue?

**Comment by bparker06** [comment]
No idea... I would suggest someone do a bisect to figure out when this broke though.

**Comment by tiltowait** [comment]
@bparker06 First bad commit is 214e0bd1bee35fb43bba83420bc84177dc2207bb.

**Comment by bparker06** [comment]
So it was simply disabled? That would explain it.

**Comment by twinaphex** [comment]
My bad guys for wasting your time, was just one of those days I guess. 

Pushed the change and all should be good again.

**Comment by tiltowait** [comment]
Yeah ... I only read the commit after commenting, heh.

**Comment by Yevenergy** [comment]
For RetroArch, it’s important to have a correct Sega CD BIOS, which should be located in the root of the "system" folder at the directory "C:\RetroArch-Win64\system". The BIOS file names must strictly be in the format: bios_CD_U.bin, bios_CD_E.bin, bios_CD_J.bin.

**Comment by Yevenergy** [comment]
For example, for RetroArch, it’s important to have a correct Sega CD BIOS, which should be located in the root of the "system" folder at the directory "C:\RetroArch-Win64\system". The BIOS file names must strictly be in the format: bios_CD_U.bin, bios_CD_E.bin, bios_CD_J.bin. It’s possible that your emulator requires a similar setup.
