### ISSUE TITLE
Odd geometry behavior between SW & HW renderer on games with built in letterboxing

### ISSUE THREAD

**Issue by klepp0906** [libretro/beetle-psx-libretro#525]
# First and foremost consider this:
- This is a DEVELOPER oriented channel dedicated to report bugs and suggest features about the libretro core, please do not ask for help;
- The upstream bug tracker is a forum thread, located at https://forum.fobby.net/index.php?t=msg&th=1114;
    - Note: As of October 2018, Microsoft email providers (think email addresses ending with hotmail/live/outlook) are rejecting email from the forum. If you want to register an account in the upstream project's forum, consider using another mail provider.
- For game-related bugs:
    1) First, check if it's already reported on the upstream bug tracker;
    2) If it's not reported there, try to reproduce the bug with mednafen;
    3) If it's reproducible with mednafen, report it on the upstream bugtracker;
    4) If it's not reproducible with mednafen, ONLY THEN should you report it here.
    
## Description
Games that have letterboxing across seem to function properly in the SW core, however in the HW core, it seems it only letterboxes the top - and leaves the bottom untouched. 

Here are two shots of a game that doesnt have letterboxing with identical settings.

SW renderer - https://www.dropbox.com/s/41wvpwgkg9187tr/sw.jpg?dl=0
HW renderer - https://www.dropbox.com/s/3zvz3oo5ih4odds/hw.jpg?dl=0

Result is identical.

Here are two shots of a game that does have built-in letterboxing for lack of a better word.  Identical settings to the above game/shots, and to eacthother.

SW renderer -  https://www.dropbox.com/s/8lieoyxypepx196/sw2.jpg?dl=0
HW renderer - https://www.dropbox.com/s/tooa4dl4ogxqa0w/hw2.jpg?dl=0

May be hard to see with the scaled down images, but notice how the SW renderer has both "letterboxes" and theyre straight across (barring the slight curve from the shader).

The HW renderer seems to be skipping the bottom black bar alltogether, and leaving the default curvature+corner behavior from non letterboxed games, while treating the top as expected.

### Expected behavior

For the HW renderer to behave like the SW renderer - and for the bottom letterbox to be cut off like the top.   Even if i were to reposition the Y axis upward, the geometry of the top and the bottom would be different.  (not to mention the loss of convenience by being able to potentially use either renderer without major adjustments to viewport).

### Steps to reproduce the bug

1. Applying an overlay may be helpful for position relative to the space. 
2. load a game with letterboxing and a crt shader of your choice.  (i tried several)
3. swap between HW and SW renderer without changing any of the video settings (using custom AR) and note the discrepancy. 

### Version/Commit
[If you're using RetroArch, after the core has started, this information is on the bottom left]

- Beetle PSX: 0.9.44.1 9d8961a

### Core options
The aforementioned screenshots were taken with defaults core-option wise.  I did try cropping options on/off but the result was the same.

### Environment information

- OS:  Windows 10
- Compiler: [In case you are running local builds]
- GPU: 2080ti 431.36

**Comment by hizzlekizzle** [comment]
Possibly related issues:
https://github.com/libretro/beetle-psx-libretro/issues/495
https://github.com/libretro/beetle-psx-libretro/issues/510

**Comment by klepp0906** [comment]
so ftr after mucking with this a bit more, im unsure if the game has built in letterboxing - or its simply something beetle SW is doing to it.  Someone much more familiar with psx games needs to comment.

for example.  wild arms as shown above will lop off top and bottom in SW, and only top in HW.  However xenogears logs off top and bottom in SW, but neither in HW, fills the entire screen as youd expect.

Unsure which is the intended behavior, but that and the positioning discrepancy between the renderers makes it hard to set up a viewport between games.

**Comment by ggdrt** [comment]
Issue is related to #510 in that it's a product of the hardware renderer not respecting how VRAM framebuffers are encoded into 240p analog format. The software renderer has correct behavior here.

If you take a look at the VRAM for Wild Arms, each of the two 320x232 framebuffers (I've outlined these in red) have 8 lines of entirely black pixels at the top. (Don't mind the exact number of pixels you see in the screenshot, there's some minor downscaling in the image)

![Image](https://i.imgur.com/u6jkudn.png)

What should be happening is that an extra 8 lines of black pixels are filled in at the bottom during analog encoding to create a full 240p signal, which is what the software renderer emulates properly. The hardware renderer seems to just take the VRAM framebuffer and incorrectly scale it directly to 4:3, which is why you're not seeing a black bar on the bottom of your HW renderer image.

![Image](https://i.imgur.com/TVJyFtp.png)

You don't see any black bars in Ridge Racer because the framebuffers are 320x240 and properly match the 240p output resolution.

**Comment by klepp0906** [comment]
well, that explains that thoroughly then.  The struggle continues, HW rendered IQ or SW rendered accuracy ;p

Thank you for laying that out.

**Comment by ggdrt** [comment]
@klepp0906 Can you confirm if this issue is fixed for the GL renderer on the latest build (a82b3a7) with the shader you were using?

**Comment by klepp0906** [comment]
yep, give me a few and ill take a look and post back.  working my way towards video game time as fast as i can.  you can count on that ;p

**Comment by klepp0906** [comment]
peeled away and checked RQ.   looks good :)  thank you!

**Comment by klepp0906** [comment]
seems still needs fixin on vulkan though?

**Comment by ggdrt** [comment]
Right, still needs to be implemented for Vulkan.

**Comment by ggdrt** [comment]
@klepp0906 Issue should now be fixed on the Vulkan renderer as of latest build (3215862). Thanks for your patience.

**Comment by klepp0906** [comment]
excellent. thank you for your work :)
