### ISSUE TITLE
Most filters under Vulkan cause GFX problems [Nvidia RTX only]

### ISSUE THREAD

**Issue by backgamon** [libretro/beetle-psx-libretro#527]
### Description
Using xBR, SABR and 3-Point cause bad GFX , under Bilinear, JINC2 and Nearest no problems at all.
Just choose xBR, SABR and 3-Point with Vulkan render.
Many games (as i checked are impacted):

* Gex enter The Gecko

* Gex Deep Cover The Gecko (for the most visible issues)
xBR:
![Screenshot - 10_08_2019 , 09_57_57](https://user-images.githubusercontent.com/39404647/62819614-e03aa780-bb57-11e9-9060-b7d566372ba1.jpg)
Nearest:
![Screenshot - 10_08_2019 , 09_58_25](https://user-images.githubusercontent.com/39404647/62819617-ecbf0000-bb57-11e9-84c1-ba1796322094.jpg)
JINC2:
![Screenshot - 10_08_2019 , 09_58_40](https://user-images.githubusercontent.com/39404647/62819621-f5afd180-bb57-11e9-8047-1d9ec685a8ed.jpg)
3-Point:
![Screenshot - 10_08_2019 , 09_58_51](https://user-images.githubusercontent.com/39404647/62819624-ff393980-bb57-11e9-9256-91eae353794e.jpg)
Bilinear:
![Screenshot - 10_08_2019 , 09_59_02](https://user-images.githubusercontent.com/39404647/62819627-0c562880-bb58-11e9-9030-61e2637ac34b.jpg)

* Ridge Racer have same issue but on some buildings - like buggy textures.
JINC2:
![retroarch 2019-08-12 14-34-59-780](https://user-images.githubusercontent.com/39404647/62868879-eaef6b00-bd16-11e9-8fba-4c15eafd6afe.jpg)
xBR:
![retroarch 2019-08-12 14-35-12-697](https://user-images.githubusercontent.com/39404647/62868897-f347a600-bd16-11e9-967e-2c57262d2332.jpg)
![retroarch 2020-01-23 16-49-06-826](https://user-images.githubusercontent.com/39404647/73004010-e02d1c00-3e06-11ea-885a-8f1fb489999f.jpg)
![retroarch 2020-01-23 16-52-52-495](https://user-images.githubusercontent.com/39404647/73004043-f63adc80-3e06-11ea-950e-098d17314fb8.jpg)
Xbr:
![retroarch 2020-01-24 19-55-13-824](https://user-images.githubusercontent.com/39404647/73096055-4176ed00-3ee4-11ea-920e-5c158f68a256.jpg)
JINC2:
![retroarch 2020-01-24 19-55-41-293](https://user-images.githubusercontent.com/39404647/73096079-4cca1880-3ee4-11ea-86fe-6b249c42b77e.jpg)

* Ridge Racer Revolution - Some little part next to the road.
* Kileak The blood having some too (3rd level on red part on the wall).
* The World is not enough - on box in snow level.
* Darklight Conflict - Drone on 1st training level.

https://www.youtube.com/watch?v=mCln_mm2AgU

After extented search an old issue seem to have exactly same behavior, but only with the 3 filters https://github.com/libretro/beetle-psx-libretro/issues/257
### Expected behavior
No buggy textures.

### Version/Commit
Retroarch 1.7.7

- Beetle PSX: [version/commit]
Beetle PSX HW 0.9.44.1 7b584a4

### Core options
Renderer: Hardware
Software Framebuffer: On
Adaptive Smoothing: On
MDEC YUV Chroma Filter: On
Internal GPU Resolution: (8x)
MSAA: x16
Perspective Correction: On
PGXP Operation Mode: Memory Only

### Environment information

- OS: Windows 10 x64 1809
- Compiler: N:A
- GPU: RTX 2070 - 431.60

**Comment by Nucleoprotein** [comment]
Hymm, i need to retest filters then, i recently switched from GTX 1060 to RTX 2070S

**Comment by backgamon** [comment]
Solved with https://github.com/libretro/beetle-psx-libretro/commit/b11adfe55da92a02d1b9a5b9b71506223c5be226
