### ISSUE TITLE
Update core to 1.24.0

### ISSUE THREAD

**Issue by ToniBC** [libretro/beetle-psx-libretro#533]
Mednafen was recently updated with several corrections of this emulator and it would be nice to include them to improve those small errors. I don't know if some have already been applied, but since the core only reflects that it is in 0.9.44.1, they supposedly were not added.

After 0.9.44.1 there are several changes that would be good to include in the core to improve emulation.

- PSX: Improved timing of CDC command 0x0A per tests on a PS1; fixes missing music and hangs in "Grind Session".
- PSX: Altered seek and pause timing and behavior per tests on a PS1; fixes hangs in "Incredible Crisis", "Ballerburg - Castle Chaos", "Transformers - Beast Wars Transmetals", and "Simple 1500 Series Vol. 057 - The Maze".
- PSX: Don't set the autopause track test value unless autopause is enabled; fixes missing music in "Pitball".
- PSX: Delay first CD-DA report after playback begins, per tests on a PS1; fixes missing music in "Roswell Conspiracies - Aliens, Myths & Legends".
- PSX: Improved emulation of the behavior of CDC command 0x0A per tests on a PS1; fixes hang in "Goryuujin Electro".
- PSX: Added a pseudorandom component to Pause command timing to address loading-related hangs in "Colony Wars - Vengeance (Europe)" and "Army Men - Air Attack (Europe)".
- PSX: Generate a seek error if the tray is opened while the CD drive is not stopped; fixes broken disc switching in "Arc the Lad III".
- PSX: Memory cards are now backed up on startup(maximum number of backup copies kept for each memory card is 5).
- PSX: Fixed a regression introduced in 1.22.0-UNSTABLE that broke a few PS1 games(e.g. SimCity 2000 and Rise 2).

I comment as you recommended to me to be reflected and appear as a pending task.

Many thanks for your work.

**Comment by personaone** [comment]
@1.27 now and off to 1.28 as unstable now - any idea if this core has a chance to be in sync with upstream? 🙏

**Comment by hizzlekizzle** [comment]
It doesn't get advertised much, but the vast majority of commits has been backported already. The core is a hard-fork at this point and it's not really feasible to sync it with upstream, but the version number doesn't reflect the actual state of the core anymore, either.

**Comment by Sanaki** [comment]
Worth note, the remaining relevant unsynced commits aren't just forgotten, they often conflict with enhancement features users expect to continue working.

**Comment by ToniBC** [comment]
I suppose that many things are fixed, the problem is that as in other cores, the version number does not reflect the state. We'd better close the topic and if bugs are found we'll put them in.

This core being very modified with respect to the base, I suppose that the arrangements do not make much sense. The one that is far behind is the Beetle Saturn, which is missing many corrections.

Thank you.
