### ISSUE TITLE
Sound problems in Double Dragon (J)

### ISSUE THREAD

**Issue by ToniBC** [libretro/beetle-psx-libretro#537]
The Double Dragon (J) game has sound errors in all PS1 emulators (Beetle PSX / HW and PCSX ReARMed). Also tested in Mednafen and fails the same. All tested in Retroarch for Windows 10.

In the game menu, there is no sound effect, no music and when you are in the fighting, there are sounds but the music does not play correctly and enters an infinite loop.

Thank you.

**Comment by rz5** [comment]
@ToniBC - It also happens in Mednafen upstream? Can you re-confirm that?

If so, then please consider reporting it on the upstream bug tracker (https://forum.fobby.net/index.php?t=msg&th=1114&start=0&)

**Comment by ToniBC** [comment]
Surprisingly it seems that now it works well, the selection menu part seems to be like that in the game, without sound effects or music, but now in the fighting everything seems to work fine. As every day I update everything, including the cores (I always use the nightly ones), it might be some small bug that has already been fixed.

If it happens again or I find something strange I will notify you again.

Thank you.
