### ISSUE TITLE
[Speedhack] Megaman X6 hangs on "Now Loading" screen when 'Increase CD Loading Speed' is 8x or above.

### ISSUE THREAD

**Issue by iokzero** [libretro/beetle-psx-libretro#539]
Try to Load Megaman X6 CHD image

There's a good change that the game will stuck at one of the NOW LOADING screen. 
Especially the one right before entering the very first stage. 

So far I am not able to pass that NOW LOADING screen, but that game can stuck on one of the previous NOW LOADING screen. 

Not sure what additional information would be help, but the game does load. like you can see all the title screen, OP anime, and all that, as long as it doesn't got stuck on the NOW LOADING screen right before.

Thanks for the great work.

**Comment by rz5** [comment]
@iokzero - Every new github issue on this repo starts with template text and fields you can fill. Could you please fill those fields? That would be a big help.

**Comment by iokzero** [comment]
Tested with up to date Mednafen on Majaro Linux, It works fine. 

**Bug Description:**

Try to Load Megaman X6 CHD image with beetle-psx-libretro. The game will load, and Op anime will play.

But there's a good change that the game will stuck at one of the NOW LOADING screen.
Especially the one right before entering the very first stage. So far I am not able to pass that NOW LOADING screen, but that game can stuck on one of the previous NOW LOADING screen as well.

Generally speaking, the Now Loading screen takes much longer then normal (compare an actual PSX)

**Expected Behavior:**
Game load, game NOW LOADING screen pass as normal. 


**Actual behavior:**
Game wouldn't pass NOW LOADING screen

**Step to reproduce the bug:**
Load the game with Beetle-psx-libretro, and wait until to see NOW LOADING screen

**Biscet Results & Version:**
Both RetroArch 1.7.6 and RetroArch 1.7.8 have the same issue.
Beetle PSX come with Lakka 2.2.2 and Lakka 2.3.1

**Core Option:**
Default

**Environment Information:**

Lakka 2.2.2 and Lakka 2.3.1
GPU: Intel Iris Plus HD 650

**Comment by rz5** [comment]
I am on Windows 10 and I can't replicate this bug on my end. I tried with a fresh beetle-psx-hw build and a CHD version of Mega Man X6. Also tried with the non-hw version of beetle-psx, same results.

![image](https://user-images.githubusercontent.com/8117159/65825699-f6203b00-e271-11e9-92e8-3d03882d959a.png)

Since these issues can be caused by usage of speedhacks, I tried them one by one and discovered that setting `Increase CD Loading Speed` to 8x or more, then I get this bug.

@iokzero - Re-check your core options.

**Comment by iokzero** [comment]
@rz5 

You right! So I tried to change the Increase CD Loading Speed around. and finally put it at X6. The problem goes away. Anything below that seem fine too.

Thank you so much for your help!

**Comment by iokzero** [comment]
Just to add a note, 

The speed hack seem affecting a number of games, Such as Castlevania: Symphony of the Night, which wouldn't load @ x4 of the speed.

**Comment by rz5** [comment]
@iokzero - Right, thanks for the info. I am aware that this particular speedhack is hit or miss and that some games are especially problematic when CD timings change.

The core option itself should say "some games are known to break when above certain speeds". I suppose that should be changed to "some games won't work if loading speed isn't set to 1x (native)".

I dunno how else to warn users about this without resorting to ugly hacks like game black lists and whatnot.
