### ISSUE TITLE
Dithering behavior for native/upscaled seem swapped for SW core

### ISSUE THREAD

**Issue by ggdrt** [libretro/beetle-psx-libretro#541]
### Description

Choosing "1x(native)" dithering in core options causes software renderer to dither at a finer upscaled granularity while choosing "internal resolution" dithering has it dither at a rougher/blockier 240p granularity

### Expected behavior

Both Vulkan/OpenGL renderers work the other way around -- choosing "internal resolution" has finer grain dithering and choosing "1x(native)" gives the blocky lower res dithering. Software core should probably match that behavior.

I have a simple fix here that doesn't seem to affect the hardware renderers since they don't read from the dither_upscale_shift variable to my knowledge:
https://github.com/ggdrt/beetle-psx-libretro/commit/0dc53c92d9896b4a007574ac628019c709c552bc

@simias Any thoughts? I think you implemented the dithering upscaling in gpu_polygon.cpp a while back. I'm not exactly sure what the math with dither_upscale_shift is but having it set to 0 gives finer grain dithering and having it set to psx_gpu_upscale_shift gives lower res dithering. So swapping those lines around in the commit above gives the expected results.

I'll open a PR if there aren't any problems.

**Comment by rz5** [comment]
Your commit in your fork is basically undoing my commit here (https://github.com/libretro/beetle-psx-libretro/commit/b0022b154a9b5ea2deaee2944538be866832b20f).

I swear I did it right but it's been a long while and when I use the SW renderer, I don't upscale.

If you don't mind, post some screenshots illustrating the problem to document it. I'll accept your PR afterwards.

**Comment by ggdrt** [comment]
Sure thing. Current behavior on commit f55db86:

**Software Renderer, 2x Internal Resolution, 1x (Native) Dither**
![fft-sw-2xIR-dither-native](https://user-images.githubusercontent.com/45282415/66448236-c1e11300-ea05-11e9-97e9-1d9345ea2ec6.png)

**Software Renderer, 2x Internal Resolution, Upscaled (Internal Resolution) Dither**
![fft-sw-2xIR-dither-upscaled](https://user-images.githubusercontent.com/45282415/66448296-e9d07680-ea05-11e9-88be-4e37c9e4498a.png)

**OpenGL Hardware Renderer, 2x Internal Resolution, 1x (Native) Dither**
![fft-hw-2xIR-dither-native](https://user-images.githubusercontent.com/45282415/66448340-0b316280-ea06-11e9-8d7b-540b7ec809b8.png)

**OpenGL Hardware Renderer, 2x Internal Resolution, Upscaled (Internal Resolution) Dither**
![fft-hw-2xIR-dither-upscaled](https://user-images.githubusercontent.com/45282415/66448344-0e2c5300-ea06-11e9-8dd4-a8b38b16a7f2.png)
