### ISSUE TITLE
Display area misaligned by default when Crop Overscan is enabled for SW renderer

### ISSUE THREAD

**Issue by ggdrt** [libretro/beetle-psx-libretro#543]
## Description

Display area is misaligned by default when Crop Overscan option is enabled in software renderer. It crops too few pixels on one side and too many pixels on the other side. Issue occurs regardless of internal resolution, window scale, or frontend.

Issue doesn't apply for the hardware renderers since Crop Overscan option doesn't work for them.

### Expected behavior

Crops properly to the display area by default (basically for any game that sets GP1(06h) X1=260h and X2=C60h, which should be most of them) for all the possible width modes. This should be expected behavior without having to utilize the Offset Cropped Image option.

### Actual behavior

Some examples:

[256px width mode, crop overscan off](https://user-images.githubusercontent.com/45282415/66547181-845ab380-eaf3-11e9-934f-1888d320a4c0.png)
[256px width mode, crop overscan on](https://user-images.githubusercontent.com/45282415/66547165-7d33a580-eaf3-11e9-818c-ddfb8e015741.png)

*Display area is offset approx 2 pixels to the right by default in 256px mode.*

[320px width mode, crop overscan off](https://user-images.githubusercontent.com/45282415/66550774-f256a900-eafa-11e9-8639-a3f1b3cc3dd9.png)
[320px width mode, crop overscan on](https://user-images.githubusercontent.com/45282415/66550783-f682c680-eafa-11e9-97a3-c81903707306.png)

*Display area is shifted approx 1 pixel to the right by default in 320px mode.*

[512px width mode, crop overscan off](https://user-images.githubusercontent.com/45282415/66561507-79614c80-eb0e-11e9-9a80-454e6961af44.png)
[512px width mode, crop overscan on](https://user-images.githubusercontent.com/45282415/66561515-7e260080-eb0e-11e9-8e1f-417685d32eb8.png)

*Display area is shifted approx 3 pixels to the left by default in 512px mode.*

Haven't tested with other width modes yet.

### Thoughts

Adjusting the hardcoded shifts for each width mode (e.g. 10 to 12 for padded 280, 14 to 15 for padded 350, etc.) in the lines below seem to give the correct results. I wasn't able to figure out how the current offset values were derived.

https://github.com/libretro/beetle-psx-libretro/blob/9f1341a9c3f881b1a552d0c0c4e8d3e22b2ed578/libretro.cpp#L3864-L3904

I also wasn't able to figure out what the 260h and C60h gpu cycle offsets in GP1(06h) were relative to. Nocash documentation says it's relative to hsync, but which part? All the calculations I've done so far have given strange numbers. If anyone has info on this it'd be appreciated. Would be useful for accuracy purposes.

In any case, upstream mednafen don't seem to adhere strictly to the horizontal display register values (based on upstream comments in gpu.cpp, unless I'm misunderstanding them) so I wasn't able to gleam anything from the source. Upstream also handles PSX overscan a lot more conservatively and leaves minor black bars instead of fully cropping to the display area for some reason.

Since upstream mednafen seems to handle overscan cropping a bit strangely as well, I'm thinking maybe it's best to just adjust the offset values ad hoc for now to at least get the display area properly centered.

**Comment by ggdrt** [comment]
So after looking into this, turns out the overscan crop code originates from 5f6b43e back in early 2013 and the offset values used were specifically for removing overscan from misaligned output across different video modes. Upstream mednafen fixed this alignment issue on Dec 9, 2014 based on the Changelog and staged it in 0.9.37 that same month. The alignment fix seems to have been ported into beetle-psx-libretro soon after but the specific cropping offsets were never brought in line with that fix.

Tested primarily with Castlevania: Symphony of the Night. Good example to work with since including the bios, the game uses all display modes from boot sequence up to gaining control of a character.

@rz5 Btw, any dev channel or someone I can talk to for advice on getting overscan cropping functionality implemented in the hardware renderers? I have a partially working implementation in the GL renderer but it only seems to work properly at 4x internal resolution or higher. I'm not really familiar with OpenGL so I'm not sure what I'm doing wrong. Getting that fully working should resolve at least a couple issues on this repo tracker.

**Comment by rz5** [comment]
You can join the libretro Discord and ask it in the programming or programming-shaders channels. Someone is bound to chime in.
