### ISSUE TITLE
Dynamic Recompiler - Compatibility List

### ISSUE THREAD

**Issue by twinaphex** [libretro/beetle-psx-libretro#544]
**Games with issues:**
* Alien Trilogy (USA) - Win64 x64 - d9ad16de - Crashes when you try to shoot when ingame
* Doom (USA) - Win64 x64 - d9ad16de - Works fine except for enemy AI of the imp not working in the first level of Doom 1
* Street Fighter EX Plus Alpha (USA) - Win64 x64 - d9ad16de - Sound effects of the opponent are missing
* Final Fantasy VII (USA) - Win64 x64 - d9ad16de - Sound effects are missing
* Hexen - Win64 x64 - d9ad16de - No Sound effects by the player and flickering enemy sprites
* Wipeout XL (USA) - Win64 x64 - d9ad16de - When in a race, at a certain point new frames are no longer rendered and you cannot continue the race anymore
* Wipeout 3 (USA) - Win64 x64 - d9ad16de - No sound effects
* Battle Arena Toshinden (USA) - Win64 x64 - d9ad16de - Several game bugs happen when starting a fight, cannot fight the opponent ,does an instant 'Draw' and nobody can win.
* Ridge Racer Type 4 (USA) - Win64 x64 - d9ad16de - When ingame, with automatic transmission (AT) enabled, it will not go past gear 1.
* Mega Man X4 (USA) - Win64 x64 - d9ad16de - Music breaks at title screen, gets stuck at 'Now Loading' screen when selecting New Game
* Battle Arena Toshinden 2 (USA) - Win64 x64 - d9ad16de - Crash after selecting character and when going inside a round.
* Dead or Alive (USA) - Win64 x64 - d9ad16de - Crashes on the first stage.
* Magic Carpet (USA)  - Win64 x64 - d9ad16de - Works fine except for broken sound effects when ingame.
* Crash Bandicoot (USA) - Win64 x64 - d9ad16de - Hang after moving forward on the first stage.
* Jumping Flash (USA) - Win64 x64 - d9ad16de - Crashes on the first stage.
* Jumping Flash 2 (USA) - Win64 x64 - d9ad16de - Crashes on the first stage.
* Star Wars: Dark Forces (USA) - Win64 x64 - d9ad16de - Crashes on the first stage.
* Gran Turismo (USA) - Win64 x64 - d9ad16de - Crashes when starting Arcade Mode.
* Mortal Kombat Trilogy (USA) - Win64 x64 - d9ad16de - Crashes at character select screen. **NOTE: This is a REGRESSION. This did not happen before with an earlier build.**
* Tomb Raider (USA) [v1.6] - Win64 x64 - d9ad16d - Crashes after selecting the game from the menu. **NOTE: This is a REGRESSION. This did not happen before with an earlier build.**
* Ridge Racer (USA) -  Win64 x64 - d9ad16d - Corrupted textures
* Mega Man Legends (USA) - Win64 x64 - d9ad16de - Crashes after selecting New Game.
* Resident Evil 3: Nemesis (USA) - Win64 x64 - d9ad16de - Inventory menu is missing textures, sound is gone from cutscene that happens before the CGI intro.

**Games that work as expected (with slight issues):**
* Einhander (USA) - Win64 x64 - d9ad16de - Works fine, no issues so far.
* Loaded (USA) - Win64 x64 - d9ad16de - Works fine, no issues so far.
* Resident Evil (USA) - Win64 x64 - d9ad16de - Works fine, no issues so far.
* Tekken 2 (USA) - Win64 x64 - d9ad16de - Works fine. Only issue perhaps being a slight graphics glitch with the background layer where sometimes it shows the fill color when it shouldn't (this is most apparent during victory poses when winning a fight).
* Tekken 3 (USA) - Win64 x64 - d9ad16de - Works fine except for this glitch on the character select screen.

![image](https://user-images.githubusercontent.com/1075274/66701132-213a6e00-ecf9-11e9-8bb0-9d3836011fc5.png)

**Comment by i30817** [comment]
Symphony of the Night is currently crashing at boot in the lightrec fork too.

**Comment by ZachCook** [comment]
These results are outdated, current dynarec bugs are tracked in #588
