### ISSUE TITLE
beetle psx hw forcing vulkan on system without vulkan

### ISSUE THREAD

**Issue by rhetr** [libretro/beetle-psx-libretro#548]
## Description

I don't have vulkan installed on this system so I want to use the opengl backend to beetle psx hw, but it keeps forcing the vulkan backend even when I select gl or glcore in retroarch and crashing as a result.

    ...
    [INFO] [Environ]: SET_HW_RENDER.
    [INFO] Requesting Vulkan context.
    [INFO] [Environ]: SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE.
    [INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
    [INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
    [INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
    [INFO] [RCHEEVOS]: ext_hash 0b886782 ('cue')
    [INFO] [RCHEEVOS]: Load task finished
    Failed to open /media/Data/games/retroarch_data/saves/Vagrant Story (USA).srm: No such file or directory
    [INFO] Skipping SRAM load..
    [INFO] Version of libretro API: 1
    [INFO] Compiled against API: 1
    [INFO] [Cheats]: Load game-specific cheatfile: /home/rhetr/.config/retroarch/cheats/Beetle PSX HW/Vagrant Story (USA).cht
    [INFO] [Audio]: Set audio input rate to: 44143.41 Hz. 
    [INFO] [Video]: Video @ 960x720
    [INFO] [Video]: Using HW render, Vulkan driver forced.
    [INFO] [Video]: "glcore" saved as cached driver.
    [ERROR] [Wayland]: Failed to connect to Wayland server.
    [INFO] Vulkan dynamic library loaded.
    [ERROR] [Vulkan]: Could not find instance extensions. Will attempt without them.
    [INFO] [Vulkan]: App: Beetle PSX (version 0)
    [INFO] [Vulkan]: Engine: parallel-psx (version 0)
    [ERROR] Failed to create Vulkan instance (-9).
    [WARN] Failed to bind API (#9, version 1.0) on context driver "x-egl".
    [WARN] Failed to bind API (#9, version 1.0) on context driver "kms".
    [WARN] Failed to bind API (#9, version 1.0) on context driver "sdl_gl".
    [INFO] Vulkan dynamic library loaded.
    [ERROR] [Vulkan]: Could not find instance extensions. Will attempt without them.
    [INFO] [Vulkan]: App: Beetle PSX (version 0)
    [INFO] [Vulkan]: Engine: parallel-psx (version 0)
    [ERROR] Failed to create Vulkan instance (-9).
    [ERROR] [Vulkan]: Failed to create Vulkan context.
    [INFO] [Vulkan]: Found vulkan context: null
    [INFO] [Vulkan]: Detecting screen resolution 320x240.
    [INFO] [Vulkan]: Using resolution 320x240
    Segmentation fault (core dumped)

full log [here](https://pastebin.com/vtDUyTZP)

why is `"glcore" saved as cached driver`??

### Version/Commit
- Beetle PSX: [0.9.44.1/9f1341a]

### Environment information

- OS: ubuntu 16.04.6
- GPU: nvidia geforce 750m via bumblebee/optirun, nvidia-418.56

**Comment by rz5** [comment]
@Rinnegatamante

**Comment by negativeExponent** [comment]
this should be fixed in latest commit... this was worked on hours ago.

**Comment by rhetr** [comment]
great! works fine now thanks.
