### ISSUE TITLE
Crash with newest buildbot build from today

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#55]
After updating to the newest buildbot build I was able to reproduce a crashing problem.

- When starting FFIX it crashes right away.
- When starting Die Hard Trilogy, it crashes right after the probe entertainment logo starts to fade away.

The event viewer entry is as follows:

```
Faulting application name: retroarch.exe, version: 0.0.0.0, time stamp: 0x0024a7a4
Faulting module name: mednafen_psx_hw_libretro.dll, version: 0.0.0.0, time stamp: 0x574af118
Exception code: 0xc0000005
Fault offset: 0x0000000000087255
Faulting process id: 0x950
Faulting application start time: 0x01d1b9c4f3dd57ee
Faulting application path: E:\Emu\Emus\RetroArch\retroarch.exe
Faulting module path: E:\Emu\Emus\RetroArch\cores\mednafen_psx_hw_libretro.dll
Report Id: 8a5e47b6-efa5-43d5-9168-298607abbc6e
Faulting package full name: 
Faulting package-relative application ID: 
```

Both of these games worked without problems with yesterday's build. I tested this with BIOS skip enabled. However, when disabling BIOS skip, it never gets passed the BIOS screen, and the screen looks like this:

![image](https://cloud.githubusercontent.com/assets/852777/15634758/23ca64b0-25cc-11e6-8254-cb4ef9686e71.png)

**Comment by twinaphex** [comment]
Are you testing this with the GL renderer?

**Comment by saftle** [comment]
Yes, sorry, I should have mentioned that. WIth the software renderer using the same mednafen HW core, it works without problems. 

I also wasn't sure if I should post this in the GL Renderer bug thread. Since that seemed to be more about the differences between games I chose to instead create a new thread.

**Comment by simias** [comment]
Looks like what I get when I don't "make clean" after having modified the vertex attributes. Does the buildbot start from a clean directory?

**Comment by saftle** [comment]
I'm running Retroarch on Windows 10 x64. Just to be safe, I started from scratch and deleted everything. I grabbed the newest nightly of retroarch and the newest mednafen psx HW build. The problem sadly still occurs. Anything else I can provide to help debug the issue?

**Comment by saftle** [comment]
I started from scratch again (newest nightly and newest Mednafen PSX HW core). No shaders are being used, and everything in the core options is set to default. I am also attaching the Windows Error Reporting Dump, in case that helps. If need be, I can configure windows to instead save a full dump instead.
[Report.zip](https://github.com/libretro/beetle-psx-libretro/files/289871/Report.zip)

**Comment by rz5** [comment]
To whom it may concern: the buildbot offers a mednafen build with the GL renderer enabled (where a 'make' flag called HAVE_OPENGL is set to 1).

I have tested the Windows x86_64 build of it and it seems like there's a very nasty bug, as can be seen on @saftle's screenshots and bug description.
If you build it from source e.g. using the MSYS2 MinGW-w64 toolchain, said bug does not seem to be present.

@fr500, you are the chosen one, the child of destiny. I suspect the buildbot's build recipe is at fault, somehow.

**Comment by saftle** [comment]
@rz5 Thanks so much for reproducing it as well. I just finished with cleaning & re-installing all of my Nvidia drivers to rule out the possibility of a driver being at fault. I'm glad you posted before I tried the next thing.

**Comment by rz5** [comment]
@saftle: Now that you mention it, it might be an Nvidia thing. I'm on an insider preview of Win10, with the Nvidia driver version being 368.22. Would be interesting if a Windows AMD GPU user could reproduce the bug.

**Comment by Warriors-Blade** [comment]
This bug also happens on a intel chipset laptop running windows 7 64 bit .

**Comment by saftle** [comment]
The newest build no longer has the issue! I left retroarch as is, and updated the mednafen psx hw core.

**Comment by saftle** [comment]
I think we can officially close this issue unless it is still reproducible by @Warriors-Blade or @rz5.

**Comment by rz5** [comment]
Not happening on my side anymore. Shouldn't happen to anyone else either since @fr500 fixed the buildbot recipe.
Since you're the author of this issue, you can close it.

**Comment by saftle** [comment]
Oh thanks. I hadn't realized that. Closing issue.
