### ISSUE TITLE
[Non-HW] Rendering resolution does not stick

### ISSUE THREAD

**Issue by OldsXCool** [libretro/beetle-psx-libretro#553]
When changing the rendering resolution to 2X the game's resolution will change and stay until the game is closed. When opening the game back up the resolution will go back to 1X but the options menu will still say that it is set to 2X. The workaround is that you simply toggle the 2X back to 1X, then back to 2X and the resolution will change once you back out of the menu. This problem does not exist when using the software renderer in Beetle PSX HW which I have switched to in the meantime.

**Comment by ggdrt** [comment]
@OldsXCool Can you check if 1. whatever frontend you are using has permissions to read/write from the folder that your core options are stored stored in, and 2. if this only happens on a per-game basis? I haven't encountered this problem before so more information to work off of would be good.

**Comment by OldsXCool** [comment]
I am using Retroarch, no other front end is involved and everything has full permissions to read and write. The resolution is the only setting in the options menu that does not stick. Other things like GTE overclock stick and do work as intended. As I stated the resolution upon game startup says that it is indeed 2X but the graphics are clearly in 1X until you go back into the options menu and give it a quick toggle. When you return to the game the resolution is then correct. The setting sticks until you shut the game down. If you use the restart option the setting still sticks. If you close the game completely and open it back up you will need to toggle the resolution setting once again. It is not a per game basis. It's any game that you run. Beetle PSX HW doesn't have this issue in software mode.

**Comment by ggdrt** [comment]
Which hardware renderer is this happening on, GL or Vulkan? And what build? The latest build should be 7e76756.

**Comment by ggdrt** [comment]
Which hardware renderer is this happening on, GL or Vulkan, and on what build? The latest build should be 7e76756.

There have been a number of updates to this core and to RetroArch since your initial post, so the more information we can get the better. Information such as your platform would be helpful as well.

**Comment by OldsXCool** [comment]
The setting does not stick regardless of the API being used. The three computers that I've used are as follows. I am indeed running the latest build of 7e76756.

Core i5 2320 
Nvidia GTX 750
4GB RAM
Windows 7

Core i5 2500
Nvidia GTX 950
8GB RAM
Windows 7

Core i5 4590
Intel HD Graphics
8GB RAM
Windows 8.1

I've also used several different versions of Retroarch including 1.7.8 through 1.8.1. On the Beetle PSX HW core I have noticed quite a few bugs now with the last three releases of Retroarch which have had issues with the software renderer on the latest build of Beetle PSX HW (7e76756). The biggest bug currently is that it is not switching to software mode at all anymore on the latest version of Retroarch 1.8.1. It started having issues in 1.7.9 with a big performance bug where it required nearly 10% more of my CPU core causing frame drops in performance heavy games. In 1.8.0 the bug appeared to be fixed but then I weirdly started seeing graphical glitches that I only see when using the hardware renderer. When I downloaded 1,8.1 I found out that I was seeing those glitches because Beetle PSX HW was in fact still running in hardware mode even with software mode being selected. I've confirmed this with my Windows 8.1 and Windows 7 machines. I'm currently using Beetle PSX HW in Retroarch 1.7.8 where everything works correctly.

The game I used for testing was Jumping Flash! 2 which always seems to cause problems with hardware renderers. The graphical glitches in the game are way more subtle using the Vulkan API with most of the defects being in the 2D elements of the game. There are massive graphical glitches using the hardware renderer in Open GL. I didn't catch the glitch at first on 1.8.0 because I was running Vulkan. When I downloaded 1.8.1 I spotted the glitches and then switched over to Open GL and that's when I saw massive graphical glitches which was a dead giveaway that hardware mode was still being used even though Beetle PSX HW had been set to software mode. Yes I did completely close the software and run it for the new settings to take effect. 

I know that this post was originally for Beetle PSX and not Beetle PSX HW, but they look to be one in the same and since I've used Beetle PSX HW exclusively since encountering the resolution bug in Beetle PSX I thought I would mention that Beelte PSX HW's software renderer is in a bad state right now.

**Comment by rz5** [comment]
I can't reproduce this on any of the hardware renderers.

@OldsXCool Something you can verify is whether or not you're using using core or content configuration overrides - these will cause RA to use different configuration settings for beetle-psx or a PSX game, respectively.

Secondly, make sure the retroarch-core-options.cfg file is stored somewhere where RetroArch has permissions to write to.

**Comment by OldsXCool** [comment]
I have the Beetle PSX core set to default to 2X resolution without any core overrides in place. When I go to run a game it clearly runs in 1X. When I check the options menu it says that it is running in 2X when it is not until I toggle the setting.

If you would like I can make a video of my findings. I assure you that all my folders have permission to read and write with no configs that are stored in any other remote locations. Everything is saved in Retroarch's default locations. 

Please don't get me wrong. I am only here to help and do not wish to come off as whiny or demanding in the slightest. Beetle PSX and PSX HW are amazing works. I brought the resolution issue up with Hunterk in the Libretro forums and he said that I should post the issue here as he has heard that other have experienced this issue. It's possible that this issue isn't very wide spread because most use the hardware renderer in Beetle PSX HW when they want to boost resolution because boosting resolution in software mode is highly taxing on the CPU though it is much more accurate. Again if you would like for me to make a video of all the issues you can see them first hand.

**Comment by rz5** [comment]
Don't worry about sounding whiny/demanding.

Videos and step-by-step instructions to reproduce the bug are very welcome. And could you re-confirm: this only happens with the SW renderer in the non-HW beetle-psx core?

Or does it happen only with the SW renderer in both beetle-psx and beetle-psx-hw?

**Comment by OldsXCool** [comment]
Ok. I will take footage of the issues in action and upload it to You Tube as an unlisted vid and give you the link.

**Comment by rz5** [comment]
@OldsXCool - I just managed to reproduce the bug, don't bother with the videos.

So this bug specifically affects the non-HW beetle-psx version. I'll try to look into it now. Most likely related to how the non-HW excludes most things related to the RSX interface...

**Comment by OldsXCool** [comment]
Excellent!

**Comment by rz5** [comment]
@OldsXCool - I think the latest changes fix it, however they were not simple. Please check if it fixes the bug you reported.

If you want those extra brownie points, please also check if you get new crashes when playing around with upscaling and if you got issues with your memory cards (that was kinda sorta changed too).

**Comment by ggdrt** [comment]
Had to revert the original commit. ca36c04 has the latest fix for this.
