### ISSUE TITLE
Some options ignored on the latest revision (980b24b)

### ISSUE THREAD

**Issue by nezumisama** [libretro/beetle-psx-libretro#571]
# First and foremost consider this:
- This is a DEVELOPER oriented channel dedicated to report bugs and suggest features about the libretro core, please do not ask for help;
- The upstream bug tracker is a forum thread, located at https://forum.fobby.net/index.php?t=msg&th=1114;
    - Note: As of October 2018, Microsoft email providers (think email addresses ending with hotmail/live/outlook) are rejecting email from the forum. If you want to register an account in the upstream project's forum, consider using another mail provider.
- For game-related bugs:
    1) First, check if it's already reported on the upstream bug tracker;
    2) If it's not reported there, try to reproduce the bug with mednafen;
    3) If it's reproducible with mednafen, report it on the upstream bugtracker;
    4) If it's not reproducible with mednafen, ONLY THEN should you report it here.
    
## Description

When I updated this core today from retroarch (which downloads nightlies) and
got version `0.9.44.1 980b24b` i noticed a problem: the core ignores some
options. I haven't checked all, but two that I know of are `skip_bios` and
`cd_access_method`. I figured the first is ignored because if I set to off,
save settings and restart, I still get the bios animation. As for the other,
I noticed it must be ignored because games load without a longer delay
which would normally occur. Most other options work as expected. Note,
the options that are ignored, are properly saved to `retroarch-core-options.cfg`
and their values properly displayed in the core's menu. I tried removing the file
so that the core resets it's setings and set those options and they still don't work.

To add, the previous version I had, `0.9.44.1 432feab` doesn't have these problems.

### Expected behavior

The aforementioned options should work, e.g. if I enable "skip bios",
games should load without the bios intro animation.

### Actual behavior

The options are ignored, the defaults are always used, e.g.
regardles of how I set "skip bios", the bios animation is shown.

### Steps to reproduce the bug

1. Install  version`0.9.44.1 432feab`.
2. In settings, enable "skip bios".
3. Save settings, restart
4. Load content with this core.

### Bisect Results

It happend somewhere between 432feab and 980b24b.

### Version/Commit

Core: `0.9.44.1 980b24b`.
Retro-arch: `v1.8.1 bfdc8e6a62`

### Core options

None were changed besides the ones that I have a problem
with. Output form file:

```
beetle_psx_hw_adaptive_smoothing = "enabled"
beetle_psx_hw_analog_calibration = "disabled"
beetle_psx_hw_analog_toggle = "disabled"
beetle_psx_hw_cd_access_method = "sync"
beetle_psx_hw_cd_fastload = "2x(native)"
beetle_psx_hw_cpu_freq_scale = "100%(native)"
beetle_psx_hw_crop_overscan = "enabled"
beetle_psx_hw_depth = "16bpp(native)"
beetle_psx_hw_display_internal_fps = "disabled"
beetle_psx_hw_display_vram = "disabled"
beetle_psx_hw_dither_mode = "1x(native)"
beetle_psx_hw_enable_memcard1 = "enabled"
beetle_psx_hw_enable_multitap_port1 = "disabled"
beetle_psx_hw_enable_multitap_port2 = "disabled"
beetle_psx_hw_filter = "nearest"
beetle_psx_hw_frame_duping = "disabled"
beetle_psx_hw_gpu_overclock = "1x(native)"
beetle_psx_hw_gte_overclock = "disabled"
beetle_psx_hw_gun_cursor = "cross"
beetle_psx_hw_gun_input_mode = "lightgun"
beetle_psx_hw_image_crop = "disabled"
beetle_psx_hw_image_offset = "disabled"
beetle_psx_hw_image_offset_cycles = "0"
beetle_psx_hw_initial_scanline = "0"
beetle_psx_hw_initial_scanline_pal = "0"
beetle_psx_hw_internal_resolution = "1x(native)"
beetle_psx_hw_last_scanline = "239"
beetle_psx_hw_last_scanline_pal = "287"
beetle_psx_hw_lineRender = "default"
beetle_psx_hw_mdec_yuv = "disabled"
beetle_psx_hw_mouse_sensitivity = "100%"
beetle_psx_hw_msaa = "1x"
beetle_psx_hw_negcon_deadzone = "0%"
beetle_psx_hw_negcon_response = "linear"
beetle_psx_hw_pgxp_mode = "disabled"
beetle_psx_hw_pgxp_texture = "disabled"
beetle_psx_hw_pgxp_vertex = "disabled"
beetle_psx_hw_renderer = "hardware"
beetle_psx_hw_renderer_software_fb = "enabled"
beetle_psx_hw_shared_memory_cards = "disabled"
beetle_psx_hw_skip_bios = "enabled"
beetle_psx_hw_super_sampling = "disabled"
beetle_psx_hw_use_mednafen_memcard0_method = "libretro"
beetle_psx_hw_widescreen_hack = "disabled"
beetle_psx_hw_wireframe = "disabled"
```

### Environment information

- OS: ArchLinux
- Compiler: I have retroarch from my distro's repo, compiler is GCC 9.2.0; I have the core from the nightly repo (downloaded via opnline updater), I don't know the compiler.
- GPU: Nvidia GeForce 1060 6GB, driver 440.31.

**Comment by ggdrt** [comment]
I've tracked down the source of the issue. I'll try to get a fix out as soon as possible.

**Comment by ggdrt** [comment]
@nezumisama Sorry about that, those options should be working again on the latest build (ca36c04). It should be available through the online updater sometime within the day.

**Comment by hizzlekizzle** [comment]
I'll go ahead and close this, but we can reopen it if something goes wrong with the fixed builds.

**Comment by nezumisama** [comment]
I got ca36c04 just now and can confirm those options work now.
