### ISSUE TITLE
Garbage output with internal resolution higher than native on ca36c04

### ISSUE THREAD

**Issue by nezumisama** [libretro/beetle-psx-libretro#572]
## Description

With version ca36c04, if I set internal resolution to anything besides native
I get garbage output. This is immediately seen at the boot screen:
![2019-11-25_19-51-03](https://user-images.githubusercontent.com/3157155/69569586-3e33b380-0fbe-11ea-939d-88b44253dc0e.png)
And first FMV:
![2019-11-25_19-51-20](https://user-images.githubusercontent.com/3157155/69569626-50155680-0fbe-11ea-83c2-833c429fcebc.png)

This happens only with hardware renderer, not with software, and with both
gl and vulkan drivers.

No other options were changed from defaults.

I'll add it seems when you change this option from native while a game is loaded,
it works correctly with no garbage, but after restarting retroarch with increased
resolution enabled, output is broken.

While I'm at it, might I ask if there's any stable release cycle? Retroarch downloads nightlies,
and I seem to have a bad luck with them, as this is the next time in short time I downloaded
a broken revision.

### Expected behavior

Have normal image.

### Actual behavior

Image outputed is more or less garbage and the game is unplayable.

### Steps to reproduce the bug

1. Load this core.
2. Set option `beetle_psx_hw_internal_resolution to e.g 2x.
3. Save setings and restart retroarch.
4. Load a game with this core.

### Bisect Results

I didn't do a full git bisect, but version 980b24b didn't have this bug, ca36c04 does.

### Version/Commit
Core: 0.9.44.1 ca36c04.
Retro-arch: v1.8.1 bfdc8e6a62

### Core options
```
beetle_psx_hw_internal_resolution = "2x"
```

### Environment information

OS: ArchLinux
Compiler: I have retroarch from my distro's repo, compiler is GCC 9.2.0; I have the core from the nightly repo (downloaded via opnline updater), I don't know the compiler.
GPU: Nvidia GeForce 1060 6GB, driver 440.31.

**Comment by rz5** [comment]
I think this is why commit b0d55624a50336a2e03b8714e9e12b7236993b7c had to be somewhat more involved than the latest commit...the reason why this happens is harder to explain but it is related to checking and updating the "upscale" core option during initialization and how that affects 3 things:
* The `MDNF_Surface` static object in libretro.cpp, updated by `alloc_surface()`
* The `vram` pointer in gpu.cpp
* The base/max geometry passed to libretro

@ggdrt - If you think you'd have fun going down the rabbit hole of fixing this bug, I encourage you to do so.
If not, then we can revert edc90765b4f0589383f669272b5cbe2172e243b7 and I will add the changes I described in my ping to you on Discord such that it fixes #571

**Comment by nezumisama** [comment]
@rz5 I've no idea what to suggest. I just thought I ask.

**Comment by ggdrt** [comment]
Latest commit should put this to rest.

This is on us, as neither of the original rework nor the ca36c04 patch should have made it into the master branch without further testing.

**Comment by ggdrt** [comment]
Closing this since latest build should have resolved this issue. Feel free to reopen if there are any further problems.

**Comment by nezumisama** [comment]
I can confirm that with 93a187f (current nightly) the issue is resolved.
