### ISSUE TITLE
"Tom and Jerry in House Trap" hangs when accessing memory card if GTE Overclock is on or CPU Overclock is above 100%

### ISSUE THREAD

**Issue by Anths2016** [libretro/beetle-psx-libretro#581]
Last version Beetle psx HW with Vulkan. Retroarch 1.8.1

**Comment by ToniBC** [comment]
I confirm the same error, tested in the last Nightly of Retroarch and the last core of January 5, 2020 and freezes the game on the memory card screen.

In PSX Rearmed it works without problems.

**Comment by rz5** [comment]
@ToniBC @Anths2016 - You both have created bug reports without filling the initial template. If you don't share information about your system and your core options, it's harder to find out what's wrong.

This bug is caused by `GTE Overclock` being on. Please test it while it's off to confirm.

**Comment by Anths2016** [comment]
No, on and off nothing change.

**Comment by rz5** [comment]
@Anths2016 Please show me what other core options you're using

**Comment by rz5** [comment]
This bug is also caused by `CPU Frequency Scaling (Overclock)` is above 100%. Please put both of those hacks to default and retest to confirm.

**Comment by Anths2016** [comment]
Vulkan or OpenGL. 
Renderer: Hardware
Soft Framebuffer: on
Dithering: off
Adaptive smooth: on
PGXP Op Mode: memory only
PGXP VC: on
PGXP PCT: on
CPU frequency scaling: 100 %
GTE overclock: off
GPU rast ov: 1x
Skip bios (on and off) - tried both ways
cd loading speed: 2x (native)

**Comment by rz5** [comment]
@Anths2016 I can't replicate the bug with your settings. Again, very important, test it with GTE overclock **off** and CPU frequency scaling set to **100%** BEFORE you get to the screen where it hangs.

@ToniBC - If you could also retest this with the above instructions, I'd be very thankful.

You can't get the emulator out of the hang by changing core options, it seems.

**Comment by Anths2016** [comment]
Before... of course.

**Comment by Anths2016** [comment]
Pcsxr-pgxp also have the same problem, but it is solved by using the HLE bios.

**Comment by rz5** [comment]
On RetroArch, enable `Logging Verbosity` and when you start up beetle-psx, check if this is written during startup:
```
[libretro INFO] Checking if required firmware is present.
[libretro INFO] Firmware found: .\system\scph5502.bin
[libretro INFO] Firmware SHA1: F6BC2D1F5EB6593DE7D089C425AC681D6FFFD3F0
```

If it's not, your BIOS may be bad.

Also, if you don't mind, post your full retroarch-core-options.cfg file here.

**Comment by Anths2016** [comment]
That information does not appear, but with a program I went to check the SHA1 of the file, and it is just that.
https://i.imgur.com/98D2Pvw.png

**Comment by ToniBC** [comment]
Disabling the "GTE overclock off" option works, I tried almost all options except that.

Solved, another one that works. Thank you.

**Comment by Anths2016** [comment]
It doesn't work for me. If you don't believe it I make a video.

**Comment by rz5** [comment]
@Anths2016 - If you have the patience, try the following:

Get a fresh build of RetroArch, with it get the latest beetle-psx-hw core and see if it happens for you on stock settings. If it DOES happen with stock everything - and it's not your BIOS - then I'd wager you have a bad game dump...

**Comment by Anths2016** [comment]
Now it works, but I don't understand what is the problem at this point.
