### ISSUE TITLE
Run ahead and Dynarec

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/beetle-psx-libretro#592]
Run Ahead is working fine in the software core (compiled without HW, that's the one I use) with beetle interpreter if your computer is fast enough for it.
I can do 2 frames, almost 3 in several games.

But just 1 frame of run ahead in any other CPU mode, dynarec or even Lightrec interpreter, makes a huge stutter each time you touch the controls in game.

I wonder if this is about an access time to recover a state, if anything can be done on this part?

win7 x64, current RA nightly and core, i5-3570k

**Comment by twinaphex** [comment]
Hi there @Dwedit ,

could you perhaps contact us and meet us on Discord? The Beetle PSX dynarec guys are stuck on this issue and they'd really appreciate somebody like you being able to brainstorm with them on how they go around fixing this issue. The persons in question are zcrc and @ZachCook .

In case you're interested, please contact Autechre on Libretro discord and I'll add you to the chan.

**Comment by ZachCook** [comment]
Should be fixed by 3f7fe0deeb6f385c243afdff7d4fb38436f88d24

**Comment by Tatsuya79** [comment]
Tested working in the software core, 3 frames in Little Ralph working fine. :+1: 

Awesome! thanks for fixing that, closing the issue.
