### ISSUE TITLE
Android OpenGL (Beetle PSX HW) - Unable to find or open hardware renderer

### ISSUE THREAD

**Issue by tabnk** [libretro/beetle-psx-libretro#593]
# First and foremost consider this:
- This is a DEVELOPER oriented channel dedicated to report bugs and suggest features about the libretro core, please do not ask for help;
- The upstream bug tracker is a forum thread, located at https://forum.fobby.net/index.php?t=msg&th=1114;
    - Note: As of October 2018, Microsoft email providers (think email addresses ending with hotmail/live/outlook) are rejecting email from the forum. If you want to register an account in the upstream project's forum, consider using another mail provider.
- For game-related bugs:
    1) First, check if it's already reported on the upstream bug tracker;
    2) If it's not reported there, try to reproduce the bug with mednafen;
    3) If it's reproducible with mednafen, report it on the upstream bugtracker;
    4) If it's not reproducible with mednafen, ONLY THEN should you report it here.
    
## Description

OpenGL Driver. Unable to find or open hardware renderer ... . 

It auto switch to software mode.

### Expected behavior

Must stay in hardware mode.

### Steps to reproduce the bug

1. OpenGL Driver
2. Hardware Renderer
3. Load your PSX game.

### Core options

Default 

### Environment information

- Android 
- Latest Build
- Galaxy S7

**Comment by rz5** [comment]
The GL renderer in beetle-psx can't be built for Android:

https://github.com/libretro/beetle-psx-libretro/blob/5d4ecd68be89aa8bb7317a97d890e9bd173c91c9/jni/Android.mk#L25-L35

To put it simply, the renderer targets the [OpenGL API](https://www.khronos.org/opengl/) which is similar to the [OpenGL ES API](https://www.khronos.org/opengles/). But they're different enough where, if you tried to compile beetle-psx's GL renderer and pretended it was GLES compatible, you'd get these types of errors:

```C
[armeabi-v7a] Compile++ thumb: retro <= rsx_lib_gl.cpp
./beetle-psx-libretro/jni/../rsx/rsx_lib_gl.cpp:795:15: error: use of undeclared identifier
      'GL_DOUBLE'
         case GL_DOUBLE:
              ^
./beetle-psx-libretro/jni/../rsx/rsx_lib_gl.cpp:876:22: error: use of undeclared identifier
      'GL_DRAW_FRAMEBUFFER'
   glBindFramebuffer(GL_DRAW_FRAMEBUFFER, fb->id);
                     ^
./beetle-psx-libretro/jni/../rsx/rsx_lib_gl.cpp:930:18: error: use of undeclared identifier
      'GL_UNPACK_ROW_LENGTH'
   glPixelStorei(GL_UNPACK_ROW_LENGTH, (GLint) row_len);
                 ^
./beetle-psx-libretro/jni/../rsx/rsx_lib_gl.cpp:977:10: error: use of undeclared identifier
      'GL_DEPTH_STENCIL_ATTACHMENT'
         GL_DEPTH_STENCIL_ATTACHMENT,
         ^
./beetle-psx-libretro/jni/../rsx/rsx_lib_gl.cpp:1110:10: error: use of undeclared identifier
      'GL_UNSIGNED_SHORT_1_5_5_5_REV'
         GL_UNSIGNED_SHORT_1_5_5_5_REV,
         ^
```

Luckily, your phone has official support for Android 7+, so you should be able to use the Vulkan renderer instead, which should be better overall.

**Comment by tabnk** [comment]
Vulkan renderer seem run much slower than software renderer on my Galaxy S7.

**Comment by MegaDeox** [comment]
I'm getting this all of a sudden, even with Vulkan. Note 9. Not sure what happened.

**Comment by ggdrt** [comment]
@MegaDeox The code for renderer selection was updated a couple of days ago. If you're having problems even after updating the core, please open a new issue in the tracker and fill out the provided template. This issue thread you are posting in has long since been closed.
