### ISSUE TITLE
How do I use the Playstation Mouse in Retroarch?

### ISSUE THREAD

**Issue by AnotherLife** [libretro/beetle-psx-libretro#6]
Trying to use it to play with mouse the english translation of Policenauts. Also, where can I find a recent compile?  It seems this core is up to 0.9.38.x according to the commits but the one that the Core Updater of the nightly downloaded says it's based on 0.9.36.5

Thanks for your work :-D

**Comment by Hydro5** [comment]
I don't think PSX Mouse can work right now as it's not supported.

**Comment by fr500** [comment]
Indeed, it's not implemented

**Comment by hiddenasbestos** [comment]
Pull request #261 adds this feature.
