### ISSUE TITLE
[Feature Request] Increase CPU Frequency Scaling limit above 650%

### ISSUE THREAD

**Issue by rapierx** [libretro/beetle-psx-libretro#601]
Is it possible to increase overclock limit to above 650%? I'm using latest Beetle HW with 650% overclock, Dynarec enabled, GTE overclock... and Twisted Metal 4 needs more overclock when playing with cheats. Video with fps dropping: https://streamable.com/7koxn

CPU usage is higher than normal because I was recording the game with OBS. I think that my CPU can support 1000% CPU Frequency Scaling on this game or even more, Dynarec turned Beetle HW into a ultrafast core.

OS: Windows 10 1909
CPU: Ryzen 2700X
GPU: Geforce GTX 960 2GB

**Comment by i30817** [comment]
It's limited because at that point the bugs in games become more than unusual; you can't simply just overclock everything without consequences.

In fact, a while ago, in a bug report i don't recall, people wanted to limit one of the overclocks *more* because upstream mednafen fixed something in the drive emulation and a popular game stopped working overclocked with fix.

**Comment by ggdrt** [comment]
I've tentatively increased this further to 750%. We could increase this further if requested, but just keep in mind there are significant limits to how much support we can provide users for bugs related to high CPU overclocking.

**Comment by simias** [comment]
Given the severity of the framedrops in this video (at times it seems to drop to low single digits) I doubt you'll be able to significantly improve things solely with better CPU overclock.

**Comment by rapierx** [comment]
> Given the severity of the framedrops in this video (at times it seems to drop to low single digits) I doubt you'll be able to significantly improve things solely with better CPU overclock.

Yeah, that's true.  I just want to increase fps, but constant 30fps in this game in all situations using cheats is impossible.

**Comment by rapierx** [comment]
750% overclock + DMA/GPU Event Cycles 1024 increase performance as expected. The game is also crashing less.

**Comment by ggdrt** [comment]
Going to close this for now since it seems like your issues are alleviated.
