### ISSUE TITLE
Ninja: Shadow of Darkness not Start

### ISSUE THREAD

**Issue by ToniBC** [libretro/beetle-psx-libretro#602]
Hello, this game, the "Ninja: Shadow of Darkness" when you click on "Start Game", the screen goes black and does not continue.

Retroarch and Cores updated to the latest Nightly versions.
Core: Beetle PSX HW / Software
System: Windows 10 x64

All tested with the default settings and the same thing always happens.

**Comment by RinMaru** [comment]
works fine for me your dump is bad probably

**Comment by DonelBueno** [comment]
I also cannot reproduce this issue.

**Comment by rz5** [comment]
@ToniBC - If you can, check if your copy can be scanned by RetroArch. It would also help if you could list the exact version (USA, EU, v1.0, v1.1, etc) and what core options you're using on beetle-psx.

**Comment by ToniBC** [comment]
Yes, I had the redump of the game in its PAL version, "Ninja - Shadow of Darkness (I-S)", but apparently it was wrong, I searched for the new Redump that appeared in 2017 and starts without problems.

Thank you for confirming that it worked, because everyone who was there failed.
