### ISSUE TITLE
save states are freezing on load

### ISSUE THREAD

**Issue by klepp0906** [libretro/beetle-psx-libretro#604]
# First and foremost consider this:
- This is a DEVELOPER oriented channel dedicated to report bugs and suggest features about the libretro core, please do not ask for help;
- The upstream bug tracker is a forum thread, located at https://forum.fobby.net/index.php?t=msg&th=1114;
    - Note: As of October 2018, Microsoft email providers (think email addresses ending with hotmail/live/outlook) are rejecting email from the forum. If you want to register an account in the upstream project's forum, consider using another mail provider.
- For game-related bugs:
    1) First, check if it's already reported on the upstream bug tracker;
    2) If it's not reported there, try to reproduce the bug with mednafen;
    3) If it's reproducible with mednafen, report it on the upstream bugtracker;
    4) If it's not reproducible with mednafen, ONLY THEN should you report it here.
    
## Description

Save states created prior to the recent updates are loading straight to a freeze now.  I attempted to load a standard save with xenogears in order to create a new state and see if it would then work, but upon loading the memcard save, it requested disk 2 (odd that states dont but w/e) anyhow, the disk swap didnt want to work now either.

I moved on to wild arms which again, save state froze upon loading - however I was able to get in game with a standard memcard save.

### Expected behavior

Save states to function as intended of course.

### Actual behavior

Everything I tried freezes upon loading of the state.   The exception was FFT which I hadnt played previously.  As another step in a process of elimination i started a game, created a state, took a few steps sideways, and loaded the state and it worked.

### Steps to reproduce the bug

1. attempt to load a save state presumably created prior to the big update
2. freeze
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
[If you're using RetroArch, after the core has started, this information is on the bottom left]

- Beetle PSX: 0.9.44.1 9c64fe0

### Core options
[List all the core options you have changed]

### Environment information

- OS: Win10
- Compiler: [In case you are running local builds]
- GPU: 2080ti 441.87

**Comment by ZachCook** [comment]
Can you share a .state file that will not load, I've been trying to fix this but need a failing .state to test against.

**Comment by ZachCook** [comment]
Nevermind, finally found what I did that changed it, fixed in https://github.com/libretro/beetle-psx-libretro/commit/55ced791707f1b1d861719e8eef547e5773c343c

**Comment by klepp0906** [comment]
sorry, i had posted that just as i was crashing for the night.  Looks like you found it anyhow.  thank you!
