### ISSUE TITLE
Inconsistent playback pace during cutscenes videos on Chrono Cross when "CD Loading Speed" is higher than native

### ISSUE THREAD

**Issue by MarcoEstevez** [libretro/beetle-psx-libretro#607]
I noticed video playback run odd on later core releases, it shows an inconsistency pace, reproduction accelerates and slows down periodically.

I tired out change several settings with no results like latest Dynarec, resolution even graphic API.

I tested the non-HW Beetle PSX core flavour and this one runs flawless, so I susppect something has regessed on latest builds

_to reproduce it, chose new game and watch intro cutscene._

**Comment by ggdrt** [comment]
Are you able to do a bisect to determine when this began occurring?

**Comment by MarcoEstevez** [comment]
I cant see how, is there any way to download older cores?

**Comment by ggdrt** [comment]
Do you know which of the renderers (OpenGL, Vulkan, or software) you were running this on? Beetle PSX HW is able to run in all three of those modes. 

I'm unable to reproduce this on Windows 10 and Ubuntu 16.04 so we can't help you without more details. It would help if you could fill out the template that's given to you whenever opening a new issue in this repository.

**Comment by MarcoEstevez** [comment]
Will do a more extensive tests later on, to see whether I spot and under what circunstances the issue occurs

**Comment by MarcoEstevez** [comment]
I did remove all PSX_ settings presents on retroarch-core-options.cfg, and bug disappeared, then I added one by one previous settings and it turned out that was "CD Loading speed" higher than Native the one causing the issue.

I feel we can close this issue since was just me being an idiot :-D

**Comment by simias** [comment]
Normally the CD "overclocking" code tries to guess if it's safe to speed up or not depending on what the games seems to be doing, I guess Chrono Cross does something uncommon that gives a false negative. Maybe we could disable the overclock if the MDEC is active or something like that.
