### ISSUE TITLE
[Feature Request] Allow shaders to run before internal res upscaling

### ISSUE THREAD

**Issue by Thrakk** [libretro/beetle-psx-libretro#616]
If it’s possible to run shader operations before internal resolution upscaling, I would love the option to do so. It would solve many problems people have with 2D/3D mix games. Currently many shaders don’t work well when running internal resolutions higher than 1X.

**Comment by hizzlekizzle** [comment]
It's not possible, unfortunately.

**Comment by simias** [comment]
Could you give us a concrete example of what you have in mind? I'm not really sure I get what you're asking.

**Comment by ggdrt** [comment]
@Thrakk I'm going to close this issue. If you can provide specific examples perhaps we can suggest some alternatives.

**Comment by Thrakk** [comment]
http://www.framecompare.com/image-compare/screenshotcomparison/DZDDPNNX
^both are running ScaleFX but the shader has less of an effect at higher internal resolutions
