### ISSUE TITLE
[Beetle PSX HW] BIOS and FMV graphical glitch - GP1(00h) issue

### ISSUE THREAD

**Issue by ggdrt** [libretro/beetle-psx-libretro#619]
Two graphical glitches caused by the same issue; filing this for documentation purposes.

Possibly a duplicate of #287 but the externally hosted images in that issue are long since down.

Example 1: BIOS glitches out momentarily after the normal BIOS animation when loading certain titles (e.g. Metal Gear Solid, Final Fantasy Tactics)

![](https://user-images.githubusercontent.com/45282415/75312782-dd5f8580-580f-11ea-9178-89c53a6dc13c.png)

Example 2: FMV glitches out on first few frames for certain titles (e.g. Wild Arms opening FMV)

![](https://user-images.githubusercontent.com/45282415/75312787-dfc1df80-580f-11ea-8665-812f139e6783.png)

Caused by a missing `rsx_intf_toggle_display()` call when the emulated GPU is being reset. Solved by 807bc73.

**Comment by simias** [comment]
Oh nice catch! I noticed this problem but never managed to figure out what caused it.
