### ISSUE TITLE
Core cannot be compiled on Windows

### ISSUE THREAD

**Issue by barisyild** [libretro/beetle-psx-libretro#635]
Although I try on 2 different computers, I get the same error.

i'm building with `make platform=windows` command

![image](https://user-images.githubusercontent.com/25794892/78171771-a52a1300-745d-11ea-8432-e2f2ce21b414.png)

I did the whole installation by following.
https://docs.libretro.com/development/retroarch/compilation/windows/#building-cores

**Comment by ggdrt** [comment]
There's no need to pass in `platform=windows`, this part of the Makefile should figure it out for you. Make sure that you're using the MSYS2 MinGW shell and not the MSYS2 MSYS shell.

https://github.com/libretro/beetle-psx-libretro/blob/ea0dd62473caa027364bb37211df3777f447f3f0/Makefile#L27-L42
