### ISSUE TITLE
"Failed to set last used disk" 

### ISSUE THREAD

**Issue by SonGokuu** [libretro/beetle-psx-libretro#639]
Every game I try, for a while now, in .PBP format, causes RetroArch to tell me the message: "failed to set last used disk". (both cores, Beetle PSX HW and standard)
The game works. And I have compressed them into .PBP with PSX2PSP. But that message is displayed and I don't know why.
A friend of mine tried and said the same message. So it is not a matter of my PC.
Is there something wrong with .PBP?

### Environment information

- Frontend: RetroArch 1.8.5
- OS: Windows 10 Home , Build 1909.
- GPU: NVIDIA GTX 1080Ti.

**Comment by ggdrt** [comment]
See if this is fixed in the latest update.

**Comment by SonGokuu** [comment]
It's solved. You're a genius!
Thank you very much.

**Comment by ggdrt** [comment]
Resolved by #638
