### ISSUE TITLE
FFIX graphic clitches

### ISSUE THREAD

**Issue by mjuzikfrik** [libretro/beetle-psx-libretro#64]
Since a few days ago I've been experiencing strange bugs. I've made some snaps of it. Everything is set to default. Software renderer not opengl. 
One the first picture there's the issue of ?shadow? on the left of the box. And the next three show some strange lines, points on the forests when moving.
![retroarch-0608-172355](https://cloud.githubusercontent.com/assets/16630872/15900520/145a9ece-2da0-11e6-818b-f42101494d47.png)
![retroarch-0608-173201](https://cloud.githubusercontent.com/assets/16630872/15900521/147381aa-2da0-11e6-948b-d5bdbd87bd0a.png)
![retroarch-0608-173214](https://cloud.githubusercontent.com/assets/16630872/15900523/148a8ca6-2da0-11e6-9bdc-8f4b141e77ee.png)
![retroarch-0608-173238](https://cloud.githubusercontent.com/assets/16630872/15900522/14899ee0-2da0-11e6-9205-061f6f0688d4.png)

**Comment by simias** [comment]
What's the problem in your first screenshot exactly? I don't see this shadow you're talking about.

**Comment by mjuzikfrik** [comment]
I think I have put it into wrong words. I mean the line I've showed on this picture.
![retroarch-0608-172355](https://cloud.githubusercontent.com/assets/16630872/15901628/53c57f62-2da4-11e6-8c84-58b9c87143fb.png)

**Comment by simias** [comment]
Ah, the other left :)

**Comment by twinaphex** [comment]
Could be the changes I made to GTE where I tried to make the code more like Rustation's. Id invite simias there to doublecheck what I did there in case I made some mistakes.

**Comment by simias** [comment]
We'd have to bisect until I can isolate the commit that introduced the regression. Seems odd that the GTE would introduce a regression on 2D graphics though.

Can I get a savestate of FFIX on the map?

**Comment by personaone** [comment]
I can confirm these issues are also present in FF7 - polygon edges have weird colors like the map screenshots, also the scroll handle in the item inventory has a corruption on the right side of it.

**Comment by mjuzikfrik** [comment]
Here's the savestate. I'm using USA-NTSC version.

**Comment by personaone** [comment]
Shots of FF7 issue.

http://imgur.com/5J7Uhtg

http://imgur.com/Cs3pSTY

**Comment by simias** [comment]
@mjuzikfrik thank you, I can reproduce it here. I'm currently tracking down the commit that caused the regression.

**Comment by simias** [comment]
Apparently it was caused by [this commit](https://github.com/libretro/beetle-psx-libretro/commit/d7e6d83b02ebaa383d70da7f62248f0d8c02303e).

I don't quite understand what's the point of that, can't MSVC optimize simple bitshifts correctly on its own? What does "fx32" mean here? I'm not sure we gain anything from this commit besides obfuscating bitshifts and a free regression for our troubles.

**Comment by rz5** [comment]
@simias: Seems @twinaphex was refactoring beetle-psx, getting it to use more libretro parts and such. And since you can't compile it with MSVC anymore, you can safely assume these bugs are happening with GCC.

**Comment by simias** [comment]
@rz5 right, but my point is that I don't understand the point of this particular commit, MSVC or not. I don't understand why this `fxp.h` is in libretro-common when I can't imagine fixed point 20.12 arithmetic is *that* common in the wild.

I don't really understand why it causes a regression either mind you. Could be something to do with a logical/arithmetic right shift or something changing the behaviour of integer promotion.

IMO I'd be for reverting this commit altogether, but I'm going to wait for @twinaphex's opinion on the subject, maybe he has a good reason for making this change.

**Comment by saftle** [comment]
Would any of the more recent bugs that were added to the GL Renderer Bug thread be related as well?

**Comment by simias** [comment]
@saftle I'm not sure but I don't think so.

**Comment by saftle** [comment]
@simias ok thanks.

**Comment by twinaphex** [comment]
@simias I already fixed a previous regression in that commit here -

https://github.com/libretro/beetle-psx-libretro/commit/d7e6d83b02ebaa383d70da7f62248f0d8c02303e#diff-6c5e302cc1da48dbaafda2d1ac4be8b2L84

So I'd just like to find out which other line currently is causing the regression.

As for why I'm doing this, these are functions used by Desmume which is now going to be using libretro-common more and more for its core emulation code, so I thought it would be a good idea to bring the functions to libretro-common and to also use them in other emulators that rely on fixedpoint. There is also a potential PS1 RetroArch port coming up where any usage of float will be very heavily penalized, so I'd like to start looking at ways to bring fixed-point handling to libretro-common in a sane way. Same for Nintendo DS which also doesn't have an FPU. Doesn't mean we are going to be changing everything over to fixed point but just to have some common helper functions in there in libretro-common can't hurt.

**Comment by twinaphex** [comment]
https://github.com/libretro/beetle-psx-libretro/commit/9b1e98e408273aef170a283f6e4bb973e252f50a

Check if this fixes it.

However, I'd still like a savestate or a way to reproduce this issue though since I'd still like to go through these inlined functions eventually for code clarity.

**Comment by simias** [comment]
@twinaphex Thanks! It seems to fix the issues in the FFIX savestate provided by @mjuzikfrik at least.

**Comment by mjuzikfrik** [comment]
Great! I see no lines or dots now. What about that border to the right of the tables in the menu battle summary? It should be like at the bottom with out the extra grey line.

**Comment by simias** [comment]
@mjuzikfrik I don't notice this issue with the latest version using the software renderer:

![retroarch-0609-165851](https://cloud.githubusercontent.com/assets/7925386/15934345/8502f680-2e63-11e6-8681-0a7de10edd95.png)

**Comment by personaone** [comment]
It looks like the weird polygon colors are indeed gone, however the 2d issue in FF7 persists.

**Comment by twinaphex** [comment]
what 2D issue, and where can I reproduce this?

**Comment by simias** [comment]
@personaone I don't see any problem in FF7 at 1x software with the latest version:

![retroarch-0609-172928](https://cloud.githubusercontent.com/assets/7925386/15935507/c536ac34-2e67-11e6-96c2-d85d5009497c.png)

**Comment by personaone** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8123295/15935486/aefab80c-2e67-11e6-87e4-f297a0d9cb51.jpg)

Also i just ran FF9 to see that right side line thing, for me it's still there:

![22](https://cloud.githubusercontent.com/assets/8123295/15935536/e063a4da-2e67-11e6-891e-c1ce01f6d815.jpg)

That's weird cause I have just update the PSX core from the online updater

**Comment by simias** [comment]
I think you must be running an older version, not sure how up to date the online build is:

![retroarch-0609-173441](https://cloud.githubusercontent.com/assets/7925386/15935736/a62533be-2e68-11e6-995c-0f04367d7039.png)

**Comment by personaone** [comment]
I don't know it's kind of weird that I don't see the weird polygons on 3d objects anymore and the 2d ones are off, I guess i'll wait a few days and try again. Cheers.

**Comment by simias** [comment]
The buildbot giveth, the buildbot taketh.

**Comment by mjuzikfrik** [comment]
Weird... I'm in the same situation as personaone. Will check again tomorrow.

**Comment by personaone** [comment]
I just cloned the repo and compiled the core myself, that 2D thing in FF7 is still appearing, I'm really puzzled to what's causing it o_O

**Comment by simias** [comment]
@personaone Using Software or GL? Which internal resolution? Can you provide a savestate?

**Comment by personaone** [comment]
I always use software, all default running at 1x. 
[ff7.state.zip](https://github.com/libretro/beetle-psx-libretro/files/307615/ff7.state.zip)

**Comment by simias** [comment]
Damn you're right, it seems my core was outdated somehow. I'm going to try to figure out what caused that then.

**Comment by simias** [comment]
I end up on the [same commit](https://github.com/libretro/beetle-psx-libretro/commit/d7e6d83b02ebaa383d70da7f62248f0d8c02303e) when I bisect, it's the same code that introduced the regression. Maybe the revert wasn't complete?

**Comment by mjuzikfrik** [comment]
Any progress with that second issue?

**Comment by Bracket-** [comment]
It was only a partial revert; completely reverting d7e6d83b02ebaa383d70da7f62248f0d8c02303e fixes the issue.

Here's a patch that reverts d7e6d83b02ebaa383d70da7f62248f0d8c02303e and related commits:
[https://gist.githubusercontent.com/anonymous/../0001-beetle-psx.patch](https://gist.githubusercontent.com/anonymous/33a79b742dabe2b32adcd739dcfebd76/raw/382eda1f5408d73d1dd9fefdfed0d7d4a3e576b9/0001-beetle-psx.patch)

I didn't really bother checking whether I reverted all necessary commits or not, just that `git revert` was happy and the core built.

**Comment by twinaphex** [comment]
Applied  the patch, sorry about putting you guys through this for some rather unnecessary code readability sensibilities. I guess it's not really important to use the fxp.h header for this.
