### ISSUE TITLE
[Beetle PSX HW][Vulkan] Filtering sprites in 3d games

### ISSUE THREAD

**Issue by EtSL33py** [libretro/beetle-psx-libretro#648]
## Description
Problem happens in games with 3D environment. Sprite alpha-channel not filtered or filtered incorrectly. With any filter, sprites have artifacts at the edges. I tried to pictured what is happening:
![vh2s](https://user-images.githubusercontent.com/19521365/81435210-2321be00-9170-11ea-945b-a12f0ee77b59.png)
### Actual behavior
![bof4](https://user-images.githubusercontent.com/19521365/81436222-c7f0cb00-9171-11ea-8075-99c6306371f5.png)
![fm3](https://user-images.githubusercontent.com/19521365/81436226-c9ba8e80-9171-11ea-9f38-3613a4c4b505.png)
![vh2](https://user-images.githubusercontent.com/19521365/81436229-cc1ce880-9171-11ea-91df-d9a22da9f27f.png)
![bof3](https://user-images.githubusercontent.com/19521365/81436235-cd4e1580-9171-11ea-9638-22f315b7c811.png)
### Expected behavior
This screenshots from opengl
![bof4gl](https://user-images.githubusercontent.com/19521365/81436354-0ab2a300-9172-11ea-8d58-47b2718d82ab.png)
![fm3gl](https://user-images.githubusercontent.com/19521365/81436364-0be3d000-9172-11ea-9200-2a7cb12e69c5.png)
![vh2gl](https://user-images.githubusercontent.com/19521365/81436368-0dad9380-9172-11ea-9181-b7df61d0a4d4.png)
![bof3gl](https://user-images.githubusercontent.com/19521365/81436371-0edec080-9172-11ea-8ef0-60a328d9b368.png)
### Version/Commit
Beetle PSX HW 0.9.44.1 9e0e95b
### Core options
Default options, only vulkan and any texture filter
### Environment information
- Frontend: Retroarch 1.8.5
- OS: Windows 10 1809 x64
- GPU: RX470 Adrenalin 20.4.1

**Comment by hizzlekizzle** [comment]
This is a result of the way PS1 handles transparency. It's not like normal alpha, and this is actually the *improved* version.

see: 11e1db403381e4a19267b1af8281047280f43799
