### ISSUE TITLE
Regression in Parasite Eve 2?

### ISSUE THREAD

**Issue by TransparentBlue** [libretro/beetle-psx-libretro#65]
While checking for bugs with the GL renderer and making sure they weren't also happening with the software renderer I stumbled upon that issue where colored dots pop up near 3D elements

![retroarch-0608-161853](https://cloud.githubusercontent.com/assets/16150597/15897984/cd55ff86-2d96-11e6-9198-298b9cfd268e.png)

At first I thought this was exclusive to the core with the GL renderer because it didn't happen with the core that didn't have it but then I realized that I hadn't updated the core without the GL render in a while and after updating it the issue was present in both. sadly I forgot to take a screenshot of that issue not being present in a somewhat recent build (around may 31st) but I managed to find a much older build (feb 13th) and it doesn't have it either.
![retroarch-0608-171819](https://cloud.githubusercontent.com/assets/16150597/15900460/e7bf6642-2d9f-11e6-92ca-7fcbc47429cb.jpg)

It also does not happen at resolution higher than native as seen here,
![retroarch-0608-161950](https://cloud.githubusercontent.com/assets/16150597/15897983/cd54960a-2d96-11e6-80a3-8c74b561ebef.png)
and it doesn't seem to be affected by any other option.

Here's a save as close as possible to the spot I used and a savestate in case you need it. [link](https://dl.dropboxusercontent.com/u/38375252/Parasite%20Eve%20II%20%28USA%29%20%28Disc%201%29.zip)

~~On a sidenote as unlikely as it might seem updating the non HW core might have changed some behavior in the HW enabled one, namely a similar colored dots problem at one specific point of the game and another one involving 3D elements disappearing while inspecting objects / opening a menu that would fix itself until the next restart by switching "Show full VRAM" on and off without going back to the game inbetween.~~ Nevermind those two things are caused by having "Software framebuffer" on I just forgot to doublecheck what option I had on for testing to begin with.

**Comment by simias** [comment]
Looks like it might be related to #64.

**Comment by twinaphex** [comment]
I think we can fix this issue now right? Let me know if it still happens in case the issue still exists.
