### ISSUE TITLE
Crash Bandicoot 3 broken graphic when using dynarec

### ISSUE THREAD

**Issue by ds22x** [libretro/beetle-psx-libretro#650]
## Description

The latest update (commit a3bf813) seems to break the graphics in Crash Bandicoot 3.
![Crash Bandicoot - Warped (USA)-200511-133317](https://user-images.githubusercontent.com/45218067/81580843-3d48df80-93ae-11ea-80b4-62d89c167bd4.png)
![Crash Bandicoot - Warped (USA)-200511-133332](https://user-images.githubusercontent.com/45218067/81580857-420d9380-93ae-11ea-9a0b-4b7b9ba1dc75.png)

Happens on both Windows and Android, using both software and hardware renderers, utilizing both default dynarec settings at max performance, and cycle accuracy check.

**Comment by pcercuei** [comment]
Fixed in https://github.com/pcercuei/lightrec/commit/126845d
