### ISSUE TITLE
Final Fantasy VII HardType mod Black Screen

### ISSUE THREAD

**Issue by TesterNes** [libretro/beetle-psx-libretro#651]
Trying to get work Final Fantasy VII Hardtype mod by GalenMyra on Beetle psx software/hardware. 

[Description of the bug]

### Expected behavior
When you've selected "New Game" from the main menu the introduction video plays. 

### Actual behavior
When you've selected "New Game" from the main menu you have an "eternal" black screen instead the introduction video.

### Version/Commit
Beetle PSX 0.9.44.1 a3bf813

### Core options
Interpreter and dynarec modes are tested. 

### Environment information
- OS: Win10 64b

**Comment by simias** [comment]
Is this mod known to work on real hardware? Mednafen/Beetle tend to be more finicky with these things than some other emulators.

**Comment by TesterNes** [comment]
@simias Yes. I've tested it on real hardware and it works flawlessly.

**Comment by TesterNes** [comment]
I solved the issue using ECCRegen 1.41. A software that can repare bad CD-roms sectors. 
It seems after I patched the .bin image of FFVII, bad sectors came across somehow. 
Despite my original Playstation can handle it, Beetle psx couldn't and needed the sector fixed using the software I've mentioned before.
