### ISSUE TITLE
[Feature Request] Dynamically switch memory cards

### ISSUE THREAD

**Issue by rouhannb** [libretro/beetle-psx-libretro#658]
There are quite a few games, such as Xenogears, that allow you to save over multiple blocks in a memory card. I like to be able to maintain a backlog of saves so I can return to any point in the game or potentially collect anything I missed several hours back without restarting the game entirely. Of course, this means that I’d have to switch out lots of memory cards, especially for longer games.

As far as I can tell, memory cards are loaded and written when the core is opened and closed, so to switch memory cards I’d have to save in the right slot, close the core, switch the memory card in the left slot, and reopen the core. This can get a bit cumbersome (especially if the game only supports the left slot), so I was wondering if an option to dynamically switch out, or at least reload, the memory cards could be implemented.

**Comment by simias** [comment]
Depending on your configuration you can tell the emulator to dump memory cards while the emulator is still running. How to do that depends on the memory card method used but see Settings -> Saving -> SaveRAM Autosave Interval. I believe that this setting should work in beetle if you set the "Memory card 0 method" to "libretro". I haven't tested it though.

This way you'll be able to make copies of your memory-card in-game. You'll have to restart the emulator every time you want to swap the active card however.

An other possibility is to use savestates instead. Those are always instant and can be reloaded at any time.

**Comment by rouhannb** [comment]
Savestates are certainly an option, but they just aren’t really the same to me.  How much would it take to reload the memory card while the core is running?

**Comment by simias** [comment]
It probably wouldn't be too hard but I'm not convinced that it's desirable, the potential for corruption and loss of progress is rather high especially given the existing options. It might make more sense to add an option to select multiple cards with a core option (a bit like how you can select a savestate slot). This way you wouldn't have to mess around with external tools to move the files around. This way we also wouldn't have to keep monitoring the file on disc to see if it's changed, we'd just reload the save when the option's value changes.

The change probably wouldn't be too difficult to implement, at least when the memory card files are directly managed by the core and not the frontend. We might even be a bit clever about it and postpone the swap if we detect memory card activity to prevent corruption.

**Comment by rouhannb** [comment]
I have no idea whether work has been started on this or not (I wouldn’t think so, as this kind of feature isn’t exactly popular), so I decided to try giving a shot at it myself (https://github.com/rouhannb/beetle-psx-libretro/commit/d4e7da9ae58cc97984b17f86e8aba05996af1241). I don’t know if it’s good or bad, but as far as I can tell, it works perfectly fine (aside from the fact that there is nothing stopping someone from putting the same memory card into both slots).

If no other work has been started, could someone look over this implementation and see if it’s worth using?
