### ISSUE TITLE
Alternative BIOS filenames give a black screen instead of the "Firmware is missing" error.

### ISSUE THREAD

**Issue by bslenul** [libretro/beetle-psx-libretro#661]
## Description

If you have a BIOS named with any alternative filenames (I'm not a dev but I guess [these ones](https://github.com/libretro/beetle-psx-libretro/blob/master/libretro.cpp#L149-L192)?) you're not getting the "Firmware is missing" error message, instead you just get a black screen. It's not a crash, you can still open RetroArch menu and close the core normally for example.

The core seems OK with the filename:
```
[libretro INFO] Checking if required firmware is present.
[libretro INFO] Firmware found: D:\programmes\RetroArch\system\SCPH-5501.bin
[libretro INFO] Firmware SHA1: 0555C6FAE8906F3F09BAF5988F00E55F88E9F30B
```
but the games won't boot.

### Expected behavior

Either just work and load the game, or don't accept alternative filenames and show the "Firmware is missing" message.

I know the .info file and the docs say `scph5501.bin`, but it's crazy how many people don't think a simple hyphen or the case can matter... so it would be probably less confusing for the users and for the troubleshooting guys if the error appeared.

### Actual behavior

Games just show a black screen (and no audio).

### Steps to reproduce the bug

1. Rename `scph5501.bin` to `SCPH-5501.bin` for example.
2. Start a USA game and you should get a black screen.
3. (optional) Delete the BIOS and retry, you'll see that glorious "Firmware is missing" error :p 

### Bisect results

No idea, I compiled a build from December 2018 by curiosity and it was already happening.

### Version/Commit

Latest RetroArch 1.8.7 nightly (cebc01cd1e) and core nightlies too (cce646d), happening with both Beetle PSX or Beetle PSX HW.

### Core options

Defaults.

### Environment information

- OS: Windows 10 / Linux Mint

**Comment by negativeExponent** [comment]
show the logs, in any case it should still work.

**Comment by ZachCook** [comment]
Working on a fix now, the firmware check was previously completely disconnected from the way it opens the bios

**Comment by bslenul** [comment]
Nice, I didn't expect a fix so soon!

Just tried your PR (briefly tho, it's late here :p) and it seems to be working like a charm, I tested `scph-5501.bin` and `scph7003.bin` as USA BIOS filenames and the game loaded properly. Also tried with a hyphen on JPN and EUR BIOS filenames, games loaded just fine too.

Thank you for the fix! ❤️

**Comment by RinMaru** [comment]
bios files just dont work period for me  this is a ussie as of 1.9.0
