### ISSUE TITLE
Vulkan crashing with latest updates

### ISSUE THREAD

**Issue by bigol83** [libretro/beetle-psx-libretro#678]
## Description

When playing Persona (USA) and using L2 button to quick view map Retroarch crashes. It didn't crash until few hours ago using vulkan hardware renderer, than i updated to the newest version with the dump texure and custom textures options and it started to crash. 

It only crashes with Vulkan hardware. It doesn't crash with Opengl hardware or software renderer. It also doesn't crash if i choose the map from the ingame menu. 

### Expected behavior

Press L2, the map opens

### Actual behavior

Instead it just crashes Retroarch when using Vulkan renderer with Revelations Persona 

### Steps to reproduce the bug

1. Press L2 when ingame

### Bisect results

Probably after the dump textures/custom textures update

### Version/Commit

Beetle PSX HW: 0.9.44.1 6ebadc5

Using Beetle PSX HW.

### Environment information

- OS: Windows 10  ver.2004
- GPU: gt 1030 driver 446.14

**Comment by twinaphex** [comment]
Do you have Replace Textures turned off?

**Comment by twinaphex** [comment]
@stoofin Are you able to reproduce this?

**Comment by twinaphex** [comment]
@stoofin Perhaps when 'Replace Textures/Dump Textures' is disabled, all these codepaths shouldn't even be active to avoid the risk of crashes like this happening for games that don't even attempt to do any texture replacement.

**Comment by bigol83** [comment]
I tried to use Dump textures option the very first time and it crashed. I thought it was that option causing the crash but i tried several times with dump textures and replace textures off and still crashed.

**Comment by twinaphex** [comment]
Can you test if it works now after this commit?

https://github.com/libretro/beetle-psx-libretro/commit/7c023980ca208d13cb16ce26d657ad69ca62e8bb

**Comment by bigol83** [comment]
Yes the new commit fixed it with Track Textures option off. It doesn't crash anymore. Nice.
