### ISSUE TITLE
Doesn't detect another discs in multidisc pbp 

### ISSUE THREAD

**Issue by mjuzikfrik** [libretro/beetle-psx-libretro#68]
Hello,

I have official PSN pbp images of FFVIII and FFIX and when I got to the second disc it's always asking me to change to the right disc. It's also in the case of loading from a memory card.

**Comment by saftle** [comment]
It might be an obvious question, but figured I'd as: Are you using the hotkey to switch discs?

**Comment by mjuzikfrik** [comment]
There was no hotkey assigned to disk change. I have added a hotkey for next disk but nothing changed. Could you please tell me how should I go about changing discs? Maybe I'm doing something wrong.

**Comment by fr500** [comment]
you press the cycle tray hotkey, then the next disk hotkey and then the cycle tray hotkey again

**Comment by mjuzikfrik** [comment]
Yeah, that's what I did. I seems that there's something wrong with hotkeys on nightly builds?(I press the the key and nothing changes). It works on the stable release, though. Thank you!

**Comment by fr500** [comment]
On Thu, Jun 16, 2016 at 11:16 PM, mjuzikfrik <notifications@github.com>
wrote:

> Yeah, that's what I did. I seems that there's something wrong with hotkeys
> on nightly builds?(I press the the key and nothing changes). It works on
> the stable release, though. Thank you!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/libretro/beetle-psx-libretro/issues/68#issuecomment-226676768>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABpC0FiGySnVP611LNKKl-w1AtGtqb7hks5qMh-0gaJpZM4I3auU>
> .
>


​I just tried on the shield and it's working fine​

**Comment by saftle** [comment]
I haven't personally tried it myself, but vaguely knew how it worked. I'll try a Windows nightly build tonight.

**Comment by fr500** [comment]
I tried on windows this morning and it's working fine, can't repro, closing.
Feel free to comment here or reopen I guess

**Comment by mjuzikfrik** [comment]
I have come across a different issue now. Also multidisc pbp. When I load from a savestate disk index becomes null and the game freezes when it's supposed to go to load another scene.

**Comment by Kierek** [comment]
I encounter the same issue as @mjuzikfrik, I'm unable to use savestates with multidisc games after first disc. Pretty inconvenient if you ask me.
