### ISSUE TITLE
Load game from command line, ignores save directory setting

### ISSUE THREAD

**Issue by waitingmoon** [libretro/beetle-psx-libretro#69]
When load game from command line (-L mednafen_psx_libletro.dll image.cue), ignores save directory setting (RetroArch\saves) and created mcr file in content directory.

**Comment by fr500** [comment]
No. I tested this very thoroughly during the last weekend and I can't reproduce, tested the following codepaths:

- Single config, no save sorting, save directory set
Result: saves in the configured path
- Overrides enabled, no save sorting, save directory set
Result: saves in the configured path
- Single config, save sorting, save directory set
Result: saves in the configured path\Mednafen PSX
- Overrides enabled, save sorting, save directory set
Result: saves in the configured path\Mednafen PSX

Unless you're running an outdated version this is not happening right now.

**Comment by waitingmoon** [comment]
mcr in content directory, srm in retroarch\saves directory, Even with the unzipped RetroArch.7z.

**Comment by fr500** [comment]
Can't reproduce.  Paste your cfg I guess

**Comment by waitingmoon** [comment]
Sure. Here it is
include retroarch.cfg, retroarch.default.cfg, retroarch-core-options.cfg
[](https://dl.dropboxusercontent.com/u/71953424/retroarch.zip)

Command line:
E:\Emulator\RetroArch\retroarch.exe -L "E:\Emulator\RetroArch\cores\mednafen_psx_libretro.dll" "E:\Play Station\image.cue"
