### ISSUE TITLE
Option to remove second memory card

### ISSUE THREAD

**Issue by Warriors-Blade** [libretro/beetle-psx-libretro#7]
Certain games like Codename Tenka need only the first memory card in to play and both are inserted and I see no way to remove the second memory card, any ideas on fixing this issue?

**Comment by Warriors-Blade** [comment]
Just wondering if anyone is ever going to look into this since mednafen vanilla is able to remove memory cards.

**Comment by simias** [comment]
I've made a patch that adds a core option to disable the Memory Card 1: https://github.com/simias/beetle-psx-libretro/commit/586b1acacba47bc371446936f0be039833789797

It's a bit hacky though, a cleaner option would be to change the mednafen option `"psx.input.port2.memcard"` to set it to 0 but I don't know how to do that dynamically in beetle.

If nobody knows how to do it better maybe we could merge this one, it's not like it's a big modification anyway.

**Comment by simias** [comment]
I should add that "Memory Card 1" is the 2nd one here, I'm starting from 0. That means the memory card on physical slot 2.

**Comment by simias** [comment]
Okay I've merged this patch on master, maybe somebody will come up with a better implementation later on but that should let us make sure that this fixes the issues with "Codename Tenka" at least.

The option is called "Enable memory card 1" (indexed from 0, so memory card 1 would be the one in physical slot 2). It's set to "enabled" by default.

**Comment by Warriors-Blade** [comment]
simias added this implantation and it works well, thanks alot for working on it.

Il close this now that it is solved.
