### ISSUE TITLE
Fantastic Pinball Kyuutenkai - Screen stays black after selecting Memory Card

### ISSUE THREAD

**Issue by Pat86** [libretro/beetle-psx-libretro#70]
After selecting a memory card to use (or no memory card) the screen stays black, but the music plays.

![retroarch-0624-151038](https://cloud.githubusercontent.com/assets/20128108/16338575/eb49246c-3a1d-11e6-9f0f-41cb1207aa72.png)

This video begins with what should follow, but only the music plays.

https://www.youtube.com/watch?v=0BZHptG-h7I

**Comment by OptimalJew** [comment]
Works on the latest version.

![fantastic pinball kyutenkai ntsc-j slps-00031 -171008-193959](https://user-images.githubusercontent.com/31424143/31322165-8a23bb5a-ac60-11e7-8d81-713c2064d7bb.png)

**Comment by rz5** [comment]
@Pat86, remember to check if it works for you too. Closing it.

**Comment by Pat86** [comment]
It works, thanks.
