### ISSUE TITLE
Mednafen PSX core no longer compiling for tvOS and iOS

### ISSUE THREAD

**Issue by mrjschulte** [libretro/beetle-psx-libretro#702]
The mednafen_psx core is no longer compiling for arm64 on tvOS and iOS. 

same error for tvOS and iOS:
_Undefined symbols for architecture arm64:
  "___clear_cache", referenced from:
      __emit_code in lightning.o
      _jit_flush in lightning.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mednafen_psx_libretro_tvos.dylib] Error 1_

@yoshisuga any ideas what could have caused this? I have a build working for both dated back in Dec 22, 2019 so perhaps this has been like this for a while now?

**Comment by twinaphex** [comment]
We could probably get it building again by just excluding lightrec/lightning for now for iOS.

Ideally we'd get it working on iOS though. @ZachCook any thoughts?

**Comment by mrjschulte** [comment]
Yeah, that was it. I'll put in a quick Pr to exempt iOS/tvOS from getting lightREC.

**Comment by mrjschulte** [comment]
And we're good again, thanks @twinaphex
