### ISSUE TITLE
[Vulkan] Internal resolution higher than 1x result in black outlines for certain 3D models of Vagrant Story

### ISSUE THREAD

**Issue by Blakrajder** [libretro/beetle-psx-libretro#704]
## Description

In Vagrant Story game uses sort of a trick to create illusion of DoF/Blur when object or character stands close to camera by, from what I can tell, duplicating it’s 3D model on black background into VRAM, slightly enlarging it and changing its transparency.
When using internal resolution of anything other than 1x you end up getting artifacts at the edges of the models due to the black background of the model not being removed properly.

### Expected behavior

Beetle PSX, internal resolution 4x, look at the right character "doubled" model, no artifacts
![SW x4](https://forums.libretro.com/uploads/default/original/2X/9/9baac15a30774f7eab03863102ee80fb7eeb00bb.png)

### Actual behavior

Beetle PSX HW, internal resolution 4x, look at the right character "doubled" model, black outline artifacts
![HW x4](https://forums.libretro.com/uploads/default/original/2X/3/35036a7c2547a8006249dc4ce32fd3191dc100ea.jpeg)

### Steps to reproduce the bug

1. Play Vagrant Story using Beetle PSX HW core
2. Watch cutscenes to witness black outline artifacts whenever fake DoF/Blur is shown

### Bisect results

When checking Display Full VRAM you can see the 3D model on the black background in the bottom right of the display whenever the object will be used for DoF/Blur effect

VRAM preview example 
![Vagrant Story (USA)-200811-105509](https://user-images.githubusercontent.com/69497361/89879121-c1378100-dbc2-11ea-89b6-d56f78342b95.png)

Duckstation, different PSX core for the Retroarch using Vulkan as a renderer is not having any problems rendering the scene properly even at 8x the internal resolution.

Duckstation, internal resolution 8x
![Vagrant Story (USA)-200811-094027](https://user-images.githubusercontent.com/69497361/89879893-de208400-dbc3-11ea-8b71-89c23613a21c.png)

Changing other core options for Beetle PSX HW produces same results. Only internal resolution scaling is at fault.

### Version/Commit

Beetle PSX HW: (0.9.44.1 9f126e5)

### Core options

Renderer: Hardware
Internal GPU resolution: 4x
Dithering Pattern: OFF

Rest of the settings at default.

### Environment information

- Frontend: Retroarch 1.9.0 
- OS: Windows 7 SP1
- GPU: Nvidia GTX 970

**Comment by Blakrajder** [comment]
> 
> 
> Do you have a savestate where this cutscene happens? I'm interested in testing it.
@xzn 
Cutscene happens in the introductory sequence, so one option is to just watch the intro and about 4min in you encounter it.
If you don't want to wait, I attach the savestate that is right before the cutscene.
Going with the savestate you can notice another instance of the glitch when the camera starts panning and and shows a column in the foreground to the left of main character.

[VS_ss.zip](https://github.com/libretro/beetle-psx-libretro/files/5140993/VS_ss.zip)

**Comment by xzn** [comment]
OpenGL backend doesn't seem to have this bug. It doesn't look as good as Duckstation though.

It's not hard to change the Vulkan backend to behave like the OpenGL one but I'm guessing it wouldn't be good enough to resolve this issue.

<img width="960" alt="vulkan test" src="https://user-images.githubusercontent.com/1617680/91560598-792d9380-e910-11ea-9ceb-ae7855af052a.png">

**Comment by xzn** [comment]
Second attempt:

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/1617680/91585632-b1da6680-e92a-11ea-81f0-9e331dcd255e.png">

**Comment by Blakrajder** [comment]
Yea. OGL doesn't have this problem, but have plethora of framebuffer issues.
Anyways, Vulkan is where the problem lies and where it needs to be resolved :]

Second attempt looks promising, if it is on Vulkan. How does it look though without the texture filtering and shaders?
Just native resolution set to 4x, no other improvements.

Wild thought: Would it be possible to port some of the Duckstations Vulkan rendering calls to Beetle? The way it's done there could be a solution.

**Comment by Blakrajder** [comment]
Another note.
It is possible, that black outlines glitch visible here could be related to black outline errors in other titles.
One that comes to mind is Persona 2: Tsumi, based on the topic from libretro forums: [link](https://forums.libretro.com/t/beetle-psx-hw-issue-with-graphics-persona-2-tsumi/24587)

**Comment by xzn** [comment]
If you don't mind installing custom core give this a try: [mednafen_psx_hw_libretro.zip](https://github.com/libretro/beetle-psx-libretro/files/5152451/mednafen_psx_hw_libretro.zip)

MSAA is still broken however so make sure that's turned off. (I've also had some incomplete changes that made MSAA really slow so just don't use it with the file I uploaded).

I believe I've gotten rid of most of the bugs aside from MSAA support so there should be a PR ready soon.

If you do test this build make sure to report any bugs you find, such as game running too slow and so on.

**Comment by Blakrajder** [comment]
Heck yes, I will test it!
I never use MSAA, I prefer Supersampling, so no problem for me.
I will have to check other titles, but for now it is good when it comes to Vagrant Story. :D 
Bellow are few screens of working fix.
Take a notice of 16x with Supersampling ON, looks like it doesn't scale down the image properly, creating a lot of aliasing issues along with "jumping" textures whenever camera moves or switches angle. 
Unless it is related to MSAA, but I have it set to 1x, which should equal to OFF.
It is sorta affecting lower internal resolutions as well when downsampling is enabled, but it's not so noticeable.

Custom core, 16x, Adaptive Smoothing ON, Supersampling OFF, Shader: Natural Colours
![Vagrant Story (USA)-200901-110855](https://user-images.githubusercontent.com/69497361/91830836-954c7000-ec43-11ea-84eb-1ffc5d312811.png)

Custom core, 8x, Adaptive Smoothing ON, Supersampling ON, Shader: Natural Colours
![Vagrant Story (USA)-200901-110514](https://user-images.githubusercontent.com/69497361/91830536-3129ac00-ec43-11ea-89b7-ce43715aaf3e.png)

Custom core, 16x, Adaptive Smoothing ON, Supersampling ON, Shader: Natural Colours | --noticeable downscaling aliasing issue
![Vagrant Story (USA)-200901-111017](https://user-images.githubusercontent.com/69497361/91831155-01c76f00-ec44-11ea-884e-7a0696b204e5.png)

Official core, 16x, Adaptive Smoothing ON, Supersampling ON, Shader: Natural Colours | --no aliasing issue, just black outline
![Vagrant Story (USA)-200901-113005](https://user-images.githubusercontent.com/69497361/91833338-ddb95d00-ec46-11ea-9156-4447187a5684.png)

**Comment by Blakrajder** [comment]
Custom core issues in other games.
All seem to be related to Supersampling. If it's OFF, everything is fine. Set to ON, issues start occurring.


**Legacy of Kain: Soul Reaver**
[video of the problem](https://youtu.be/u5p_7Y_NeXE)
Custom core, 8x, Supersampling ON | --Screenshot is not capable of showing the constant flickering of the remaining portion of menu.
![Legacy Of Kain Soul Reaver  NTSC -200901-115956](https://user-images.githubusercontent.com/69497361/91836642-5fab8500-ec4b-11ea-8fb9-bb1f899768ca.png)

Custom core, 8x, Supersampling OFF | --No flickering occurs.
![Legacy Of Kain Soul Reaver  NTSC -200901-120023](https://user-images.githubusercontent.com/69497361/91836965-ce88de00-ec4b-11ea-8bd9-4adfe67373fe.png)


**Dino Crisis 2**
[video of the problem](https://youtu.be/gG6OkO1oeqg)
Custom core, 8x, Supersampling ON | --Static background of main menu is not shown
![Dino Crisis 2  SLUS-01279   U   bin+cue -200901-123622](https://user-images.githubusercontent.com/69497361/91840628-4a395980-ec51-11ea-81e3-636b4c07d42c.png)

Custom core, 8x, Supersampling OFF | --Main menu visible as it should be
![Dino Crisis 2  SLUS-01279   U   bin+cue -200901-123641](https://user-images.githubusercontent.com/69497361/91840737-75bc4400-ec51-11ea-80e4-36a56651aa70.png)

**Comment by xzn** [comment]
[mednafen_psx_hw_libretro.zip](https://github.com/libretro/beetle-psx-libretro/files/5156366/mednafen_psx_hw_libretro.zip)

Let me know if this get rid of flickering (I made a dumb mistake apparently). Don't really know about aliasing issue though?

**Comment by Blakrajder** [comment]
Well aliasing issue when Supersampling-ON is gone with your latest build.

Custom core, 16x, Adaptive Smoothing ON, Supersampling ON, Shader: Natural Colours | --no issues with aliasing when downsampled
![Vagrant Story (USA)-200901-160005](https://user-images.githubusercontent.com/69497361/91860819-6ac2dd00-ec6c-11ea-93ae-b094ec156cc6.png)

Sadly the flickering remains.
[remaining issue](https://youtu.be/wp58z1wCVbE)

**Comment by xzn** [comment]
[mednafen_psx_hw_libretro.zip](https://github.com/libretro/beetle-psx-libretro/files/5156990/mednafen_psx_hw_libretro.zip)

You might've guessed it but it's another dumb mistake on my part :(

Sorry for all the trouble.

**Comment by Blakrajder** [comment]
No trouble at all. Mistakes happen. Hence we're working together to catch them and eliminate them. :]
You're fixing few bugs at the same time. You missed one and now you fixed it.

Your newest build.
All I can say is GREAT JOB, WELL DONE.
Black borders in Vagrant Story on internal resolutions higher than 1x are gone.
There is no flickering nor missing textures in other games that I've tested.

I'll be playing around with few more titles to see if anything else might pop. But I have nothing but praise for your work so far. :D

**Comment by Blakrajder** [comment]
New find.

**Valkyrie Profile**

You can see gaps between certain sprites that should be shown as one when internal resolution is higher than 1x.
Only internal resolution is the culprit for this. Other options don't affect it.

Custom core, 8x
![Valkyrie Profile-200901-182310](https://user-images.githubusercontent.com/69497361/91880918-05c5b200-ec81-11ea-897c-c3d1e0331d0a.png)

Official core, 8x
![Valkyrie Profile-200901-182437](https://user-images.githubusercontent.com/69497361/91881072-3b6a9b00-ec81-11ea-9724-ef89e1b71105.png)

**Comment by xzn** [comment]
I really appreciate you continue helping testing this out. The bug in Valkyrie Profile is actually from a different change and not meant for you to test :]

[mednafen_psx_hw_libretro.zip](https://github.com/libretro/beetle-psx-libretro/files/5158301/mednafen_psx_hw_libretro.zip)

The bug still shows up if you change the internal resolution while the game is running, but it's gone if you close and restart the emulator. I'm a bit tired to progress on this one, sorry!

The current plan is to refactor the changes pertaining to this issue only into its own branch and send a pr. Please give me some time.

**Comment by Blakrajder** [comment]
I likewise appreciate your work. You've already did a lot. Time is what we definitely have, it's not a race.
I'm just testing and noting whatever pops in as an error in relation to the core build that I received.
Figured I can do at least this after playing on emulators close to 15 years XD

Freshest build indeed fixes the issue as you described.
From what I can see, the gap now shows up only when you change the internal resolution to 1x without restarting the core.
Internal resolutions of 2x and higher seem to be free of the issue even without the restart.

**Comment by Blakrajder** [comment]
One more tiny, tiny thing.

Latest custom build results in RetroArch crash during BIOS boot up (SONY & PS Logo) if internal resolution is set to 16x.
Crash can be avoided if save state is loaded immediately with the boot.
Another way to avoid the crash is to quickly open emulator menu, switch internal resolution to anything lower than 16x, continue with the emulation and wait for BIOS to pass, re-enable 16x

**Comment by xzn** [comment]
What game were you playing that resulted in crash? (and what settings?)

**Comment by Blakrajder** [comment]
Any game, any setting, crash happens only when using internal resolution of 16x during the BIOS stage.
Sometimes it does not crash but state of emulation goes down to 10FPS and below.

I tried even in reverse. I started emulation with internal resolution 8x, when BIOS started showing, I've switched to 16x and got immediate slowdown and crash.

 [Here's a video showing the process.](https://youtu.be/4LBdbdpNotM) Hope this will be of help.

**Comment by xzn** [comment]
I got the slow down now, but no crashes for me though :o

The slowdown also happens with the official core so I don't know what gives..

**Comment by Blakrajder** [comment]
You're right. It does happen on official core, no crash with the official one though. Don't know how I never noticed that before.
Sorry for unnecessary worry.

Interestingly enough, slowdown sorta happens on the initialisation and then everything runs smoothly when you use BIOS extracted from PSP. So it looks that there is something related to sony part of the BIOS boot up process.

Is it possible that BIOS is running only in software mode and then emu switches to hardware midway?
Just a thought, because I get uber crazy slowdowns like that whenever I try to run software mode with internal resolution higher than 2x.

Anyways, disregard, it's not a problem related to the black outlines fix.
