### ISSUE TITLE
Latest commit (d8a3e93) broke PAL games (only black screen with sound)

### ISSUE THREAD

**Issue by SigmaVirus** [libretro/beetle-psx-libretro#71]
It turns out that the latest commit from 2016-06-25 have broken PAL games completely as they only show a black screen with sound (refer to this thread http://libretro.com/forums/showthread.php?t=6174)

The last working commit was 465fdd9 compiled 2016-06-22

It doesn't matter what settings you change either, still black screen only with sound.

**Comment by simias** [comment]
There's only one commit after this one, and as far as I can tell it shouldn't do anything if you set the option "Video mode" to "auto" (the default).

Do you get a black screen with "Video mode" set to "auto"?

This particular commit seems to be worthless anyway, if it causes this regression I'll revert it.

**Comment by Axiphel** [comment]
Black screen is there with video mode set to auto.

**Comment by simias** [comment]
Ok, I've reverted the last commit. Hopefully that'll fix it.

**Comment by SigmaVirus** [comment]
It works again so I'll close the issue.

Thanks simias!

**Comment by simias** [comment]
Cool, thanks for taking the time to report it.
