### ISSUE TITLE
Final Fantasy IX (Italy) won't boot

### ISSUE THREAD

**Issue by NiBBa256** [libretro/beetle-psx-libretro#711]
I have the PAL BIOS as well as the subchannel data. PCSXReARMed runs the game just fine. I have skip BIOS turned off.

**Comment by bslenul** [comment]
Stuck on black screen? Or "Failed to load content"?

If stuck on black screen, make sure the .sbi files (http://redump.org/sbi/psx/) have the same filenames as the .cue files, so for example if you have `Final Fantasy IX (Italy) (Disc 1).cue` then .sbi for disc 1 should be `Final Fantasy IX (Italy) (Disc 1).sbi`.

Works fine for me anyway: ![image](https://user-images.githubusercontent.com/33353403/90766343-a87a4a00-e2eb-11ea-9d51-bcab36e7fd5d.png)

**Comment by NiBBa256** [comment]
OK, so I used mednafen and it turned out the PAL BIOS I used was at fault. Apparently it was a bad dump. It works fine now after a different BIOS.
