### ISSUE TITLE
Cannot change renderer to hardware

### ISSUE THREAD

**Issue by gourdcaptain** [libretro/beetle-psx-libretro#72]
I have version 1238.4ad02c7-1 installed on Arch Linux (64-bit). When I run the core in Retroarch, it won't let me change the renderer away from software in the menu. Any suggestions?

**Comment by gourdcaptain** [comment]
Trying to change it in the config file for "retroarch-core-options.cfg" to "opengl" (I also tried "hardware") results in it still loading software and changing the config file back when Retroarch closes.

**Comment by needo2** [comment]
That happens when it's not built with HAVE_OPENGL=1

**Comment by novicestar** [comment]
I have this same issue
