### ISSUE TITLE
(Regression) (Vulkan) Suikoden freezes and crashes RetroArch after the PS1 BIOS logos.

### ISSUE THREAD

**Issue by bslenul** [libretro/beetle-psx-libretro#736]
## Description

When trying to play Suikoden (I'm using USA 1.1 redump version, haven't tried with the other regions of the game), after the BIOS logos it's just a black screen then RetroArch just hangs (it doesn't crash directly, I have to force it to close, so I can't get a crash log with retroarch_debug.exe unfortunately). It seems to be only happening with vulkan driver, glcore is fine, software too.

My Linux VM doesn't support vulkan so I can't confirm if it's happening on Linux too or not... :/ 

### Expected behavior

Starts the game normally.

### Actual behavior

Black screen + hangs RetroArch after the PS1 logos when using vulkan driver.

### Steps to reproduce the bug

1. Select vulkan as video driver.
2. Start Suikoden (USA, idk if it's happening with EU/JP versions).

### Bisect results

After bisecting, e90953d seems to be the first "bad" commit.

### Version/Commit

- Beetle PSX HW: 0.9.44.1 / a7c353c

### Core options

Defaults.

### Environment information

- Frontend: RetroArch / 1.9.0 / 9ca09e8
- OS: Windows 10 64bit
- Compiler: MSYS2 used for the bisect (gcc 10.1.0 Rev2 apparently)
- GPU: GTX 970

**Comment by xzn** [comment]
Thank you for the report. The cause was an infinite loop due to an empty clear command which is something I did not account for.

I've submitted a PR that should resolve this.

**Comment by bslenul** [comment]
Yup, just tested your PR, the game boots just fine now! That was quick, thank you! 👍
