### ISSUE TITLE
In GUI no shader is loaded, however shader is still shown in core's CFG

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#74]
On a clean install of RetroArch, I updated all of my cores, but this time I left out the regular "Mednafen PSX" and instead only downloaded "Mednafen PSX HW".

When launching content, after loading the Mednafen PSX HW core, it would only show a black screen, however you could hear the audio.

As a test, I downloaded the Mednafen PSX (regular), and launched content which worked. Afterwards, I loaded up the Mednafen PSX HW core and tried loading content as well. This time it worked. So it appears that loading content in Mednafen PSX HW requires having already loaded content with Mednafen PSX (standard).

As a second test, I found out the problem is also reproducible by just deleting the "mednafen_psx_libretro.dll" cfg file and leaving the "mednafen_psx_hw_libretro.dll" intact.

I am on Windows 10 x64, using the stable 1.3.6 retroarch build, with the newest buildbot cores as of today.

**Comment by saftle** [comment]
It appears to affect the HW renderer period. Please disregard the information about the CFGs. What was happening, is that if a CFG didn't already exist, Medfnafen PSX HW would load OGL by default, rather than software.

**Comment by fr500** [comment]
Make sure you don't have a CG shader selected, that's all

**Comment by saftle** [comment]
I don't have a cg shader loaded, and it is occurring on two PCs that both have GTX 970s with the newest driver. I'll try to troubleshoot more tomorrow. I have a strong feeling that is has something to do with the newest Nvidia driver.

**Comment by saftle** [comment]
@fr500 actually you were right. It appears that in the GUI it shows no shaders are loaded, however in the core's CFG the shader was still there.

Since, I have cfgs per core enabled, it initially used the shader that I had loaded previously from the retroarch.cfg (which is to be expected). After loading the core, I had brought the shader passes parameter to 0, and saved by exiting retroarch (in order to remove the loaded shader). However, it appears to still load regardless, since the line in the CFG does not get removed.

I didn't have this problem in 1.3.4 and 1.3.2. Do you think it could be perhaps a problem with the new feature allowing you to change the shader settings prior to loading content?

**Comment by saftle** [comment]
This will most likely be fixed in the next stable, since core configs have been revamped using overrides instead.
