### ISSUE TITLE
Tomb Raider 3 sound looping when game paused.

### ISSUE THREAD

**Issue by ewertonpires2** [libretro/beetle-psx-libretro#757]
# First and foremost consider this:
- This is a DEVELOPER oriented channel dedicated to report bugs and suggest features about the libretro core, please do not ask for help. If you need help, go to https://forums.libretro.com/;
- The upstream bug tracker is a forum thread, located at https://forum.fobby.net/index.php?t=msg&th=1114;
    - Note: As of October 2018, Microsoft email providers (think email addresses ending with hotmail/live/outlook) are rejecting email from the forum. If you want to register an account in the upstream project's forum, consider using another mail provider.
- For game-related bugs:
    1) First, check if it's already reported on the upstream bug tracker;
    2) If it's not reported there, try to reproduce the bug with mednafen;
    3) If it's reproducible with mednafen, report it on the upstream bugtracker;
    4) If it's not reproducible with mednafen, ONLY THEN should you report it here.
    5) DO NOT report Beetle-specific bugs on the upstream tracker.

## Description

The sounds of ambient effects are repeated in Tomb Raider 3 when the game is paused.

### Expected behavior

The sound should be summarized and not be repeated.

### Actual behavior

[What is actually happening]
https://youtu.be/Nr7DerwmHIc

### Steps to reproduce the bug

1. Select the level, you can select New Game
2. When secret shime plays, press start and the sound will repeat (issue).
3. Repeat everytime.
### Bisect results

[It happened only with Beetle PSX core, on Mednafen is ok.]

### Version/Commit

[If you're using RetroArch, this information is on the bottom left after loading the core. You can do this via Main Menu -> Load Core]

- Beetle PSX: [Beetle PSX (0.9.44.1 c6ee7ce]
Please specify whether you are using Beetle PSX or Beetle PSX HW.

### Core options

[None] is seted as "default".

Please also specify, if reporting a graphical glitch for Beetle PSX HW, your "Renderer" core option setting and your frontend selected video driver.

### Environment information

- Frontend: [RetroArch]
- OS: [Windows 10 Pro]
- Compiler: [none]
- GPU: [GTX 1060]

**Comment by bslenul** [comment]
Bisected, started happening with this commit: 18a9de19f3f079408eb8181aa4c5144e9434c5f7.

Btw, this does not happen in standalone Mednafen.

**Comment by ewertonpires2** [comment]
It happens only with RetroArch with Beetle PSX core, doen't happen with Mednafen.

**Comment by bslenul** [comment]
> You should test using RetroArch.

That's what I did for the bisect :D The commit I mentioned means the bug started happening from here (so the bug is here since late December 2019). It's just to, hopefully, help the devs for a fix ;)
