### ISSUE TITLE
New Update improves Reverb Emulation 

### ISSUE THREAD

**Issue by TesterNes** [libretro/beetle-psx-libretro#761]
Mednafen 1.26.1 include a more accurate SPU reverb emulation.
It will be perfect if the libretro core is updated to 1.26.1 in pursuit of  sound fidelity and preservation. 
The update will fix too more than 12 games that have serious problems. 

Thanks for your work.

**Comment by Awakened0** [comment]
This was just backported: 76750ab9ee7598ea03ce1de4dcc86cd119334d6a
