### ISSUE TITLE
Final Fantasy VIII (German version) does not run at all

### ISSUE THREAD

**Issue by coldspark29** [libretro/beetle-psx-libretro#771]
## Description
It does not start with Beetle, ReArmed or Duckstation. It does start with ePSXe

### Expected behavior
It should start

### Version/Commit

[If you're using RetroArch, this information is on the bottom left after loading the core. You can do this via Main Menu -> Load Core]

- Beetle PSX: 2483-1 
- Beetle PSX HW: 2483-1

Tried both

### Core options
Standard options

### Environment information

- Frontend: Lakka, Lutris
- OS: Lakka, Manjaro
- GPU: Raspberry Pi4, Intel UHD620

**Comment by Kupo91** [comment]
I also play the german version and it works for me. You probably forgot to get the *.sbi files

**Comment by coldspark29** [comment]
@Kupo91 Never needed those before. It works now. Dankee :)
