### ISSUE TITLE
Camera problem in サルゲッチュ (Ape Escape)

### ISSUE THREAD

**Issue by ape123** [libretro/beetle-psx-libretro#78]
The camera doesn't move in the way it's supposed to, making the game very hard to play because you have to adjust it with L1 constantly. Upstream mednafen doesn't have this issue.

**Comment by twinaphex** [comment]
that's too vague a description for me.

Maybe you just mean the analogue controls are off.

**Comment by ape123** [comment]
I don't know how to explain it well, but I think it should be apparent if you play it in upstream mednafen and beetle-psx-libretro and compare. Like for instance in the libretro port the camera often moves in such a way that you can't see where you're going.

About analog sticks, well you don't control the camera with the analog sticks.

**Comment by twinaphex** [comment]
I don't use 'upstream' Mednafen and never will. I will only use the libretro versions.

Anyway,I can look into backporting some of the analog-specific code which hasn't yet been carried over I guess.

**Comment by saftle** [comment]
@ape123 Do you perhaps have "Analog to Digital Type" enabled in the input options? If it's enabled, it can cause problems if you're using DualShock as well.

**Comment by ape123** [comment]
@saftle Man, this input configuration mess in RetroArch... Anyway, yes I had "Analog to Digital Type" on since I like to play non-Dual Shock games with analog controls as well, and that seems to have been the issue (camera can be moved with the d-pad in this game). I was really sure that Dual Shock mode would cancel out any d-pad emulation, but I guess not. I turned it off now and the game's camera is acting normal. Thanks for the help.

**Comment by twinaphex** [comment]
What is a 'mess' about it? You are NOT SUPPOSED to edit Settings -> Input -> binds all the time, you are supposed to use quick menu -> controls to create per-game remappings in case the defaults don't suit you. 

In 90% of all cases there should be no real need to change the defaults.

There is no mess about this at all, it is just different from what you are usually used to in other emulators, and it's a definite case of convention over configuration.

**Comment by saftle** [comment]
@twinaphex I think it's not necessarily a mess, but it's not the first thing a user realizes is the case. It took me a good year to figure it out as well, and always assumed that it was perhaps a bug with certain games. This may explain issues such as https://github.com/libretro/beetle-psx-libretro/issues/40 as well. 

As a feature request, would it be possible to automatically disable analog to digital if Dualshock Analog Toggle is enabled, and was turned on by holding in "Start, Select, L1, L2, R1, and R2"? I figured there is probably never a case where in-game analog to digital should be enabled if Dualshock is enabled as well.
