### ISSUE TITLE
Donald Duck Goin' Quackers: First FMV is cut short.

### ISSUE THREAD

**Issue by IdiotBlueMage** [libretro/beetle-psx-libretro#781]
In Donald Duck: Goin' Quackers, the first FMV cuts short and goes straight to the game.

### Expected behavior
The FMV plays competely.

### Actual behavior
The FMV only plays the first second or two.

### Steps to reproduce the bug

1. Start game from the beginning.
2. Observe opening FMV.

### Version/Commit

Beetle PSX HW: (0.9.44.1) (49e73a2)

### Core options

Software Renderer, Pure Interpreter, no PGXP, 1X internal resolution, pretty much playing this as Beetle PSX.

### Environment information

- Frontend: RetroArch Plus 1.90
- OS: Android

**Comment by ZachCook** [comment]
Is this a duplicate of #583 fixed by changing the controller type?

**Comment by IdiotBlueMage** [comment]
> Is this a duplicate of #583 fixed by changing the controller type?

Just tested it, looks like that's the case.  Sorry about that, I must not have searched for closed tickets when I looked for a similar issue.  Thanks, guess I should close this one.
