### ISSUE TITLE
Widescreen bugs with GL Renderer

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#79]
Creating a new issue for this, since this is a bit more unique in comparison to the other gl renderer bugs.

**Widescreen not enabled by default, regardless of core option**

The following can be reproduced with any game:

1. Load content with widescreen enabled.
2. Game will not be in widescreen, even though the option is enabled.

Workaround:

After loading a game, disable and then re-enable the widescreen core option.

**Widescreen gets disabled automatically during certain loading screens**

Reproduced with Apocalypse (USA):

1. Succcessfully finish a level with widescreen enabled.
2. After the loading screen appears and disappears, the game will default back to non-widescreen even though the core option is enabled.

Workaround:

Disable and then re-enable the widescreen core option.

**Comment by simias** [comment]
That should fix it, thanks for taking the time to report it
