### ISSUE TITLE
Crash when both retroarch and beetle-psx-hw set to vulkan and msi afterburner runs

### ISSUE THREAD

**Issue by rtentser** [libretro/beetle-psx-libretro#790]
Windows 10.

Can't reproduce it if either or both retroarch and beetle-psx-hw set to gl. Can't reproduce it when msi afterburner isn't running. But when it is and both retroarch & beetle-psx-hw set to vulkan, i can't run the core (at least with "Clock Tower: The First Fear", didn't test it with other games yet) — retroarch just crashes to desktop.

**Comment by Ryunam** [comment]
Which version of MSI Afterburner are you using? Try to update both Afterburner and RTSS to the latest beta and see if it's still happening. I can't seem to reproduce this issue on my Windows 10 x64 system.

**Comment by rtentser** [comment]
Didn't try betas, but updated RivaTuner to 7.3.1 stable and it fixed the problem. Thanks!

**Comment by Ryunam** [comment]
Glad to hear that!
