### ISSUE TITLE
[Bug/Workaround Request] Disable precaching when loading from physical media

### ISSUE THREAD

**Issue by Sanaki** [libretro/beetle-psx-libretro#795]
Loading games via physical media stalls eternally when precache is enabled. Auto-disabling precache whenever the loaded file is named `drive[n].cue` would sort this nicely. In my case I have two drives, so I've had to make configs disabling it for `drive2` and `drive3`.

**Comment by ZachCook** [comment]
I have a patch for this, though not sure if it should be as another option precache-nodrive instead of changing the behavior of precache, it seems like it can precache it would just take about an hour, and so is pretty useless compared to dumping the disk first

**Comment by Sanaki** [comment]
I'm not sure that really qualifies as a useful feature at that timeframe....
