### ISSUE TITLE
[Workaround Suggestion] Add delay before applying GPU Rasterizer Overclock

### ISSUE THREAD

**Issue by ichee** [libretro/beetle-psx-libretro#796]
# First and foremost consider this:
- This is a DEVELOPER oriented channel dedicated to report bugs and suggest features about the libretro core, please do not ask for help. If you need help, go to https://forums.libretro.com/;
- The upstream bug tracker is a forum thread, located at https://forum.fobby.net/index.php?t=msg&th=1114;
    - Note: As of October 2018, Microsoft email providers (think email addresses ending with hotmail/live/outlook) are rejecting email from the forum. If you want to register an account in the upstream project's forum, consider using another mail provider.
- For game-related bugs:
    1) First, check if it's already reported on the upstream bug tracker;
    2) If it's not reported there, try to reproduce the bug with mednafen;
    3) If it's reproducible with mednafen, report it on the upstream bugtracker;
    4) If it's not reproducible with mednafen, ONLY THEN should you report it here.
    5) DO NOT report Beetle-specific bugs on the upstream tracker.

## Description

GPU Rasterizer Overclock set to x16 or higher causes BIOS to briefly stall during boot.

Adding a delay of some kind before applying rasterizer overclock could mitigate issue.
Commit 1f620d01944ffce505b610b87d563b7f8d4478e7 does something similar with interpreter to fix a crash related to dynarec.

Testing with Chrono Cross (USA), but occurs regardless of game.

This game needs at least x16 for status menu to not flicker or glitch when changing to next character.

### Expected behavior

BIOS to continue booting uninterrupted.

### Actual behavior

During bootup on the first screen with the playstation diamond, boot hangs with audio stuck on last sound for approximately
2-5 seconds.

### Steps to reproduce the bug

Boot up bios with GPU Rasterizer Overclock set to x16 or higher.

### Bisect results

N/A

### Version/Commit

Beetle PSX Latest build as of now, but occurs on builds as old as 1 year ago, no older builds on hand.

Also tested with Beetle PSX HW

Retroarch 1.9.4, also tested with latest nightly and with older build 1.8.9.

### Core options

All defaults.

Changing other options makes no difference.

### Environment information

Windows 10
Intel 9820x
Nvidia GTX 1080TI

NTSC-U bios

**Comment by ZachCook** [comment]
You should be able to use the skip bios option to get past that stall, I don't think this is worth the additional complexity to create a workaround to fix problems caused by another workaround to fix a bug, better to fix the status menu flickering directly instead. My similar hack to fix the dynarec+runahead issue was more of a last resort to fix a crash, not something that should be used if it can be avoided.

**Comment by ichee** [comment]
I would agree, except the status menu flickering issue is also present upstream, so it is unlikely to be fixed in the libretro core until upstream also fixes it.

Working around the issues caused by the rasterizer overclock is currently the only available solution here, and I personally would prefer not to have to skip the BIOS if avoidable, for nostalgic reasons, helps set the mood.

**Comment by ichee** [comment]
Since the remaster of Chrono Cross was released, enabling GTE overclock, despite the increased character model rotation speeds in the status menu, seems accurate to the remaster behavior, even though the slower rotation matches original hardware, though original didn’t have the interlacing artifacts when switching between characters in status menu.

So if there’s no other reasoning, then I’m considering this resolved.
