### ISSUE TITLE
Add Option for Fastboot

### ISSUE THREAD

**Issue by RyanBram** [libretro/beetle-psx-libretro#8]
Hi Developers,
Is it possible to add option for skipping PSX BIOS logo screen and directly go to the game?
If no, please add the option for it.
Thanks.

**Comment by Warriors-Blade** [comment]
It used to have that option until it was removed in vanilla mednafen.

It would be really appreciated if it would make a return tough.

**Comment by hizzlekizzle** [comment]
It was taken out because it breaks some games.

**Comment by Awakened0** [comment]
This is back in and works fine with a few games I tested. It probably still breaks some games; if someone finds them it'd be useful to note which ones break when it's enabled on the compatibility wiki page. Or in the description of the option on the core's page.

**Comment by rz5** [comment]
Feature has been implemented, as can be seen  by the discussion and the 'Skip BIOS' core option.
