### ISSUE TITLE
V-Rally 2 (PAL) - Game doesn't pass the "Loading Game Mode" Screen

### ISSUE THREAD

**Issue by Pat86** [libretro/beetle-psx-libretro#80]
After choosing a car and game mode, the game just stays on the "Loading Game Mode" Screen and doesnt pass it. Keeps loading forever.

![retroarch-0818-174558](https://cloud.githubusercontent.com/assets/20128108/17780601/4a09bf88-656c-11e6-9aa3-9e23b775a356.png)

**Comment by OptimalJew** [comment]
Was testing this, and a kind anon suggested that it could be a copy protection issue. Turns out, it is. With the .sbi file in the same directory as the bin/cue, it works perfectly.

![v-rally - championship edition 2 europe en fr de -171008-182153](https://user-images.githubusercontent.com/31424143/31321556-f8088638-ac55-11e7-9a2b-0615f2c918dc.png)

**Comment by rz5** [comment]
@OptimalJew - you're on fire today. Marked as invalid. Closing.

**Comment by Pat86** [comment]
Thanks for the info. Any chance, we'll see a auto-patching feature in the future?

**Comment by rz5** [comment]
@Pat86 - SBI files can be considered patches and the core already auto-applies them (when they're present). If you want the core to bake in all the SBI files present in http://psxdatacenter.com/sbifiles.html , I suggest pitching the idea to the upstream author.

**Comment by yorkashton** [comment]
> Was testing this, and a kind anon suggested that it could be a copy protection issue. Turns out, it is. With the .sbi file in the same directory as the bin/cue, it works perfectly.
> 
> ![v-rally - championship edition 2 europe en fr de -171008-182153](https://user-images.githubusercontent.com/31424143/31321556-f8088638-ac55-11e7-9a2b-0615f2c918dc.png)

hello i see same problem on emulators and ps1 console.  i was burn ro cd and tried to play on ps1 console. i see this problem.
this game is most important for me on the ps1.
how i can fix it? i downloaded sbi file. how i can put this file in cd?
