### ISSUE TITLE
BIOS Corruption (Always) and Game Crashes (Under certain circumstances)

### ISSUE THREAD

**Issue by RobertCochran** [libretro/beetle-psx-libretro#809]
## Description

BIOS boot screen has glitches with audio and video (almost as if its corrupted), and in certain circumstances, some games will crash.

While I've only gotten crashes in one game (Crash Team Racing US), the BIOS glitch manifests in some way or another in every game I tried.

I've verified matching md5sums both for 
my BIOS (SCPH-5501.bin) via http://www.lakka.tv/doc/BIOSes/#bios-requirements-table
and for CTR itself via http://redump.org/disc/2397/

### Expected behavior

BIOS does not glitch in any way and game does not crash.

### Actual behavior

A video of me going through my core settings then a full boot from BIOS to crash. I changed the CPU mode here because running any of the dynarec modes and triggering this crash will cause Retroarch itself to crash due to bad instructions.

https://youtu.be/La3qWs3EeoM

### Steps to reproduce the bug

1. Start a PlayStation game (for BIOS glitches)
2. What will/won't cause a crash is kinda up in the air. All of the circumstances where I've encountered crashes are where the game is trying to save, but it's not every time the game wants to save. For CTR, it wants to happen for most (but not all) Relic Races/Time Trials modes when saving a new top time.

### Bisect results

I'm not set up to do this right now. Sorry!

### Version/Commit

Beetle PSX HW 0.9.44.1 f71ab8b (should be the latest version of the core from Retroarch)

### Core options

All core options are shown in the demo video. Frontend video driver is `vulkan`. I've tried many variations of the settings in attempting to pin down what the problem is. It doesn't matter if I'm using dynarec or not, nor does hardware vs software renderer: all combinations lead to BIOS glitches and eventual crashes.

### Environment information

- Frontend: Retroarch 1.9.0
- OS: Windows 10 Pro 64bit 20H2 build 19042.110
- GPU: AMD Radeon RX 6800 XT (PowerColor Red Devil variant) @ Driver 21.7.1

-----

If anything else is needed, please do ask and I'll do my best to do it for you. Thanks all for your hard work in making this all go, this has otherwise been a wonderful emulation experience!

**Comment by RobertCochran** [comment]
[ctr.txt](https://github.com/libretro/beetle-psx-libretro/files/6949756/ctr.txt)

I forgot to upload this at post time, oops! This is the savestate I made in the video. It's been renamed to `crt.txt` as opposed to `ctr.state` because Github won't let you keep that extension on it.

**Comment by ZachCook** [comment]
The BIOS stuff is known issue with hw renderers, setting to software will fix at the cost of performance (will not be able to go to 8x, so not really worth it unless there are other issues, you can also just skip bios), I haven't been able to reproduce your crash even with the same settings and save state you provided, though I am using a different OS, I'll check later a windows system to see if it is specific to that, maybe backup your configuration and try default config to see if that changes anything?

**Comment by RobertCochran** [comment]
> The BIOS stuff is known issue with hw renderers, setting to software will fix at the cost of performance (will not be able to go to 8x, so not really worth it unless there are other issues, you can also just skip bios),

Ah, gotcha. Not knowing that, I thought it might have been indicative of some deeper emulation related problems. Sure enough, goes away in the software render. Sorry for the repeat report on that, then.

> maybe install the latest retroarch to a seperate folder and use default config to see if anything changes?

I'll do this and report back.

**Comment by RobertCochran** [comment]
> I'll do this and report back.

At bone-stock default settings, it worked like a charm. I'll start tuning some options to see what will stick.

**Comment by RobertCochran** [comment]
I have my core settings more or less identical to my 'real' settings and at this point, it hasn't crashed a single time. I'll go ahead and upgrade the system Retroarch and double-check for issues.

**Comment by RobertCochran** [comment]
Upgrading the system Retroarch to 1.9.7 didn't fix the issue. It's still crashing in the same spot. So that means there must be something else that I've changed (knowingly or not) that's causing the crashes. Where else would be good places to look?

**Comment by ZachCook** [comment]
Does it depend on the state of the memory card? Try backing up and moving the existing memory card and starting from a new one.

**Comment by RobertCochran** [comment]
A fresh memory card results in no crash... so yeah, that's where the issue is at this point. How bizarre.

**Comment by ZachCook** [comment]
Glad I could help narrow it down, maybe the memory card was partially corrupted by some bad setting earlier, or maybe the crash just requires some existing data, lots of testing you can do if you feel like it.

**Comment by RobertCochran** [comment]
Suddenly, the game decided to cooperate and not crash, though it's pretty clear at this point there's a case of memory card corruption going on:

![](https://cdn.discordapp.com/attachments/396379528982822922/876738700170637352/20210816000054_1.jpg)

So ultimately I don't believe there to be any emulation faults at this time. I'll explore some of the other circumstances that were causing crashes, maybe they won't anymore.

**Comment by RobertCochran** [comment]
> I'll explore some of the other circumstances that were causing crashes, maybe they won't anymore.

At least one other circumstance where it was crashing (Dragon Mines during the Relic Race) still exhibits crashing. I'm sure the other spots it was being sulky still have issues as well, I just didn't get around to testing them.

I'm gonna go ahead and close this issue for the moment - I'm convinced that my issues regarding the crashing are because of memory card corruption and not emulation faults.
