### ISSUE TITLE
Digimon World Sprite-Graphic Issue

### ISSUE THREAD

**Issue by JacobAL** [libretro/beetle-psx-libretro#86]
Sometimes (a lot of the time) sprites are misaligned. I think this also applies in some cases to elements in the pre-rendered backgrounds since sometimes things don't seem to be interactable where you think they'd be.
I haven't noticed any similar issues in other games.

Here's some pictures of what I mean, both in 16:9 and 4:3 and there's a picture with native res instead of 2x res (my normal).

Clock's hand is offset: http://i.imgur.com/561AyrX.jpg
Aggro indicators for battle are all over the place: http://i.imgur.com/0APf6MG.jpg
4:3 with native res: http://i.imgur.com/6ovSKLa.jpg

As far as I can tell, this is not an issue in the mednafen standalone:
http://i.imgur.com/bxWja1J.jpg
http://i.imgur.com/pYpHpQW.jpg

**Comment by saftle** [comment]
Do the issues only occur when the widescreen core option is enabled? If yes, then that wouldn't be a bug. Most games with pre-rendered backgrounds do not work with it (Chrono Cross for example).

**Comment by saftle** [comment]
The widescreen (16:9) pics aren't relevant to the issue, since Widescreen does not work on most games with pre-rendered backgrounds (Chrono Cross is a good example). This isn't a bug.

However, the 4:3 screenshot is interesting. I would double check to see if the widescreen option happens to be enabled within the core options.

**Comment by JacobAL** [comment]
Yes, turns out that widescreen mode was set to on. Sorry to have wasted your time with this and thanks for the help.

**Comment by saftle** [comment]
Oh no worries. Glad to help. Not everyone knows that PSX didn't have widescreen, so I figured that could have been an issue :)

**Comment by bigorilho** [comment]
thanks for the help
