### ISSUE TITLE
Alien 3 Level 3 Door Bug PAL/NTSC (Retroarch Linux)

### ISSUE THREAD

**Issue by orderorder** [libretro/beetle-psx-libretro#869]
## Description

In both the PAL/NTSC versions at level 3 of Alien Resurrection once I get the security card, I head to the area where there is an alien behind a security barrier hanging from the ceiling, but the card does not work. I have informed myself on the internet and the error may have to do with the synchronization of the audio.

### Expected behavior

I have seen several guides on youtube and the security card disables the barrier and allows you to advance in level 3

https://youtu.be/UIFrTpvhSok?t=195

### Version/Commit

Retroarch 1.12.0 - Beetle PSX HW 0.9.44.1 798fab9 / Mednafen 1.29.0 and Mednafen 1.31.0-UNSTABLE

### Core options

Default Core Options 

### Environment information

- Frontend: Retroarch 1.12.0
- OS: Manjaro Linux 21.3.7
- GPU: Nvidia 3070m

Save State

[Alien Resurrection (USA).state4.zip](https://github.com/libretro/beetle-psx-libretro/files/10071480/Alien.Resurrection.USA.state4.zip)

**Comment by bslenul** [comment]
Not a bug, you just didn't destroy the clones, you have to backtrack a bit for one and a bit more for the other one, once you destroy both it should open :)

![image](https://user-images.githubusercontent.com/33353403/203545510-50995ec8-3787-402a-bdbe-8847f4931895.png)

**Comment by orderorder** [comment]
Thank you, I am very embarrassed. I'm glad that sync problems with sound no longer occur with this emulator.
