### ISSUE TITLE
Widescreen hack not working when PGXP enabled

### ISSUE THREAD

**Issue by SpaceAgeHero** [libretro/beetle-psx-libretro#91]
Image is just being stretched.
(Ubuntu Xenial x64)

Thanks for adding PGXP.
For me it's a dream coming true.

**Comment by simias** [comment]
This commit fixes the issue, then I tried making a cleverer implementation using PGXP to identify which GPU polygons didn't make it through the GTE and apply the widescreen hack later on but I couldn't make it work the way I wanted... I guess I'll give it an other try when PGXP is better integrated.

Thank you for the report.

**Comment by simias** [comment]
Mmh, I just noticed I didn't push to libretro's repo, I'm not sure where I'm supposed to push anymore...

@twinaphex can I push directly to libretro/ now?
