### ISSUE TITLE
Add Ability to Hide OSD Messages (Analog enabled, bad sector, ect.) [Feature Request]

### ISSUE THREAD

**Issue by Awakened0** [libretro/beetle-psx-libretro#913]
The SwanStation core has an option to "Display OSD Messages" that you can turn off to hide them. This would be great to have in Beetle as well for a more immersive experience. Without having to disable all frontend notifications.

**Comment by DarthMew** [comment]
Added via https://github.com/libretro/beetle-psx-libretro/commit/349bc50e55b8d758efce65478a313d8a9ece320d

**Comment by Awakened0** [comment]
Thanks!!
