### ISSUE TITLE
HW Core Regressions: After committing PGXP changes

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#95]
After PGXP compatibility was merged, certain games show the wrong colors or continuously flash if the Internal Color Depth: 32bpp option is enabled. A good example game is Brave Fencer Musashi & Wild 9.

In this case, the problem is reproducible even when all PGXP relevant core options are disabled. The workaround is to turn off Internal Color Depth: 32bpp and re-enable it. However, the problem will occur every time new textures are loaded, so it's not a permanent fix.

I have reproduced this with the Windows Buildbot build from today.

**Comment by simias** [comment]
I can't seem to find any issue in Brave Fencer Musashi (but I don't know the game very well so I might be missing things). Is there some way to reproduce the issue easily?

**Comment by saftle** [comment]
If you start Brave Fencer Musashi with "Internal Color Depth: 32bpp" it should automatically show texture issues. This is with all core options disabled, shaders disabled, and only only Internal Color Depth: 32bpp being set. The first thing you'll notice is the opening video has weird bars going down the middle, and then more texture issues. If it's not reproducible on your end, I can make a video if need be. Thanks.

**Comment by saftle** [comment]
Found another issue, this time with Croc. Even with every core option disabled (every native option left alone, and all PGXP options disabled), the game continuously flashes in the opening video.

**Comment by saftle** [comment]
This was fixed awhile ago, but accidentally left it open.
